import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

/**
 * Phase 1.18B-0: the historical backtesting layer (`lib/backtesting/`, `data/historical/`)
 * must stay ISOLATED - production 2026 code must never import it, and no historical data
 * may be ingested yet (templates are header-only).
 */
describe("backtesting layer is isolated from production (Phase 1.18B-0)", () => {
  const root = process.cwd();
  const collect = (dir: string): string[] => {
    if (!existsSync(dir)) return [];
    const out: string[] = [];
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const p = join(dir, e.name);
      if (e.isDirectory()) out.push(...collect(p));
      else if (/\.(ts|tsx)$/.test(e.name)) out.push(p);
    }
    return out;
  };
  // Production paths that must NOT depend on the historical/backtesting layer.
  const PROD_DIRS = [
    "app", "components",
    join("lib", "model"), join("lib", "simulation"), join("lib", "data"),
    join("lib", "tournament-context"), join("lib", "recent-form"),
    join("data", "model-inputs"), join("data", "official"), join("data", "mock"),
  ];
  const importsHistorical = (src: string) =>
    /(?:from|import|require)\s*\(?\s*["'][^"']*(lib\/backtesting|data\/historical)[^"']*["']/.test(src);

  it("no production module imports lib/backtesting or data/historical", () => {
    for (const dir of PROD_DIRS) {
      for (const file of collect(join(root, dir))) {
        expect({ file, imports: importsHistorical(readFileSync(file, "utf8")) }).toEqual({ file, imports: false });
      }
    }
  });

  it("the contract types module is standalone (no imports)", () => {
    const src = readFileSync(join(root, "lib", "backtesting", "types.ts"), "utf8");
    expect(/^\s*import\s/m.test(src)).toBe(false);
  });

  it("no historical data ingested yet: templates are header-only (one line each)", () => {
    const dir = join(root, "data", "historical", "templates");
    const csvs = readdirSync(dir).filter((f) => f.endsWith(".csv"));
    expect(csvs.length).toBeGreaterThan(0);
    for (const f of csvs) {
      const lines = readFileSync(join(dir, f), "utf8").replace(/\n+$/, "").split("\n");
      expect({ f, lines: lines.length }).toEqual({ f, lines: 1 });
    }
  });

  it("the WC-2022 snapshot is committed but stays isolated (not imported by production)", () => {
    // Phase 1.18B-2 ingests the WC-2022 pilot snapshot. It lives in the backtesting
    // layer and must remain unimported by production (asserted by the test above) and
    // never wired into the model.
    const snap = join(root, "data", "historical", "snapshots", "wc-2022.ts");
    expect(existsSync(snap)).toBe(true);
    const src = readFileSync(snap, "utf8");
    // generated, derived-only, and typed against the backtesting contract
    expect(src.includes("GENERATED by scripts/generate-historical-2022.mjs")).toBe(true);
    expect(/@\/lib\/backtesting\/types/.test(src)).toBe(true);
  });

  it("no production module imports the historical snapshot", () => {
    for (const dir of PROD_DIRS) {
      for (const file of collect(join(root, dir))) {
        const src = readFileSync(file, "utf8");
        expect({ file, imports: /historical\/snapshots\/wc-2022/.test(src) }).toEqual({ file, imports: false });
      }
    }
  });
});

/**
 * Phase 1.18C-1: the match-level harness (`lib/backtesting/*`) must build features
 * directly from the historical snapshot and may reuse only IMPORT-SAFE production
 * pieces (`lib/model/config`, `lib/simulation/poisson`, type-only `lib/types`). It
 * must NOT import anything that transitively pulls in 2026 data: `data/model-inputs`,
 * `lib/model/features`, `lib/model/predict`, `data/official`, `lib/data`, or any 2026
 * snapshot.
 */
describe("backtesting harness avoids 2026 / production-data imports (Phase 1.18C-1)", () => {
  const root = process.cwd();
  const collect = (dir: string): string[] => {
    if (!existsSync(dir)) return [];
    const out: string[] = [];
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const p = join(dir, e.name);
      if (e.isDirectory()) out.push(...collect(p));
      else if (/\.ts$/.test(e.name)) out.push(p);
    }
    return out;
  };
  // Modules whose import would drag 2026 production data into the historical harness.
  const FORBIDDEN = [
    /data\/model-inputs/,
    /lib\/model\/features/,
    /lib\/model\/predict/,
    /data\/official/,
    /lib\/data["']/,
    /2026/,
  ];

  // Extract module specifiers from import/from/require statements (not comments).
  const importSpecifiers = (src: string): string[] => {
    const out: string[] = [];
    const re = /(?:from|import|require)\s*\(?\s*["']([^"']+)["']/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(src))) out.push(m[1]!);
    return out;
  };

  it("lib/backtesting/* imports no forbidden production/2026 module", () => {
    const files = collect(join(root, "lib", "backtesting"));
    expect(files.length).toBeGreaterThan(0);
    for (const file of files) {
      const specs = importSpecifiers(readFileSync(file, "utf8"));
      const bad = specs.find((s) => FORBIDDEN.some((re) => re.test(s)));
      expect({ file, forbidden: bad ?? null }).toEqual({ file, forbidden: null });
    }
  });
});
