import type { ClimateSuitabilityRow, ModelInputSource } from "@/lib/types";

/**
 * Phase 1.13 - climate-suitability snapshot (home-country 1991-2020 normals).
 * ---------------------------------------------------------------------------
 * GENERATED by scripts/generate-climate-snapshot.py - DO NOT EDIT BY HAND.
 *
 * Home-country monthly climate normals feeding the Klement/Joachim year-round
 * football-playability pillar. Raw monthly arrays are the trustworthy inputs; the
 * DERIVED 12-month playability suitability score (lib/model/climate-suitability.ts)
 * is a documented `candidate` heuristic, NOT source-backed.
 *
 * Provenance (MIXED family, status `candidate`):
 *  - 46 sovereign economies: World Bank Climate Knowledge Portal, CRU TS4.09
 *    monthly climatology 1991-2020 (tas deg C, pr mm/month). `source-backed`.
 *    CRU exports trace/near-zero arid-month precipitation as blank; blanks are
 *    stored here as 0.0 mm (documented; score-neutral). e.g. Qatar Jun-Sep.
 *  - England + Scotland: Met Office / HadUK-Grid constituent areal series,
 *    calendar-month means over 1991-2020. `official-derived` - NOT CCKP `GBR` and
 *    NOT parent-mapped to the United Kingdom.
 *
 * Raw source exports (CCKP .xlsx, Met Office .txt) are NOT committed. See
 * docs/CLIMATE_SUITABILITY_SNAPSHOT_AUDIT.md.
 */
export const CLIMATE_SUITABILITY_SOURCE: ModelInputSource = {
  family: "climateFamiliarity",
  label: "Climate suitability (home-country year-round playability)",
  sourceName: "World Bank Climate Knowledge Portal (CRU TS4.09); Met Office / HadUK-Grid",
  sourceUrl: "https://climateknowledgeportal.worldbank.org/",
  sourceDate: "1991-2020",
  retrievedAt: "2026-06-19",
  status: "candidate",
  notes:
    "MIXED family (candidate): 46 economies are source-backed monthly climate normals from the World Bank Climate Knowledge Portal (CRU TS4.09, 1991-2020; tas deg C + pr mm/month, published values used as-is; CRU blank arid-month precipitation stored as 0.0 mm). England + Scotland are official-derived from Met Office / HadUK-Grid constituent series (calendar-month means over 1991-2020) - NOT CCKP GBR and NOT parent-mapped to the UK. The DERIVED 12-month playability suitability score is a documented candidate heuristic (calibration deferred), capped at +/-25 Elo-equivalent pts; model weight unchanged.",
};

/** CCKP / ISO3 economy code -> app team id (source-backed rows only). */
export const CLIMATE_CODE_TO_ID: Record<string, string> = {
  DZA: "algeria",
  ARG: "argentina",
  AUS: "australia",
  AUT: "austria",
  BEL: "belgium",
  BIH: "bosnia-herzegovina",
  BRA: "brazil",
  CAN: "canada",
  CPV: "cape-verde",
  COL: "colombia",
  COD: "congo-dr",
  HRV: "croatia",
  CUW: "curacao",
  CZE: "czechia",
  ECU: "ecuador",
  EGY: "egypt",
  FRA: "france",
  DEU: "germany",
  GHA: "ghana",
  HTI: "haiti",
  IRN: "iran",
  IRQ: "iraq",
  CIV: "ivory-coast",
  JPN: "japan",
  JOR: "jordan",
  MEX: "mexico",
  MAR: "morocco",
  NLD: "netherlands",
  NZL: "new-zealand",
  NOR: "norway",
  PAN: "panama",
  PRY: "paraguay",
  PRT: "portugal",
  QAT: "qatar",
  SAU: "saudi-arabia",
  SEN: "senegal",
  ZAF: "south-africa",
  KOR: "south-korea",
  ESP: "spain",
  SWE: "sweden",
  CHE: "switzerland",
  TUN: "tunisia",
  TUR: "turkiye",
  URY: "uruguay",
  USA: "usa",
  UZB: "uzbekistan",
};

/** The 48 World Cup teams' home-country 1991-2020 monthly climate normals. */
export const climateSuitabilitySnapshot: ClimateSuitabilityRow[] = [
  { teamId: "algeria", countryNameRaw: "Algeria", climateCode: "DZA", monthlyTempC: [12.50, 15.17, 18.97, 23.09, 27.58, 31.95, 33.50, 33.00, 29.83, 24.67, 18.35, 13.67], monthlyPrecipMm: [9.66, 7.38, 8.18, 7.11, 6.02, 2.85, 2.56, 6.60, 8.17, 8.51, 8.66, 8.62], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "argentina", countryNameRaw: "Argentina", climateCode: "ARG", monthlyTempC: [21.65, 20.62, 18.76, 15.05, 11.45, 8.68, 7.96, 10.14, 12.69, 15.81, 18.53, 20.74], monthlyPrecipMm: [75.05, 72.60, 71.42, 56.55, 39.63, 32.77, 23.76, 24.71, 30.31, 56.08, 60.31, 72.53], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "australia", countryNameRaw: "Australia", climateCode: "AUS", monthlyTempC: [28.37, 27.58, 25.75, 22.47, 18.28, 15.27, 14.68, 16.34, 19.92, 23.26, 25.72, 27.34], monthlyPrecipMm: [86.93, 91.64, 57.39, 27.78, 23.55, 24.40, 20.39, 17.35, 16.77, 23.97, 35.75, 58.12], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "austria", countryNameRaw: "Austria", climateCode: "AUT", monthlyTempC: [-2.10, -0.99, 2.67, 7.11, 11.47, 15.09, 16.99, 16.82, 12.47, 7.94, 2.82, -1.33], monthlyPrecipMm: [56.83, 56.05, 72.93, 75.95, 110.36, 133.77, 140.50, 133.45, 108.28, 91.48, 81.49, 70.24], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "belgium", countryNameRaw: "Belgium", climateCode: "BEL", monthlyTempC: [3.21, 3.69, 6.58, 9.75, 13.46, 16.53, 18.60, 18.49, 15.05, 11.02, 6.77, 4.26], monthlyPrecipMm: [78.56, 68.05, 63.48, 50.95, 68.08, 76.37, 82.47, 79.54, 70.61, 80.06, 84.18, 93.80], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "bosnia-herzegovina", countryNameRaw: "Bosnia and Herzegovina", climateCode: "BIH", monthlyTempC: [0.35, 1.69, 5.39, 9.91, 14.37, 18.02, 20.12, 20.27, 15.57, 10.78, 5.95, 0.91], monthlyPrecipMm: [77.92, 78.64, 70.40, 85.98, 99.07, 95.27, 88.89, 69.03, 107.82, 105.25, 122.84, 113.70], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "brazil", countryNameRaw: "Brazil", climateCode: "BRA", monthlyTempC: [26.05, 25.97, 25.85, 25.54, 24.65, 23.95, 23.86, 24.87, 25.86, 26.49, 26.23, 26.21], monthlyPrecipMm: [235.22, 225.64, 241.20, 188.21, 134.97, 84.51, 66.00, 53.24, 73.22, 117.12, 159.69, 199.23], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "canada", countryNameRaw: "Canada", climateCode: "CAN", monthlyTempC: [-21.27, -20.06, -14.92, -6.30, 2.37, 9.49, 13.11, 11.70, 6.14, -1.66, -10.90, -17.61], monthlyPrecipMm: [36.24, 28.06, 32.42, 31.58, 40.10, 57.64, 66.73, 62.93, 56.99, 52.28, 45.02, 38.89], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "cape-verde", countryNameRaw: "Cabo Verde", climateCode: "CPV", monthlyTempC: [20.60, 20.10, 20.44, 20.90, 21.49, 22.60, 23.73, 24.66, 25.21, 24.74, 23.58, 22.15], monthlyPrecipMm: [6.72, 5.23, 2.98, 5.39, 4.91, 4.80, 12.67, 36.83, 55.42, 36.39, 9.23, 7.16], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "colombia", countryNameRaw: "Colombia", climateCode: "COL", monthlyTempC: [25.20, 25.48, 25.58, 25.38, 24.96, 24.64, 24.47, 24.70, 24.98, 25.05, 25.07, 25.10], monthlyPrecipMm: [102.37, 116.25, 181.67, 243.15, 298.64, 280.66, 262.71, 233.55, 233.77, 235.38, 220.99, 151.94], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "congo-dr", countryNameRaw: "Democratic Republic of Congo", climateCode: "COD", monthlyTempC: [24.38, 24.81, 24.99, 24.87, 24.59, 23.70, 23.25, 23.88, 24.34, 24.50, 24.42, 24.27], monthlyPrecipMm: [128.67, 116.83, 162.46, 151.09, 106.98, 62.82, 61.77, 90.37, 122.51, 167.45, 174.91, 154.04], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "croatia", countryNameRaw: "Croatia", climateCode: "HRV", monthlyTempC: [1.86, 3.33, 7.16, 11.69, 15.99, 19.79, 21.86, 21.77, 17.11, 12.30, 7.49, 2.55], monthlyPrecipMm: [74.05, 73.71, 69.24, 84.24, 93.88, 92.52, 80.09, 81.82, 115.62, 114.30, 122.73, 106.10], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "curacao", countryNameRaw: "Curaçao (Neth.)", climateCode: "CUW", monthlyTempC: [26.97, 27.03, 27.20, 28.08, 28.63, 28.98, 28.84, 29.31, 29.69, 29.16, 28.16, 27.48], monthlyPrecipMm: [55.65, 26.48, 22.90, 24.62, 18.17, 21.90, 38.66, 32.57, 31.93, 95.56, 119.00, 90.68], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "czechia", countryNameRaw: "Czech Republic", climateCode: "CZE", monthlyTempC: [-1.28, -0.01, 3.62, 8.76, 13.24, 16.59, 18.47, 18.15, 13.48, 8.52, 3.62, -0.17], monthlyPrecipMm: [40.56, 33.21, 44.37, 38.85, 70.53, 80.19, 91.53, 76.82, 60.39, 48.14, 43.63, 44.47], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "ecuador", countryNameRaw: "Ecuador", climateCode: "ECU", monthlyTempC: [21.82, 21.91, 21.91, 21.83, 21.73, 21.13, 20.65, 20.86, 21.17, 21.47, 21.53, 21.62], monthlyPrecipMm: [171.22, 220.36, 271.94, 267.00, 246.09, 184.72, 166.17, 95.87, 102.44, 124.28, 144.85, 131.07], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "egypt", countryNameRaw: "Arab Republic of Egypt", climateCode: "EGY", monthlyTempC: [13.68, 15.15, 18.74, 23.19, 27.06, 29.67, 30.56, 30.52, 28.66, 25.10, 19.53, 15.20], monthlyPrecipMm: [3.86, 3.30, 1.97, 1.37, 0.90, 0.31, 0.52, 0.73, 0.22, 1.18, 2.07, 3.09], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "france", countryNameRaw: "France", climateCode: "FRA", monthlyTempC: [4.31, 4.86, 7.67, 10.39, 13.97, 17.48, 19.75, 19.63, 16.30, 12.43, 7.74, 4.91], monthlyPrecipMm: [72.28, 56.92, 57.10, 63.78, 70.60, 68.65, 59.18, 64.48, 73.97, 82.03, 90.39, 81.71], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "germany", countryNameRaw: "Germany", climateCode: "DEU", monthlyTempC: [0.87, 1.75, 4.89, 9.30, 13.29, 16.58, 18.60, 18.40, 14.40, 9.75, 5.04, 1.72], monthlyPrecipMm: [53.52, 45.05, 47.49, 41.95, 66.06, 75.33, 88.46, 78.38, 59.09, 59.32, 54.80, 59.66], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "ghana", countryNameRaw: "Ghana", climateCode: "GHA", monthlyTempC: [27.40, 29.52, 30.29, 29.67, 28.54, 27.11, 26.07, 25.61, 26.18, 27.16, 27.94, 27.25], monthlyPrecipMm: [9.62, 27.86, 66.79, 114.60, 148.14, 170.12, 146.46, 139.98, 177.52, 150.18, 44.03, 14.83], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "haiti", countryNameRaw: "Haiti", climateCode: "HTI", monthlyTempC: [22.84, 23.27, 23.84, 24.57, 25.29, 26.29, 26.31, 26.52, 26.25, 25.66, 24.60, 23.52], monthlyPrecipMm: [41.28, 53.50, 78.39, 123.74, 221.20, 115.45, 123.15, 156.48, 187.95, 212.84, 128.14, 56.55], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "iran", countryNameRaw: "Islamic Republic of Iran", climateCode: "IRN", monthlyTempC: [5.98, 8.16, 12.72, 18.24, 23.56, 28.15, 30.03, 28.82, 24.95, 19.44, 12.43, 7.65], monthlyPrecipMm: [33.85, 29.38, 36.88, 29.06, 16.14, 4.02, 3.66, 2.90, 3.67, 10.04, 21.68, 28.20], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "iraq", countryNameRaw: "Iraq", climateCode: "IRQ", monthlyTempC: [9.93, 12.40, 16.54, 22.27, 28.17, 32.66, 35.22, 34.58, 31.09, 25.05, 16.38, 11.20], monthlyPrecipMm: [30.40, 27.59, 35.08, 28.47, 11.06, 0.59, 0.15, 0.06, 0.33, 7.48, 24.16, 28.67], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "ivory-coast", countryNameRaw: "Côte d'Ivoire", climateCode: "CIV", monthlyTempC: [26.27, 28.26, 29.06, 28.61, 27.64, 26.49, 25.37, 25.11, 25.67, 26.38, 26.96, 26.16], monthlyPrecipMm: [13.15, 33.57, 78.57, 122.64, 150.33, 180.78, 147.76, 154.91, 186.59, 152.81, 58.79, 19.78], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "japan", countryNameRaw: "Japan", climateCode: "JPN", monthlyTempC: [0.19, 0.76, 4.26, 9.81, 14.87, 18.68, 22.68, 23.98, 20.27, 14.41, 8.43, 2.82], monthlyPrecipMm: [80.79, 74.16, 104.66, 116.27, 136.10, 197.87, 223.55, 180.58, 200.07, 139.87, 100.57, 88.88], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "jordan", countryNameRaw: "Jordan", climateCode: "JOR", monthlyTempC: [9.13, 10.77, 14.19, 18.77, 23.15, 26.17, 28.31, 28.38, 26.17, 21.83, 15.57, 10.95], monthlyPrecipMm: [24.54, 22.62, 15.44, 7.04, 3.63, 0.08, 0.07, 0.01, 0.07, 4.91, 11.76, 17.32], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "mexico", countryNameRaw: "Mexico", climateCode: "MEX", monthlyTempC: [15.95, 17.41, 19.50, 22.12, 24.30, 25.79, 25.50, 25.43, 24.20, 21.85, 18.40, 16.08], monthlyPrecipMm: [20.61, 15.78, 14.94, 17.26, 43.76, 105.53, 128.22, 133.15, 145.46, 83.89, 32.77, 21.91], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "morocco", countryNameRaw: "Morocco", climateCode: "MAR", monthlyTempC: [9.91, 11.58, 14.34, 16.37, 19.75, 23.55, 26.81, 26.88, 23.18, 19.27, 14.52, 11.06], monthlyPrecipMm: [38.67, 35.27, 38.57, 27.82, 17.67, 5.46, 3.51, 7.44, 16.80, 34.33, 39.92, 46.88], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "netherlands", countryNameRaw: "Netherlands", climateCode: "NLD", monthlyTempC: [3.49, 3.76, 6.40, 9.44, 13.15, 15.84, 18.11, 18.11, 14.76, 10.85, 6.98, 4.49], monthlyPrecipMm: [69.67, 55.72, 53.58, 39.80, 54.82, 67.03, 78.61, 80.77, 71.21, 76.60, 74.07, 80.33], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "new-zealand", countryNameRaw: "New Zealand", climateCode: "NZL", monthlyTempC: [15.37, 15.60, 13.76, 11.12, 8.49, 6.03, 5.23, 6.28, 8.18, 9.99, 11.71, 14.01], monthlyPrecipMm: [113.98, 101.57, 122.14, 127.31, 143.14, 151.28, 139.02, 146.30, 146.05, 146.02, 120.37, 135.15], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "norway", countryNameRaw: "Norway", climateCode: "NOR", monthlyTempC: [-5.76, -5.80, -3.45, 0.55, 5.19, 9.29, 12.14, 11.30, 7.36, 2.32, -2.15, -4.60], monthlyPrecipMm: [106.56, 84.24, 80.28, 59.61, 64.29, 80.70, 90.99, 106.34, 107.54, 121.44, 105.11, 116.14], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "panama", countryNameRaw: "Panama", climateCode: "PAN", monthlyTempC: [25.18, 25.46, 26.17, 26.60, 26.25, 25.71, 25.92, 25.59, 25.35, 25.27, 24.88, 24.92], monthlyPrecipMm: [82.82, 50.35, 58.57, 123.51, 284.35, 251.18, 228.65, 247.67, 253.83, 356.89, 327.29, 171.62], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "paraguay", countryNameRaw: "Paraguay", climateCode: "PRY", monthlyTempC: [28.01, 27.42, 26.39, 23.91, 20.57, 19.26, 18.59, 20.83, 23.16, 25.41, 26.21, 27.37], monthlyPrecipMm: [134.40, 130.47, 108.26, 105.01, 94.63, 56.18, 41.01, 31.51, 62.52, 132.11, 137.51, 135.69], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "portugal", countryNameRaw: "Portugal", climateCode: "PRT", monthlyTempC: [9.44, 10.21, 12.47, 13.98, 16.92, 20.60, 22.85, 23.14, 20.76, 17.12, 12.68, 10.35], monthlyPrecipMm: [107.35, 84.37, 81.39, 78.31, 64.36, 24.87, 8.47, 11.73, 43.66, 122.72, 114.32, 119.60], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "qatar", countryNameRaw: "Qatar", climateCode: "QAT", monthlyTempC: [17.53, 19.13, 22.44, 27.44, 32.77, 35.37, 36.47, 36.15, 33.87, 30.29, 24.64, 19.84], monthlyPrecipMm: [15.17, 13.16, 16.34, 6.77, 1.39, 0.00, 0.00, 0.00, 0.00, 0.19, 5.21, 12.44], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "saudi-arabia", countryNameRaw: "Saudi Arabia", climateCode: "SAU", monthlyTempC: [15.31, 17.74, 21.59, 26.34, 30.86, 33.11, 34.27, 34.27, 31.73, 26.86, 21.22, 16.93], monthlyPrecipMm: [13.08, 7.27, 21.26, 18.53, 9.91, 1.13, 1.39, 2.17, 0.73, 3.64, 12.74, 10.06], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "senegal", countryNameRaw: "Senegal", climateCode: "SEN", monthlyTempC: [25.17, 27.34, 29.62, 31.40, 32.02, 31.05, 29.20, 28.69, 28.58, 29.59, 28.20, 25.73], monthlyPrecipMm: [0.22, 0.39, 0.04, 0.59, 10.53, 69.10, 144.34, 241.73, 193.96, 58.57, 2.26, 0.33], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "south-africa", countryNameRaw: "South Africa", climateCode: "ZAF", monthlyTempC: [23.66, 23.43, 21.75, 18.46, 15.02, 11.94, 11.64, 13.53, 16.64, 19.29, 20.99, 22.68], monthlyPrecipMm: [70.73, 64.45, 56.81, 32.81, 18.79, 13.55, 12.03, 14.13, 18.61, 38.41, 55.18, 67.24], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "south-korea", countryNameRaw: "Republic of Korea", climateCode: "KOR", monthlyTempC: [-1.71, 0.56, 5.63, 11.62, 16.88, 21.25, 24.47, 25.08, 20.26, 14.21, 7.19, 0.59], monthlyPrecipMm: [27.35, 38.11, 55.77, 93.19, 107.43, 165.80, 301.95, 284.11, 153.27, 64.22, 48.26, 28.60], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "spain", countryNameRaw: "Spain", climateCode: "ESP", monthlyTempC: [6.33, 7.23, 9.82, 11.90, 15.58, 19.92, 23.01, 22.97, 19.46, 14.87, 9.79, 7.10], monthlyPrecipMm: [60.57, 48.60, 58.77, 58.72, 56.18, 32.01, 18.40, 23.10, 44.19, 79.35, 72.77, 70.11], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "sweden", countryNameRaw: "Sweden", climateCode: "SWE", monthlyTempC: [-7.16, -6.73, -3.11, 2.07, 7.43, 12.15, 14.95, 13.60, 9.13, 3.41, -2.02, -5.47], monthlyPrecipMm: [47.23, 36.91, 34.14, 35.48, 45.72, 67.46, 79.66, 79.09, 59.24, 59.03, 55.83, 53.16], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "switzerland", countryNameRaw: "Switzerland", climateCode: "CHE", monthlyTempC: [-1.72, -1.23, 1.86, 5.57, 9.48, 13.22, 15.27, 14.92, 11.26, 7.33, 2.52, -0.70], monthlyPrecipMm: [77.31, 67.08, 72.03, 86.30, 124.64, 129.50, 134.81, 143.20, 112.17, 98.10, 98.26, 92.24], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "tunisia", countryNameRaw: "Tunisia", climateCode: "TUN", monthlyTempC: [11.00, 12.21, 15.17, 18.84, 22.82, 27.46, 29.78, 30.11, 26.84, 22.51, 16.63, 12.23], monthlyPrecipMm: [34.65, 27.24, 29.80, 26.35, 16.48, 6.25, 2.40, 6.96, 28.41, 35.42, 29.23, 34.11], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "turkiye", countryNameRaw: "Türkiye", climateCode: "TUR", monthlyTempC: [0.18, 1.61, 5.53, 10.33, 15.05, 19.45, 22.80, 22.94, 18.94, 13.66, 7.13, 2.18], monthlyPrecipMm: [73.65, 62.64, 66.18, 61.87, 60.11, 37.73, 16.71, 15.14, 23.37, 48.81, 59.90, 78.18], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "uruguay", countryNameRaw: "Uruguay", climateCode: "URY", monthlyTempC: [24.39, 23.60, 21.85, 18.41, 14.85, 12.46, 11.46, 13.38, 14.99, 17.63, 20.33, 22.92], monthlyPrecipMm: [115.42, 115.68, 109.87, 138.76, 112.56, 101.73, 87.49, 88.07, 100.37, 120.70, 90.47, 107.03], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "usa", countryNameRaw: "United States of America", climateCode: "USA", monthlyTempC: [-2.67, -0.77, 3.25, 8.63, 14.32, 19.12, 21.74, 20.81, 16.74, 10.07, 3.21, -1.41], monthlyPrecipMm: [56.23, 50.09, 56.39, 61.24, 69.16, 73.22, 71.59, 69.70, 64.14, 60.49, 53.79, 58.17], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  { teamId: "uzbekistan", countryNameRaw: "Uzbekistan", climateCode: "UZB", monthlyTempC: [-1.50, 0.43, 7.51, 15.19, 21.47, 26.57, 28.48, 26.57, 20.42, 13.09, 5.58, 0.13], monthlyPrecipMm: [23.82, 26.48, 35.06, 33.26, 24.14, 8.59, 3.94, 2.61, 2.62, 10.90, 23.04, 23.24], baselinePeriod: "1991-2020", dataStatus: "source-backed" },
  // --- official-derived: UK constituent FAs, Met Office / HadUK-Grid calendar-month
  // means over 1991-2020 (NOT CCKP GBR; NOT parent-mapped to the United Kingdom) ---
  { teamId: "england", countryNameRaw: "England", climateCode: "", monthlyTempC: [4.40, 4.65, 6.40, 8.65, 11.56, 14.37, 16.48, 16.29, 13.93, 10.62, 7.12, 4.72], monthlyPrecipMm: [83.04, 66.05, 58.33, 56.09, 57.18, 64.97, 66.47, 74.58, 68.49, 90.23, 92.08, 92.04], baselinePeriod: "1991-2020", dataStatus: "official-derived" },
  { teamId: "scotland", countryNameRaw: "Scotland", climateCode: "", monthlyTempC: [2.92, 3.09, 4.39, 6.52, 9.08, 11.62, 13.43, 13.23, 11.29, 8.17, 5.21, 3.06], monthlyPrecipMm: [177.89, 140.74, 124.48, 93.00, 89.18, 92.91, 103.66, 120.03, 123.34, 168.25, 165.21, 173.94], baselinePeriod: "1991-2020", dataStatus: "official-derived" },
];
