/**
 * Phase 1.19D - WC-1998 historical source-pack snapshot (32 teams, 64 matches). STRETCH.
 * GENERATED by scripts/generate-historical-1998.mjs - DO NOT EDIT BY HAND.
 *
 * ISOLATED + UNWIRED: part of the backtesting layer (`data/historical/`,
 * `lib/backtesting/`). NEVER imported by the production 2026 app; nothing is wired
 * into lib/model/*; no probabilities change; no calibration, no tournament replay.
 * Validated by lib/backtesting/validate-historical.ts.
 *
 * STRETCH EVIDENCE ONLY: WC-1998 is an ADDITIVE stretch pack. It does NOT change the
 * primary four-tournament (2010/2014/2018/2022) diagnostic headline, does NOT recompute
 * LOTO, does NOT create stretch consolidation, and does NOT approve calibration
 * (calibration remains NO-GO). Per-tournament diagnostics are NOT pooled with the
 * primary scope.
 *
 * DERIVED-ONLY: raw CSV/MD source files are NOT committed; their SHA-256 anchors live
 * in WC1998_SOURCE.
 *
 * FIRST 32-TEAM World Cup; single host France (UEFA).
 *
 * LEAKAGE: every Elo asOfDate (1998-06-09) and FIFA rankingDate (1998-05-20) is
 * strictly before the opening kickoff (1998-06-10T17:30:00+02:00 = 1998-06-10T15:30:00Z).
 * Match results are OUTCOMES ONLY and must never feed a pre-tournament feature.
 *
 * SCORE CONVENTION (mirrors 2022/2018/2014/2010/2006/2002): snapshot goalsA/goalsB store
 * the 90-MINUTE score; resultAt90 is derived from the 90' score; extra time
 * (afterExtraTime) and penalties (penalties MADE, not attempts) are recorded separately.
 * GOLDEN GOAL (1998 knockouts): stored as a 90' draw + afterExtraTime:true, no penalties
 * (the golden goal is an ET goal, never in 90' goalsA/goalsB). The evaluator targets only
 * 90-minute W/D/L. Final: Brazil 0-3 France (no ET, no penalties; teamA=Brazil,
 * teamB=France; resultAt90 "B").
 *
 * SLUGS: "Yugoslavia"/"FR Yugoslavia" -> fr-yugoslavia (HISTORICAL-ONLY, distinct from
 * modern `serbia` and from `serbia-and-montenegro`); "South Korea" -> south-korea;
 * "United States" -> usa; new clean slugs bulgaria/chile/colombia/jamaica/romania.
 */
import type { HistoricalSourcePack, BacktestProvenance } from "@/lib/backtesting/types";

/** Per-file source provenance + SHA-256 anchors (raw files NOT committed). */
export const WC1998_SOURCE: {
  label: string;
  openingKickoff: string;
  retrievedAt: string;
  files: Record<string, BacktestProvenance>;
  notes: string;
} = {
  label: "FIFA World Cup 1998 (France) historical source pack - backtesting (STRETCH)",
  openingKickoff: "1998-06-10T17:30:00+02:00",
  retrievedAt: "2026-06-22",
  files: {
    identity: {
      sourceName: "OpenFootball World Cup repository (1998--france) + FIFA 1998 page",
      sourceUrl: "https://github.com/openfootball/worldcup",
      sourceFile: "wc1998-identity.csv",
      sha256: "36f6bdfb85be90929478ae8d2e971865673a0e8df8f13eaae3697852054c32e8",
      licence: "OpenFootball CC0-1.0; FIFA page reference-only",
      retrievedAt: "2026-06-22",
      notes: "Compact 1-row identity (JSON groups, colon-style confederations) normalized; raw not committed. First 32-team WC; single host France (UEFA).",
    },
    results: {
      sourceName: "OpenFootball World Cup repository (1998--france)",
      sourceUrl: "https://github.com/openfootball/worldcup",
      sourceFile: "wc1998-results.csv",
      sha256: "050dbcfef720a680a78148ae9283202de5a0b4f9562111eb4f92a659aff2d17f",
      licence: "OpenFootball CC0-1.0",
      retrievedAt: "2026-06-22",
      notes:
        "64 matches; stage/outcome labels normalized to contract enums (resultAt90 raw tokens are teamA_win/" +
        "draw/teamB_win). Snapshot goalsA/goalsB = 90-minute score (raw goalsA/goalsB are after-ET; golden-goal " +
        "era). Final: Brazil 0-3 France.",
    },
    elo: {
      sourceName: "World Football Elo Ratings 1998 World Cup start (eloratings.net)",
      sourceUrl: "https://www.eloratings.net/1998_World_Cup_start",
      sourceFile: "wc1998-elo.csv",
      sha256: "1d0dda7bb5d1530517e5c03095843358c2f76961d740272b4e88db6d7f73235e",
      licence: "eloratings/international-football.net reference; small derived values only",
      retrievedAt: "2026-06-22",
      asOfDate: "1998-06-09",
      notes: "Pre-tournament Elo as-of 1998-06-09, strictly before the opening kickoff. No host adjustment.",
    },
    fifa: {
      sourceName: "FIFA men's ranking 1998-05-20 (en.fifaranking.net mirror)",
      sourceUrl: "https://en.fifaranking.net/ranking/index.php?d=1998-05-20",
      sourceFile: "wc1998-fifa.csv",
      sha256: "d397577c0cc2c75752a39f56ef22c3c117ce40c3032a257a2e62240dd0d94d54",
      licence: "Public ranking mirror licensing unclear / reference-grade; official values conceptually",
      retrievedAt: "2026-06-22",
      asOfDate: "1998-05-20",
      notes:
        "Last pre-tournament FIFA release (exact date 1998-05-20); no post-tournament ranking used. Rank " +
        "uniqueness is not asserted as a rule. Raw mirror not committed - SHA-256 is the anchor.",
    },
    readme: {
      sourceName: "User-supplied source notes (README_SOURCE_NOTES.md)",
      sourceFile: "README_SOURCE_NOTES.md",
      sha256: "03e45912d0712cbd163d1a5a3ca25c6951da6d5669ec9513a1e0f01f901dff12",
      licence: "n/a (documentation of source strategy + licence notes)",
      retrievedAt: "2026-06-22",
      notes: "Records source strategy, leakage rules, golden-goal/ET/penalty cases, and licence notes for the pack.",
    },
  },
  notes:
    "STRETCH backtesting pack (1998). Optional packs (macro, recent form, squads, managers, " +
    "venues/tournamentContext) are intentionally deferred. Sources: OpenFootball (CC0) is the " +
    "permissive fixtures/results route; FIFA ranking values are official conceptually but supplied via a " +
    "public mirror (treat licensing cautiously); eloratings is a small derived Elo reference, not a raw " +
    "dump. Raw source files are NOT committed; checksums are the reproducibility anchor. Stretch-only: this " +
    "does not change the primary four-tournament diagnostics, does not recompute LOTO, does not create " +
    "stretch consolidation, and does not approve calibration (calibration remains NO-GO).",
};

/** Declared per-confederation entrant counts (from the compact identity row). */
export const WC1998_CONFEDERATION_COUNTS: Record<string, number> = {
  "AFC": 4,
  "CAF": 5,
  "CONCACAF": 3,
  "CONMEBOL": 5,
  "UEFA": 15
};

/** Source team display name -> historical team id (historical id space). */
export const WC1998_NAME_TO_ID: Record<string, string> = {
  "Brazil": "brazil",
  "Norway": "norway",
  "Morocco": "morocco",
  "Scotland": "scotland",
  "Italy": "italy",
  "Chile": "chile",
  "Austria": "austria",
  "Cameroon": "cameroon",
  "France": "france",
  "Denmark": "denmark",
  "South Africa": "south-africa",
  "Saudi Arabia": "saudi-arabia",
  "Nigeria": "nigeria",
  "Paraguay": "paraguay",
  "Spain": "spain",
  "Bulgaria": "bulgaria",
  "Netherlands": "netherlands",
  "Mexico": "mexico",
  "Belgium": "belgium",
  "South Korea": "south-korea",
  "Germany": "germany",
  "Yugoslavia": "fr-yugoslavia",
  "Iran": "iran",
  "United States": "usa",
  "Romania": "romania",
  "England": "england",
  "Colombia": "colombia",
  "Tunisia": "tunisia",
  "Argentina": "argentina",
  "Croatia": "croatia",
  "Jamaica": "jamaica",
  "Japan": "japan",
  "FR Yugoslavia": "fr-yugoslavia",
  "Korea Republic": "south-korea",
  "USA": "usa"
};

export const WC1998_PACK: HistoricalSourcePack = {
  "identity": {
    "tournamentYear": 1998,
    "hostCountries": [
      "France"
    ],
    "openingKickoff": "1998-06-10T17:30:00+02:00",
    "format": "32-team-8-groups",
    "teamIds": [
      "argentina",
      "austria",
      "belgium",
      "brazil",
      "bulgaria",
      "cameroon",
      "chile",
      "colombia",
      "croatia",
      "denmark",
      "england",
      "fr-yugoslavia",
      "france",
      "germany",
      "iran",
      "italy",
      "jamaica",
      "japan",
      "mexico",
      "morocco",
      "netherlands",
      "nigeria",
      "norway",
      "paraguay",
      "romania",
      "saudi-arabia",
      "scotland",
      "south-africa",
      "south-korea",
      "spain",
      "tunisia",
      "usa"
    ],
    "confederations": {
      "argentina": "CONMEBOL",
      "austria": "UEFA",
      "belgium": "UEFA",
      "brazil": "CONMEBOL",
      "bulgaria": "UEFA",
      "cameroon": "CAF",
      "chile": "CONMEBOL",
      "colombia": "CONMEBOL",
      "croatia": "UEFA",
      "denmark": "UEFA",
      "england": "UEFA",
      "fr-yugoslavia": "UEFA",
      "france": "UEFA",
      "germany": "UEFA",
      "iran": "AFC",
      "italy": "UEFA",
      "jamaica": "CONCACAF",
      "japan": "AFC",
      "mexico": "CONCACAF",
      "morocco": "CAF",
      "netherlands": "UEFA",
      "nigeria": "CAF",
      "norway": "UEFA",
      "paraguay": "CONMEBOL",
      "romania": "UEFA",
      "saudi-arabia": "AFC",
      "scotland": "UEFA",
      "south-africa": "CAF",
      "south-korea": "AFC",
      "spain": "UEFA",
      "tunisia": "CAF",
      "usa": "CONCACAF"
    },
    "groups": {
      "A": [
        "brazil",
        "norway",
        "morocco",
        "scotland"
      ],
      "B": [
        "italy",
        "chile",
        "austria",
        "cameroon"
      ],
      "C": [
        "france",
        "denmark",
        "south-africa",
        "saudi-arabia"
      ],
      "D": [
        "nigeria",
        "paraguay",
        "spain",
        "bulgaria"
      ],
      "E": [
        "netherlands",
        "mexico",
        "belgium",
        "south-korea"
      ],
      "F": [
        "germany",
        "fr-yugoslavia",
        "iran",
        "usa"
      ],
      "G": [
        "romania",
        "england",
        "colombia",
        "tunisia"
      ],
      "H": [
        "argentina",
        "croatia",
        "jamaica",
        "japan"
      ]
    },
    "bracket": {
      "description": "Round of 16: A1-B2, C1-D2, E1-F2, G1-H2, B1-A2, D1-C2, F1-E2, H1-G2; then quarter-finals, semi-finals, third-place match, final",
      "rounds": [
        "round-of-16",
        "quarter-final",
        "semi-final",
        "third-place",
        "final"
      ]
    },
    "provenance": {
      "sourceName": "OpenFootball World Cup repository (1998--france) + FIFA 1998 page (user-supplied derived CSV)",
      "sourceUrl": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt; https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt",
      "sourceFile": "wc1998-identity.csv",
      "sha256": "36f6bdfb85be90929478ae8d2e971865673a0e8df8f13eaae3697852054c32e8",
      "licence": "OpenFootball CC0-1.0; FIFA pages reference-only; eloratings derived reference",
      "retrievedAt": "2026-06-22",
      "notes": "Compact raw identity (1 row; groups as JSON, confederations as colon-style string) normalized to teamIds[]/groups{}/confederations{}. First 32-team World Cup; single host France (UEFA). FR Yugoslavia is a historical-only slug. Aggregate counts (AFC:4; CAF:5; CONCACAF:3; CONMEBOL:5; UEFA:15) cross-checked by the validator. format text: \"32 teams; 8 groups of 4; top 2 per group advanced to knockout; Round of 16 through Final; golden-goal extra time in knockout rounds where applicable\"."
    }
  },
  "results": [
    {
      "matchId": "1998-001",
      "date": "1998-06-10",
      "stage": "group",
      "group": "A",
      "teamA": "brazil",
      "teamB": "scotland",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Stade de France",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-002",
      "date": "1998-06-10",
      "stage": "group",
      "group": "A",
      "teamA": "morocco",
      "teamB": "norway",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Stade de la Mosson",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-003",
      "date": "1998-06-16",
      "stage": "group",
      "group": "A",
      "teamA": "scotland",
      "teamB": "norway",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Parc Lescure",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-004",
      "date": "1998-06-16",
      "stage": "group",
      "group": "A",
      "teamA": "brazil",
      "teamB": "morocco",
      "goalsA": 3,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Stade de la Beaujoire",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-005",
      "date": "1998-06-23",
      "stage": "group",
      "group": "A",
      "teamA": "scotland",
      "teamB": "morocco",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Stade Geoffroy-Guichard",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-006",
      "date": "1998-06-23",
      "stage": "group",
      "group": "A",
      "teamA": "brazil",
      "teamB": "norway",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Stade Vélodrome",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-007",
      "date": "1998-06-11",
      "stage": "group",
      "group": "B",
      "teamA": "cameroon",
      "teamB": "austria",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Stade de Toulouse",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-008",
      "date": "1998-06-11",
      "stage": "group",
      "group": "B",
      "teamA": "italy",
      "teamB": "chile",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Parc Lescure",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-009",
      "date": "1998-06-17",
      "stage": "group",
      "group": "B",
      "teamA": "chile",
      "teamB": "austria",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Stade Geoffroy-Guichard",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-010",
      "date": "1998-06-17",
      "stage": "group",
      "group": "B",
      "teamA": "italy",
      "teamB": "cameroon",
      "goalsA": 3,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Stade de la Mosson",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-011",
      "date": "1998-06-23",
      "stage": "group",
      "group": "B",
      "teamA": "italy",
      "teamB": "austria",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Stade de France",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-012",
      "date": "1998-06-23",
      "stage": "group",
      "group": "B",
      "teamA": "chile",
      "teamB": "cameroon",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Stade de la Beaujoire",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-013",
      "date": "1998-06-12",
      "stage": "group",
      "group": "C",
      "teamA": "saudi-arabia",
      "teamB": "denmark",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Stade Félix Bollaert",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-014",
      "date": "1998-06-12",
      "stage": "group",
      "group": "C",
      "teamA": "france",
      "teamB": "south-africa",
      "goalsA": 3,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Stade Vélodrome",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-015",
      "date": "1998-06-18",
      "stage": "group",
      "group": "C",
      "teamA": "france",
      "teamB": "saudi-arabia",
      "goalsA": 4,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Stade de France",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-016",
      "date": "1998-06-18",
      "stage": "group",
      "group": "C",
      "teamA": "south-africa",
      "teamB": "denmark",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Stade de Toulouse",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-017",
      "date": "1998-06-24",
      "stage": "group",
      "group": "C",
      "teamA": "france",
      "teamB": "denmark",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Stade Gerland",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-018",
      "date": "1998-06-24",
      "stage": "group",
      "group": "C",
      "teamA": "south-africa",
      "teamB": "saudi-arabia",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Parc Lescure",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-019",
      "date": "1998-06-12",
      "stage": "group",
      "group": "D",
      "teamA": "paraguay",
      "teamB": "bulgaria",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Stade de la Mosson",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-020",
      "date": "1998-06-13",
      "stage": "group",
      "group": "D",
      "teamA": "spain",
      "teamB": "nigeria",
      "goalsA": 2,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Stade de la Beaujoire",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-021",
      "date": "1998-06-19",
      "stage": "group",
      "group": "D",
      "teamA": "nigeria",
      "teamB": "bulgaria",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Parc des Princes",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-022",
      "date": "1998-06-19",
      "stage": "group",
      "group": "D",
      "teamA": "spain",
      "teamB": "paraguay",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Stade Geoffroy-Guichard",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-023",
      "date": "1998-06-24",
      "stage": "group",
      "group": "D",
      "teamA": "spain",
      "teamB": "bulgaria",
      "goalsA": 6,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Stade Félix Bollaert",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-024",
      "date": "1998-06-24",
      "stage": "group",
      "group": "D",
      "teamA": "nigeria",
      "teamB": "paraguay",
      "goalsA": 1,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Stade de Toulouse",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-025",
      "date": "1998-06-13",
      "stage": "group",
      "group": "E",
      "teamA": "netherlands",
      "teamB": "belgium",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Stade de France",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-026",
      "date": "1998-06-13",
      "stage": "group",
      "group": "E",
      "teamA": "south-korea",
      "teamB": "mexico",
      "goalsA": 1,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Stade Gerland",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-027",
      "date": "1998-06-20",
      "stage": "group",
      "group": "E",
      "teamA": "netherlands",
      "teamB": "south-korea",
      "goalsA": 5,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Stade Vélodrome",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-028",
      "date": "1998-06-20",
      "stage": "group",
      "group": "E",
      "teamA": "belgium",
      "teamB": "mexico",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Parc Lescure",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-029",
      "date": "1998-06-25",
      "stage": "group",
      "group": "E",
      "teamA": "belgium",
      "teamB": "south-korea",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Parc des Princes",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-030",
      "date": "1998-06-25",
      "stage": "group",
      "group": "E",
      "teamA": "netherlands",
      "teamB": "mexico",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Stade Geoffroy-Guichard",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-031",
      "date": "1998-06-14",
      "stage": "group",
      "group": "F",
      "teamA": "fr-yugoslavia",
      "teamB": "iran",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Stade Geoffroy-Guichard",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-032",
      "date": "1998-06-15",
      "stage": "group",
      "group": "F",
      "teamA": "germany",
      "teamB": "usa",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Parc des Princes",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-033",
      "date": "1998-06-21",
      "stage": "group",
      "group": "F",
      "teamA": "germany",
      "teamB": "fr-yugoslavia",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Stade Félix Bollaert",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-034",
      "date": "1998-06-21",
      "stage": "group",
      "group": "F",
      "teamA": "usa",
      "teamB": "iran",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Stade Gerland",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-035",
      "date": "1998-06-25",
      "stage": "group",
      "group": "F",
      "teamA": "germany",
      "teamB": "iran",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Stade de la Mosson",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-036",
      "date": "1998-06-25",
      "stage": "group",
      "group": "F",
      "teamA": "usa",
      "teamB": "fr-yugoslavia",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Stade de la Beaujoire",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-037",
      "date": "1998-06-15",
      "stage": "group",
      "group": "G",
      "teamA": "romania",
      "teamB": "colombia",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Stade Gerland",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-038",
      "date": "1998-06-15",
      "stage": "group",
      "group": "G",
      "teamA": "england",
      "teamB": "tunisia",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Stade Vélodrome",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-039",
      "date": "1998-06-22",
      "stage": "group",
      "group": "G",
      "teamA": "colombia",
      "teamB": "tunisia",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Stade de la Mosson",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-040",
      "date": "1998-06-22",
      "stage": "group",
      "group": "G",
      "teamA": "romania",
      "teamB": "england",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Stade de Toulouse",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-041",
      "date": "1998-06-26",
      "stage": "group",
      "group": "G",
      "teamA": "romania",
      "teamB": "tunisia",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Stade de France",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-042",
      "date": "1998-06-26",
      "stage": "group",
      "group": "G",
      "teamA": "colombia",
      "teamB": "england",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Stade Félix Bollaert",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-043",
      "date": "1998-06-14",
      "stage": "group",
      "group": "H",
      "teamA": "jamaica",
      "teamB": "croatia",
      "goalsA": 1,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Stade Félix Bollaert",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-044",
      "date": "1998-06-14",
      "stage": "group",
      "group": "H",
      "teamA": "argentina",
      "teamB": "japan",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Stade de Toulouse",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-045",
      "date": "1998-06-20",
      "stage": "group",
      "group": "H",
      "teamA": "japan",
      "teamB": "croatia",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Stade de la Beaujoire",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-046",
      "date": "1998-06-21",
      "stage": "group",
      "group": "H",
      "teamA": "argentina",
      "teamB": "jamaica",
      "goalsA": 5,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Parc des Princes",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-047",
      "date": "1998-06-26",
      "stage": "group",
      "group": "H",
      "teamA": "japan",
      "teamB": "jamaica",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Stade Gerland",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-048",
      "date": "1998-06-26",
      "stage": "group",
      "group": "H",
      "teamA": "argentina",
      "teamB": "croatia",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Parc Lescure",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup.txt"
    },
    {
      "matchId": "1998-049",
      "date": "1998-06-27",
      "stage": "round-of-16",
      "teamA": "brazil",
      "teamB": "chile",
      "goalsA": 4,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Parc des Princes",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    },
    {
      "matchId": "1998-050",
      "date": "1998-06-27",
      "stage": "round-of-16",
      "teamA": "italy",
      "teamB": "norway",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Stade Vélodrome",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    },
    {
      "matchId": "1998-051",
      "date": "1998-06-28",
      "stage": "round-of-16",
      "teamA": "nigeria",
      "teamB": "denmark",
      "goalsA": 1,
      "goalsB": 4,
      "resultAt90": "B",
      "venue": "Stade de France",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    },
    {
      "matchId": "1998-052",
      "date": "1998-06-28",
      "stage": "round-of-16",
      "teamA": "france",
      "teamB": "paraguay",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "venue": "Stade Félix Bollaert",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    },
    {
      "matchId": "1998-053",
      "date": "1998-06-29",
      "stage": "round-of-16",
      "teamA": "germany",
      "teamB": "mexico",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Stade de la Mosson",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    },
    {
      "matchId": "1998-054",
      "date": "1998-06-29",
      "stage": "round-of-16",
      "teamA": "netherlands",
      "teamB": "fr-yugoslavia",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Stade de Toulouse",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    },
    {
      "matchId": "1998-055",
      "date": "1998-06-30",
      "stage": "round-of-16",
      "teamA": "argentina",
      "teamB": "england",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 4,
        "b": 3
      },
      "venue": "Stade Geoffroy-Guichard",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    },
    {
      "matchId": "1998-056",
      "date": "1998-06-30",
      "stage": "round-of-16",
      "teamA": "romania",
      "teamB": "croatia",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Parc Lescure",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    },
    {
      "matchId": "1998-057",
      "date": "1998-07-03",
      "stage": "quarter-final",
      "teamA": "italy",
      "teamB": "france",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 3,
        "b": 4
      },
      "venue": "Stade de France",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    },
    {
      "matchId": "1998-058",
      "date": "1998-07-03",
      "stage": "quarter-final",
      "teamA": "brazil",
      "teamB": "denmark",
      "goalsA": 3,
      "goalsB": 2,
      "resultAt90": "A",
      "venue": "Stade de la Beaujoire",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    },
    {
      "matchId": "1998-059",
      "date": "1998-07-04",
      "stage": "quarter-final",
      "teamA": "germany",
      "teamB": "croatia",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Stade Gerland",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    },
    {
      "matchId": "1998-060",
      "date": "1998-07-04",
      "stage": "quarter-final",
      "teamA": "netherlands",
      "teamB": "argentina",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Stade Vélodrome",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    },
    {
      "matchId": "1998-061",
      "date": "1998-07-07",
      "stage": "semi-final",
      "teamA": "brazil",
      "teamB": "netherlands",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 4,
        "b": 2
      },
      "venue": "Stade Vélodrome",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    },
    {
      "matchId": "1998-062",
      "date": "1998-07-08",
      "stage": "semi-final",
      "teamA": "france",
      "teamB": "croatia",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Stade de France",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    },
    {
      "matchId": "1998-063",
      "date": "1998-07-11",
      "stage": "third-place",
      "teamA": "netherlands",
      "teamB": "croatia",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Parc des Princes",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    },
    {
      "matchId": "1998-064",
      "date": "1998-07-12",
      "stage": "final",
      "teamA": "brazil",
      "teamB": "france",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Stade de France",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/1998--france/cup_finals.txt"
    }
  ],
  "elo": [
    {
      "teamId": "argentina",
      "rating": 1893,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "austria",
      "rating": 1715,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "belgium",
      "rating": 1822,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "brazil",
      "rating": 2091,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "bulgaria",
      "rating": 1805,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "cameroon",
      "rating": 1710,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "chile",
      "rating": 1788,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "colombia",
      "rating": 1778,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "croatia",
      "rating": 1874,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "denmark",
      "rating": 1891,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "england",
      "rating": 1974,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "fr-yugoslavia",
      "rating": 1968,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "france",
      "rating": 2004,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "germany",
      "rating": 2058,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "iran",
      "rating": 1655,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "italy",
      "rating": 1972,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "jamaica",
      "rating": 1645,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "japan",
      "rating": 1744,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "mexico",
      "rating": 1896,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "morocco",
      "rating": 1727,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "netherlands",
      "rating": 1962,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "nigeria",
      "rating": 1703,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "norway",
      "rating": 1903,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "paraguay",
      "rating": 1742,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "romania",
      "rating": 1880,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "saudi-arabia",
      "rating": 1645,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "scotland",
      "rating": 1777,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "south-africa",
      "rating": 1637,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "south-korea",
      "rating": 1750,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "spain",
      "rating": 2039,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "tunisia",
      "rating": 1570,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    },
    {
      "teamId": "usa",
      "rating": 1759,
      "asOfDate": "1998-06-09",
      "sourceRef": "https://www.eloratings.net/1998_World_Cup_start"
    }
  ],
  "fifa": [
    {
      "teamId": "argentina",
      "rank": 6,
      "points": 60,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "austria",
      "rank": 31,
      "points": 51,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "belgium",
      "rank": 36,
      "points": 50,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "brazil",
      "rank": 1,
      "points": 71,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "bulgaria",
      "rank": 35,
      "points": 50,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "cameroon",
      "rank": 49,
      "points": 45,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "chile",
      "rank": 9,
      "points": 58,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "colombia",
      "rank": 10,
      "points": 58,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "croatia",
      "rank": 19,
      "points": 55,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "denmark",
      "rank": 27,
      "points": 52,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "england",
      "rank": 5,
      "points": 60,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "fr-yugoslavia",
      "rank": 8,
      "points": 59,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "france",
      "rank": 18,
      "points": 56,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "germany",
      "rank": 2,
      "points": 64,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "iran",
      "rank": 42,
      "points": 47,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "italy",
      "rank": 14,
      "points": 56,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "jamaica",
      "rank": 30,
      "points": 52,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "japan",
      "rank": 12,
      "points": 57,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "mexico",
      "rank": 4,
      "points": 61,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "morocco",
      "rank": 13,
      "points": 57,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "netherlands",
      "rank": 25,
      "points": 54,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "nigeria",
      "rank": 74,
      "points": 36,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "norway",
      "rank": 7,
      "points": 59,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "paraguay",
      "rank": 29,
      "points": 52,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "romania",
      "rank": 22,
      "points": 54,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "saudi-arabia",
      "rank": 34,
      "points": 50,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "scotland",
      "rank": 41,
      "points": 48,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "south-africa",
      "rank": 24,
      "points": 54,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "south-korea",
      "rank": 20,
      "points": 55,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "spain",
      "rank": 15,
      "points": 56,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "tunisia",
      "rank": 21,
      "points": 55,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    },
    {
      "teamId": "usa",
      "rank": 11,
      "points": 58,
      "rankingDate": "1998-05-20",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=1998-05-20"
    }
  ],
  "macro": [],
  "recentForm": []
};
