/**
 * Phase 1.18B-2 - WC-2022 historical source-pack snapshot (32 teams, 64 matches).
 * GENERATED by scripts/generate-historical-2022.mjs - DO NOT EDIT BY HAND.
 *
 * ISOLATED + UNWIRED: part of the backtesting layer (`data/historical/`,
 * `lib/backtesting/`). NEVER imported by the production 2026 app; nothing is wired
 * into lib/model/*; no probabilities change; no calibration, no match-level harness,
 * no tournament replay in this phase. Validated by lib/backtesting/validate-historical.ts.
 *
 * DERIVED-ONLY: raw CSV/MD source files are NOT committed; their SHA-256 anchors live
 * in WC2022_SOURCE. Pilot to prove the source-pack contract, team mapping, leakage
 * controls, provenance/checksums, and validation flow on one clean recent tournament.
 *
 * LEAKAGE: every Elo asOfDate and FIFA rankingDate is strictly before the opening
 * kickoff (2022-11-20T19:00:00+03:00 = 2022-11-20T16:00:00Z). FIFA uses the last
 * pre-tournament release (2022-10-06), NOT the post-tournament 2022-12-22 ranking.
 * Match results are OUTCOMES ONLY and must never feed a pre-tournament feature;
 * goalsA/goalsB are the 90-minute goals (ET/penalties recorded separately).
 *
 * Qatar Elo is the unadjusted eloratings value 1680 (asOf 2022-11-09), NOT
 * ProFootballLogic's host-adjusted 1780; see WC2022_SOURCE.notes.
 */
import type { HistoricalSourcePack, BacktestProvenance } from "@/lib/backtesting/types";

/** Per-file source provenance + SHA-256 anchors (raw files NOT committed). */
export const WC2022_SOURCE: {
  label: string;
  openingKickoff: string;
  retrievedAt: string;
  files: Record<string, BacktestProvenance>;
  notes: string;
} = {
  label: "FIFA World Cup 2022 (Qatar) historical source pack - backtesting pilot",
  openingKickoff: "2022-11-20T19:00:00+03:00",
  retrievedAt: "2026-06-21",
  files: {
    identity: {
      sourceName: "OpenFootball World Cup repository + FIFA Qatar 2022 page",
      sourceUrl: "https://github.com/openfootball/worldcup",
      sourceFile: "wc2022-identity.csv",
      sha256: "1c5ea230b3877366e4cd0ee83ae7e79e68f15561c2318651b2eac36f4e969fd1",
      licence: "OpenFootball CC0-1.0 (Fjelstul alt. CC-BY-SA-4.0); FIFA page reference-only",
      retrievedAt: "2026-06-21",
      notes: "Compact 1-row identity normalized into the snapshot; raw not committed.",
    },
    results: {
      sourceName: "OpenFootball World Cup repository + FIFA Qatar 2022 page",
      sourceUrl: "https://github.com/openfootball/worldcup",
      sourceFile: "wc2022-results.csv",
      sha256: "2c3de1d9326fe5529e7fa912f99d750e5fefb6bf2cea76ca8c3c6f57ed3f9d44",
      licence: "OpenFootball CC0-1.0 (Fjelstul alt. CC-BY-SA-4.0)",
      retrievedAt: "2026-06-21",
      notes: "64 matches; stage/outcome labels normalized to contract enums; outcomes only.",
    },
    elo: {
      sourceName: "ProFootballLogic 2022 WC odds page (Elo sourced from eloratings.net)",
      sourceUrl: "https://www.eloratings.net/",
      sourceFile: "wc2022-elo.csv",
      sha256: "6599fe082c5f3a4d941ded16f87bb2a853f43625139a86ee94c28663d4e9df91",
      licence: "eloratings/ProFootballLogic reference; small derived values only",
      retrievedAt: "2026-06-21",
      asOfDate: "2022-11-19",
      notes:
        "Pre-tournament Elo as-of 2022-11-19 (Qatar 2022-11-09). Qatar = 1680 (unadjusted " +
        "eloratings), NOT ProFootballLogic's host-adjusted 1780. All dates < opening kickoff.",
    },
    fifa: {
      sourceName: "FIFA men's ranking 2022-10-06 (public CSV mirror + official FIFA context)",
      sourceUrl: "https://inside.fifa.com/fifa-world-ranking/men",
      sourceFile: "wc2022-fifa.csv",
      sha256: "36faaf7e4c77cda3890abfb9615c64d2d6cc94ff98c2e0b237d409b8cd00895e",
      licence: "Public CSV mirror licensing unclear / reference-grade; official values conceptually",
      retrievedAt: "2026-06-21",
      asOfDate: "2022-10-06",
      notes:
        "Last pre-tournament FIFA release (2022-10-06); the post-tournament 2022-12-22 ranking is " +
        "deliberately NOT used. Raw mirror not committed - SHA-256 is the anchor.",
    },
    readme: {
      sourceName: "User-supplied source notes (README_SOURCE_NOTES.md)",
      sourceFile: "README_SOURCE_NOTES.md",
      sha256: "076375c1bd66f74713a4ffec06c5615df1edf1598e949177ea5a9f204460f1c6",
      licence: "n/a (documentation of source strategy + licence notes)",
      retrievedAt: "2026-06-21",
      notes: "Records source strategy, leakage rules, and licence notes for the pilot pack.",
    },
  },
  notes:
    "Backtesting pilot pack (2022 only). Optional packs (macro, recent form, squads, managers, " +
    "venues/tournamentContext) are intentionally deferred. Sources: OpenFootball (CC0) is the " +
    "permissive fixtures/results route; Fjelstul is recommended for richer coverage but carries " +
    "CC-BY-SA obligations; FIFA ranking values are official conceptually but supplied via a public " +
    "mirror (treat licensing cautiously); ProFootballLogic/eloratings are small derived Elo " +
    "references, not raw dumps. Raw source files are NOT committed; checksums are the reproducibility anchor.",
};

/** Declared per-confederation entrant counts (from the compact identity row). */
export const WC2022_CONFEDERATION_COUNTS: Record<string, number> = {
  "AFC": 6,
  "CAF": 5,
  "CONCACAF": 4,
  "CONMEBOL": 4,
  "UEFA": 13,
  "OFC": 0
};

/** Source team display name -> historical team id (historical id space). */
export const WC2022_NAME_TO_ID: Record<string, string> = {
  "Qatar": "qatar",
  "Ecuador": "ecuador",
  "Senegal": "senegal",
  "Netherlands": "netherlands",
  "England": "england",
  "Iran": "iran",
  "United States": "usa",
  "Wales": "wales",
  "Argentina": "argentina",
  "Saudi Arabia": "saudi-arabia",
  "Mexico": "mexico",
  "Poland": "poland",
  "France": "france",
  "Australia": "australia",
  "Denmark": "denmark",
  "Tunisia": "tunisia",
  "Spain": "spain",
  "Costa Rica": "costa-rica",
  "Germany": "germany",
  "Japan": "japan",
  "Belgium": "belgium",
  "Canada": "canada",
  "Morocco": "morocco",
  "Croatia": "croatia",
  "Brazil": "brazil",
  "Serbia": "serbia",
  "Switzerland": "switzerland",
  "Cameroon": "cameroon",
  "Portugal": "portugal",
  "Ghana": "ghana",
  "Uruguay": "uruguay",
  "South Korea": "south-korea"
};

export const WC2022_PACK: HistoricalSourcePack = {
  "identity": {
    "tournamentYear": 2022,
    "hostCountries": [
      "Qatar"
    ],
    "openingKickoff": "2022-11-20T19:00:00+03:00",
    "format": "32-team-8-groups",
    "teamIds": [
      "argentina",
      "australia",
      "belgium",
      "brazil",
      "cameroon",
      "canada",
      "costa-rica",
      "croatia",
      "denmark",
      "ecuador",
      "england",
      "france",
      "germany",
      "ghana",
      "iran",
      "japan",
      "mexico",
      "morocco",
      "netherlands",
      "poland",
      "portugal",
      "qatar",
      "saudi-arabia",
      "senegal",
      "serbia",
      "south-korea",
      "spain",
      "switzerland",
      "tunisia",
      "uruguay",
      "usa",
      "wales"
    ],
    "confederations": {
      "argentina": "CONMEBOL",
      "australia": "AFC",
      "belgium": "UEFA",
      "brazil": "CONMEBOL",
      "cameroon": "CAF",
      "canada": "CONCACAF",
      "costa-rica": "CONCACAF",
      "croatia": "UEFA",
      "denmark": "UEFA",
      "ecuador": "CONMEBOL",
      "england": "UEFA",
      "france": "UEFA",
      "germany": "UEFA",
      "ghana": "CAF",
      "iran": "AFC",
      "japan": "AFC",
      "mexico": "CONCACAF",
      "morocco": "CAF",
      "netherlands": "UEFA",
      "poland": "UEFA",
      "portugal": "UEFA",
      "qatar": "AFC",
      "saudi-arabia": "AFC",
      "senegal": "CAF",
      "serbia": "UEFA",
      "south-korea": "AFC",
      "spain": "UEFA",
      "switzerland": "UEFA",
      "tunisia": "CAF",
      "uruguay": "CONMEBOL",
      "usa": "CONCACAF",
      "wales": "UEFA"
    },
    "groups": {
      "A": [
        "qatar",
        "ecuador",
        "senegal",
        "netherlands"
      ],
      "B": [
        "england",
        "iran",
        "usa",
        "wales"
      ],
      "C": [
        "argentina",
        "saudi-arabia",
        "mexico",
        "poland"
      ],
      "D": [
        "france",
        "australia",
        "denmark",
        "tunisia"
      ],
      "E": [
        "spain",
        "costa-rica",
        "germany",
        "japan"
      ],
      "F": [
        "belgium",
        "canada",
        "morocco",
        "croatia"
      ],
      "G": [
        "brazil",
        "serbia",
        "switzerland",
        "cameroon"
      ],
      "H": [
        "portugal",
        "ghana",
        "uruguay",
        "south-korea"
      ]
    },
    "bracket": {
      "description": "R16: A1-B2, C1-D2, E1-F2, G1-H2, B1-A2, D1-C2, F1-E2, H1-G2; QF; SF; third-place; final",
      "roundOf16": [
        {
          "home": "A1",
          "away": "B2"
        },
        {
          "home": "C1",
          "away": "D2"
        },
        {
          "home": "E1",
          "away": "F2"
        },
        {
          "home": "G1",
          "away": "H2"
        },
        {
          "home": "B1",
          "away": "A2"
        },
        {
          "home": "D1",
          "away": "C2"
        },
        {
          "home": "F1",
          "away": "E2"
        },
        {
          "home": "H1",
          "away": "G2"
        }
      ],
      "rounds": [
        "round-of-16",
        "quarter-final",
        "semi-final",
        "third-place",
        "final"
      ]
    },
    "provenance": {
      "sourceName": "OpenFootball World Cup repository + FIFA Qatar 2022 tournament page (user-supplied derived CSV)",
      "sourceUrl": "https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022; https://github.com/openfootball/worldcup; https://github.com/jfjelstul/worldcup",
      "sourceFile": "wc2022-identity.csv",
      "sha256": "1c5ea230b3877366e4cd0ee83ae7e79e68f15561c2318651b2eac36f4e969fd1",
      "licence": "OpenFootball CC0-1.0; Fjelstul (richer coverage) CC-BY-SA-4.0; FIFA pages reference-only",
      "retrievedAt": "2026-06-21",
      "notes": "Compact raw identity (1 row, groups/confederations as strings) normalized to teamIds[]/groups{}/confederations{}. Per-team confederation is the known 2022 FIFA membership; aggregate counts (AFC=6; CAF=5; CONCACAF=4; CONMEBOL=4; UEFA=13; OFC=0) cross-checked by the validator. format text: \"32 teams; eight groups of four; top two from each group advance to Round of 16; then quarter-finals, semi-finals, third-place match and final\"."
    }
  },
  "results": [
    {
      "matchId": "WC2022-001",
      "date": "2022-11-20",
      "stage": "group",
      "group": "A",
      "teamA": "qatar",
      "teamB": "ecuador",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Al Bayt Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-002",
      "date": "2022-11-21",
      "stage": "group",
      "group": "A",
      "teamA": "senegal",
      "teamB": "netherlands",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Al Thumama Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-003",
      "date": "2022-11-21",
      "stage": "group",
      "group": "B",
      "teamA": "england",
      "teamB": "iran",
      "goalsA": 6,
      "goalsB": 2,
      "resultAt90": "A",
      "venue": "Khalifa International Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-004",
      "date": "2022-11-21",
      "stage": "group",
      "group": "B",
      "teamA": "usa",
      "teamB": "wales",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Ahmad Bin Ali Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-005",
      "date": "2022-11-22",
      "stage": "group",
      "group": "C",
      "teamA": "argentina",
      "teamB": "saudi-arabia",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Lusail Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-006",
      "date": "2022-11-22",
      "stage": "group",
      "group": "D",
      "teamA": "denmark",
      "teamB": "tunisia",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Education City Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-007",
      "date": "2022-11-22",
      "stage": "group",
      "group": "C",
      "teamA": "mexico",
      "teamB": "poland",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Stadium 974",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-008",
      "date": "2022-11-22",
      "stage": "group",
      "group": "D",
      "teamA": "france",
      "teamB": "australia",
      "goalsA": 4,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Al Janoub Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-009",
      "date": "2022-11-23",
      "stage": "group",
      "group": "F",
      "teamA": "morocco",
      "teamB": "croatia",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Al Bayt Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-010",
      "date": "2022-11-23",
      "stage": "group",
      "group": "E",
      "teamA": "germany",
      "teamB": "japan",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Khalifa International Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-011",
      "date": "2022-11-23",
      "stage": "group",
      "group": "E",
      "teamA": "spain",
      "teamB": "costa-rica",
      "goalsA": 7,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Al Thumama Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-012",
      "date": "2022-11-23",
      "stage": "group",
      "group": "F",
      "teamA": "belgium",
      "teamB": "canada",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Ahmad Bin Ali Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-013",
      "date": "2022-11-24",
      "stage": "group",
      "group": "G",
      "teamA": "switzerland",
      "teamB": "cameroon",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Al Janoub Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-014",
      "date": "2022-11-24",
      "stage": "group",
      "group": "H",
      "teamA": "uruguay",
      "teamB": "south-korea",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Education City Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-015",
      "date": "2022-11-24",
      "stage": "group",
      "group": "H",
      "teamA": "portugal",
      "teamB": "ghana",
      "goalsA": 3,
      "goalsB": 2,
      "resultAt90": "A",
      "venue": "Stadium 974",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-016",
      "date": "2022-11-24",
      "stage": "group",
      "group": "G",
      "teamA": "brazil",
      "teamB": "serbia",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Lusail Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-017",
      "date": "2022-11-25",
      "stage": "group",
      "group": "B",
      "teamA": "wales",
      "teamB": "iran",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Ahmad Bin Ali Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-018",
      "date": "2022-11-25",
      "stage": "group",
      "group": "A",
      "teamA": "qatar",
      "teamB": "senegal",
      "goalsA": 1,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Al Thumama Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-019",
      "date": "2022-11-25",
      "stage": "group",
      "group": "A",
      "teamA": "netherlands",
      "teamB": "ecuador",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Khalifa International Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-020",
      "date": "2022-11-25",
      "stage": "group",
      "group": "B",
      "teamA": "england",
      "teamB": "usa",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Al Bayt Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-021",
      "date": "2022-11-26",
      "stage": "group",
      "group": "D",
      "teamA": "tunisia",
      "teamB": "australia",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Al Janoub Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-022",
      "date": "2022-11-26",
      "stage": "group",
      "group": "C",
      "teamA": "poland",
      "teamB": "saudi-arabia",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Education City Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-023",
      "date": "2022-11-26",
      "stage": "group",
      "group": "D",
      "teamA": "france",
      "teamB": "denmark",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Stadium 974",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-024",
      "date": "2022-11-26",
      "stage": "group",
      "group": "C",
      "teamA": "argentina",
      "teamB": "mexico",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Lusail Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-025",
      "date": "2022-11-27",
      "stage": "group",
      "group": "E",
      "teamA": "japan",
      "teamB": "costa-rica",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Ahmad Bin Ali Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-026",
      "date": "2022-11-27",
      "stage": "group",
      "group": "F",
      "teamA": "belgium",
      "teamB": "morocco",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Al Thumama Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-027",
      "date": "2022-11-27",
      "stage": "group",
      "group": "F",
      "teamA": "croatia",
      "teamB": "canada",
      "goalsA": 4,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Khalifa International Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-028",
      "date": "2022-11-27",
      "stage": "group",
      "group": "E",
      "teamA": "spain",
      "teamB": "germany",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Al Bayt Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-029",
      "date": "2022-11-28",
      "stage": "group",
      "group": "G",
      "teamA": "cameroon",
      "teamB": "serbia",
      "goalsA": 3,
      "goalsB": 3,
      "resultAt90": "D",
      "venue": "Al Janoub Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-030",
      "date": "2022-11-28",
      "stage": "group",
      "group": "H",
      "teamA": "south-korea",
      "teamB": "ghana",
      "goalsA": 2,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Education City Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-031",
      "date": "2022-11-28",
      "stage": "group",
      "group": "G",
      "teamA": "brazil",
      "teamB": "switzerland",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Stadium 974",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-032",
      "date": "2022-11-28",
      "stage": "group",
      "group": "H",
      "teamA": "portugal",
      "teamB": "uruguay",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Lusail Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-033",
      "date": "2022-11-29",
      "stage": "group",
      "group": "A",
      "teamA": "netherlands",
      "teamB": "qatar",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Al Bayt Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-034",
      "date": "2022-11-29",
      "stage": "group",
      "group": "A",
      "teamA": "ecuador",
      "teamB": "senegal",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Khalifa International Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-035",
      "date": "2022-11-29",
      "stage": "group",
      "group": "B",
      "teamA": "wales",
      "teamB": "england",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Ahmad Bin Ali Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-036",
      "date": "2022-11-29",
      "stage": "group",
      "group": "B",
      "teamA": "iran",
      "teamB": "usa",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Al Thumama Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-037",
      "date": "2022-11-30",
      "stage": "group",
      "group": "D",
      "teamA": "australia",
      "teamB": "denmark",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Al Janoub Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-038",
      "date": "2022-11-30",
      "stage": "group",
      "group": "D",
      "teamA": "tunisia",
      "teamB": "france",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Education City Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-039",
      "date": "2022-11-30",
      "stage": "group",
      "group": "C",
      "teamA": "poland",
      "teamB": "argentina",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Stadium 974",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-040",
      "date": "2022-11-30",
      "stage": "group",
      "group": "C",
      "teamA": "saudi-arabia",
      "teamB": "mexico",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Lusail Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-041",
      "date": "2022-12-01",
      "stage": "group",
      "group": "F",
      "teamA": "croatia",
      "teamB": "belgium",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Ahmad Bin Ali Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-042",
      "date": "2022-12-01",
      "stage": "group",
      "group": "F",
      "teamA": "canada",
      "teamB": "morocco",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Al Thumama Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-043",
      "date": "2022-12-01",
      "stage": "group",
      "group": "E",
      "teamA": "japan",
      "teamB": "spain",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Khalifa International Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-044",
      "date": "2022-12-01",
      "stage": "group",
      "group": "E",
      "teamA": "costa-rica",
      "teamB": "germany",
      "goalsA": 2,
      "goalsB": 4,
      "resultAt90": "B",
      "venue": "Al Bayt Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-045",
      "date": "2022-12-02",
      "stage": "group",
      "group": "H",
      "teamA": "ghana",
      "teamB": "uruguay",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Al Janoub Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-046",
      "date": "2022-12-02",
      "stage": "group",
      "group": "H",
      "teamA": "south-korea",
      "teamB": "portugal",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Education City Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-047",
      "date": "2022-12-02",
      "stage": "group",
      "group": "G",
      "teamA": "serbia",
      "teamB": "switzerland",
      "goalsA": 2,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Stadium 974",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-048",
      "date": "2022-12-02",
      "stage": "group",
      "group": "G",
      "teamA": "cameroon",
      "teamB": "brazil",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Lusail Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-049",
      "date": "2022-12-03",
      "stage": "round-of-16",
      "teamA": "netherlands",
      "teamB": "usa",
      "goalsA": 3,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Khalifa International Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-050",
      "date": "2022-12-03",
      "stage": "round-of-16",
      "teamA": "argentina",
      "teamB": "australia",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Ahmad Bin Ali Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-051",
      "date": "2022-12-04",
      "stage": "round-of-16",
      "teamA": "france",
      "teamB": "poland",
      "goalsA": 3,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Al Thumama Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-052",
      "date": "2022-12-04",
      "stage": "round-of-16",
      "teamA": "england",
      "teamB": "senegal",
      "goalsA": 3,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Al Bayt Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-053",
      "date": "2022-12-05",
      "stage": "round-of-16",
      "teamA": "japan",
      "teamB": "croatia",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 1,
        "b": 3
      },
      "venue": "Al Janoub Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-054",
      "date": "2022-12-05",
      "stage": "round-of-16",
      "teamA": "brazil",
      "teamB": "south-korea",
      "goalsA": 4,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Stadium 974",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-055",
      "date": "2022-12-06",
      "stage": "round-of-16",
      "teamA": "morocco",
      "teamB": "spain",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 3,
        "b": 0
      },
      "venue": "Education City Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-056",
      "date": "2022-12-06",
      "stage": "round-of-16",
      "teamA": "portugal",
      "teamB": "switzerland",
      "goalsA": 6,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Lusail Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-057",
      "date": "2022-12-09",
      "stage": "quarter-final",
      "teamA": "croatia",
      "teamB": "brazil",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 4,
        "b": 2
      },
      "venue": "Education City Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-058",
      "date": "2022-12-09",
      "stage": "quarter-final",
      "teamA": "netherlands",
      "teamB": "argentina",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 3,
        "b": 4
      },
      "venue": "Lusail Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-059",
      "date": "2022-12-10",
      "stage": "quarter-final",
      "teamA": "morocco",
      "teamB": "portugal",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Al Thumama Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-060",
      "date": "2022-12-10",
      "stage": "quarter-final",
      "teamA": "england",
      "teamB": "france",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Al Bayt Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-061",
      "date": "2022-12-13",
      "stage": "semi-final",
      "teamA": "argentina",
      "teamB": "croatia",
      "goalsA": 3,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Lusail Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-062",
      "date": "2022-12-14",
      "stage": "semi-final",
      "teamA": "france",
      "teamB": "morocco",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Al Bayt Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-063",
      "date": "2022-12-17",
      "stage": "third-place",
      "teamA": "croatia",
      "teamB": "morocco",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Khalifa International Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    },
    {
      "matchId": "WC2022-064",
      "date": "2022-12-18",
      "stage": "final",
      "teamA": "argentina",
      "teamB": "france",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 4,
        "b": 2
      },
      "venue": "Lusail Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://www.fifa.com/en/tournaments/mens/worldcup/qatar2022"
    }
  ],
  "elo": [
    {
      "teamId": "argentina",
      "rating": 2143,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "australia",
      "rating": 1719,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "belgium",
      "rating": 2007,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "brazil",
      "rating": 2169,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "cameroon",
      "rating": 1610,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "canada",
      "rating": 1776,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "costa-rica",
      "rating": 1743,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "croatia",
      "rating": 1927,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "denmark",
      "rating": 1971,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "ecuador",
      "rating": 1833,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "england",
      "rating": 1920,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "france",
      "rating": 2005,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "germany",
      "rating": 1963,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "ghana",
      "rating": 1567,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "iran",
      "rating": 1797,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "japan",
      "rating": 1787,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "mexico",
      "rating": 1809,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "morocco",
      "rating": 1766,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "netherlands",
      "rating": 2040,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "poland",
      "rating": 1814,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "portugal",
      "rating": 2006,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "qatar",
      "rating": 1680,
      "asOfDate": "2022-11-09",
      "sourceRef": "https://www.eloratings.net/Qatar; https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "saudi-arabia",
      "rating": 1635,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "senegal",
      "rating": 1687,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "serbia",
      "rating": 1898,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "south-korea",
      "rating": 1786,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "spain",
      "rating": 2048,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "switzerland",
      "rating": 1902,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "tunisia",
      "rating": 1707,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "uruguay",
      "rating": 1936,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "usa",
      "rating": 1798,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    },
    {
      "teamId": "wales",
      "rating": 1790,
      "asOfDate": "2022-11-19",
      "sourceRef": "https://www.profootballlogic.com/sports/soccer/?order=DESC&sort=Elo&status=o&year=2022; https://www.eloratings.net/"
    }
  ],
  "fifa": [
    {
      "teamId": "argentina",
      "rank": 3,
      "points": 1773.88,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "australia",
      "rank": 38,
      "points": 1488.72,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "belgium",
      "rank": 2,
      "points": 1816.71,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "brazil",
      "rank": 1,
      "points": 1841.3,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "cameroon",
      "rank": 43,
      "points": 1471.44,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "canada",
      "rank": 41,
      "points": 1475,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "costa-rica",
      "rank": 31,
      "points": 1503.59,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "croatia",
      "rank": 12,
      "points": 1645.64,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "denmark",
      "rank": 10,
      "points": 1666.57,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "ecuador",
      "rank": 44,
      "points": 1464.39,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "england",
      "rank": 5,
      "points": 1728.47,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "france",
      "rank": 4,
      "points": 1759.78,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "germany",
      "rank": 11,
      "points": 1650.21,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "ghana",
      "rank": 61,
      "points": 1393,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "iran",
      "rank": 20,
      "points": 1564.61,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "japan",
      "rank": 24,
      "points": 1559.54,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "mexico",
      "rank": 13,
      "points": 1644.89,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "morocco",
      "rank": 22,
      "points": 1563.5,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "netherlands",
      "rank": 8,
      "points": 1694.51,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "poland",
      "rank": 26,
      "points": 1548.59,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "portugal",
      "rank": 9,
      "points": 1676.56,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "qatar",
      "rank": 50,
      "points": 1439.89,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "saudi-arabia",
      "rank": 51,
      "points": 1437.78,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "senegal",
      "rank": 18,
      "points": 1584.38,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "serbia",
      "rank": 21,
      "points": 1563.62,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "south-korea",
      "rank": 28,
      "points": 1530.3,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "spain",
      "rank": 7,
      "points": 1715.22,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "switzerland",
      "rank": 15,
      "points": 1635.92,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "tunisia",
      "rank": 30,
      "points": 1507.54,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "uruguay",
      "rank": 14,
      "points": 1638.71,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "usa",
      "rank": 16,
      "points": 1627.48,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    },
    {
      "teamId": "wales",
      "rank": 19,
      "points": 1569.82,
      "rankingDate": "2022-10-06",
      "sourceRef": "https://raw.githubusercontent.com/sslp23/world_cup_sim/master/fifa_ranking-2022-10-06.csv; https://inside.fifa.com/fifa-world-ranking/men"
    }
  ],
  "macro": [],
  "recentForm": []
};
