/**
 * Phase 1.18B-8 - WC-2010 historical source-pack snapshot (32 teams, 64 matches).
 * GENERATED by scripts/generate-historical-2010.mjs - DO NOT EDIT BY HAND.
 *
 * ISOLATED + UNWIRED: part of the backtesting layer (`data/historical/`,
 * `lib/backtesting/`). NEVER imported by the production 2026 app; nothing is wired
 * into lib/model/*; no probabilities change; no calibration, no tournament replay.
 * Validated by lib/backtesting/validate-historical.ts.
 *
 * DERIVED-ONLY: raw CSV/MD source files are NOT committed; their SHA-256 anchors live
 * in WC2010_SOURCE. Fourth historical pack (after 2022, 2018, 2014); completes the
 * primary scope (2010, 2014, 2018, 2022). Per-tournament diagnostics are NOT pooled.
 *
 * LEAKAGE: every Elo asOfDate (2010-06-10) and FIFA rankingDate (2010-05-26) is
 * strictly before the opening kickoff (2010-06-11T16:00:00+02:00 = 2010-06-11T14:00:00Z).
 * Match results are OUTCOMES ONLY and must never feed a pre-tournament feature.
 *
 * SCORE CONVENTION (mirrors 2022/2018/2014): snapshot goalsA/goalsB store the
 * 90-MINUTE score; resultAt90 is derived from the 90' score; extra time
 * (afterExtraTime) and penalties (penalties MADE, not attempts) are recorded
 * separately. The evaluator targets only 90-minute W/D/L. Final: Netherlands 0-1
 * Spain after extra time (0-0 at 90, so goalsA=0/goalsB=0, resultAt90 "D",
 * afterExtraTime true).
 *
 * North Korea (north-korea) is DISTINCT from South Korea (south-korea); New Zealand
 * is the sole OFC entrant (OFC:1).
 */
import type { HistoricalSourcePack, BacktestProvenance } from "@/lib/backtesting/types";

/** Per-file source provenance + SHA-256 anchors (raw files NOT committed). */
export const WC2010_SOURCE: {
  label: string;
  openingKickoff: string;
  retrievedAt: string;
  files: Record<string, BacktestProvenance>;
  notes: string;
} = {
  label: "FIFA World Cup 2010 (South Africa) historical source pack - backtesting",
  openingKickoff: "2010-06-11T16:00:00+02:00",
  retrievedAt: "2026-06-21",
  files: {
    identity: {
      sourceName: "OpenFootball World Cup repository (2010--south-africa) + FIFA 2010 page",
      sourceUrl: "https://github.com/openfootball/worldcup",
      sourceFile: "wc2010-identity.csv",
      sha256: "8d3ad67b4036a70d119f6a9ccfc8369bf110bf839f93a7b2ccae9f58e8fe1d83",
      licence: "OpenFootball CC0-1.0 (Fjelstul alt. CC-BY-SA-4.0); FIFA page reference-only",
      retrievedAt: "2026-06-21",
      notes: "Compact 1-row identity (JSON groups, colon-style confederations) normalized; raw not committed.",
    },
    results: {
      sourceName: "OpenFootball World Cup repository (2010--south-africa)",
      sourceUrl: "https://github.com/openfootball/worldcup",
      sourceFile: "wc2010-results.csv",
      sha256: "5a81a98909e6a2779056702966efe805aa5bb3e671cadc7841e01ef77b1d018a",
      licence: "OpenFootball CC0-1.0 (Fjelstul alt. CC-BY-SA-4.0)",
      retrievedAt: "2026-06-21",
      notes:
        "64 matches; stage/outcome labels normalized to contract enums; outcomes only. Snapshot " +
        "goalsA/goalsB = 90-minute score (raw goalsA/goalsB are after-ET). Final: Netherlands 0-1 Spain AET.",
    },
    elo: {
      sourceName: "World Football Elo Ratings 2010 World Cup start (eloratings.net)",
      sourceUrl: "https://www.eloratings.net/2010_World_Cup_start",
      sourceFile: "wc2010-elo.csv",
      sha256: "90f6f9524f41a407c6bb8005addecde81ab223872f14f33d4dec8e40f67a640f",
      licence: "eloratings/international-football.net reference; small derived values only",
      retrievedAt: "2026-06-21",
      asOfDate: "2010-06-10",
      notes: "Pre-tournament Elo as-of 2010-06-10, strictly before the opening kickoff. No host adjustment.",
    },
    fifa: {
      sourceName: "FIFA men's ranking 2010-05-26 (en.fifaranking.net mirror)",
      sourceUrl: "https://en.fifaranking.net/ranking/index.php?d=2010-05-26",
      sourceFile: "wc2010-fifa.csv",
      sha256: "9d7d4cddbb14efc741f47347674d3d8221c391175fd2da4b97d9dff8c8593c1d",
      licence: "Public ranking mirror licensing unclear / reference-grade; official values conceptually",
      retrievedAt: "2026-06-21",
      asOfDate: "2010-05-26",
      notes:
        "Last pre-tournament FIFA release (exact date 2010-05-26); no post-tournament ranking used. Raw " +
        "mirror not committed - SHA-256 is the anchor.",
    },
    readme: {
      sourceName: "User-supplied source notes (README_SOURCE_NOTES.md)",
      sourceFile: "README_SOURCE_NOTES.md",
      sha256: "d70777bcbe9ff7da9715d643f68bfc0fb88a82300e0183351b427db611aa342a",
      licence: "n/a (documentation of source strategy + licence notes)",
      retrievedAt: "2026-06-21",
      notes: "Records source strategy, leakage rules, and licence notes for the pack.",
    },
  },
  notes:
    "Backtesting pack (2010). Optional packs (macro, recent form, squads, managers, " +
    "venues/tournamentContext) are intentionally deferred. Sources: OpenFootball (CC0) is the " +
    "permissive fixtures/results route; Fjelstul is the richer backbone but carries CC-BY-SA " +
    "obligations; FIFA ranking values are official conceptually but supplied via a public mirror " +
    "(treat licensing cautiously); eloratings is a small derived Elo reference, not a raw dump. " +
    "Raw source files are NOT committed; checksums are the reproducibility anchor.",
};

/** Declared per-confederation entrant counts (from the compact identity row). */
export const WC2010_CONFEDERATION_COUNTS: Record<string, number> = {
  "AFC": 4,
  "CAF": 6,
  "CONCACAF": 3,
  "CONMEBOL": 5,
  "UEFA": 13,
  "OFC": 1
};

/** Source team display name -> historical team id (historical id space). */
export const WC2010_NAME_TO_ID: Record<string, string> = {
  "South Africa": "south-africa",
  "Mexico": "mexico",
  "Uruguay": "uruguay",
  "France": "france",
  "Argentina": "argentina",
  "Nigeria": "nigeria",
  "South Korea": "south-korea",
  "Greece": "greece",
  "England": "england",
  "USA": "usa",
  "Algeria": "algeria",
  "Slovenia": "slovenia",
  "Germany": "germany",
  "Australia": "australia",
  "Serbia": "serbia",
  "Ghana": "ghana",
  "Netherlands": "netherlands",
  "Denmark": "denmark",
  "Japan": "japan",
  "Cameroon": "cameroon",
  "Italy": "italy",
  "Paraguay": "paraguay",
  "New Zealand": "new-zealand",
  "Slovakia": "slovakia",
  "Brazil": "brazil",
  "North Korea": "north-korea",
  "Côte d'Ivoire": "ivory-coast",
  "Portugal": "portugal",
  "Spain": "spain",
  "Switzerland": "switzerland",
  "Honduras": "honduras",
  "Chile": "chile",
  "Ivory Coast": "ivory-coast",
  "United States": "usa",
  "Korea Republic": "south-korea",
  "Korea DPR": "north-korea",
  "DPR Korea": "north-korea",
  "Holland": "netherlands"
};

export const WC2010_PACK: HistoricalSourcePack = {
  "identity": {
    "tournamentYear": 2010,
    "hostCountries": [
      "South Africa"
    ],
    "openingKickoff": "2010-06-11T16:00:00+02:00",
    "format": "32-team-8-groups",
    "teamIds": [
      "algeria",
      "argentina",
      "australia",
      "brazil",
      "cameroon",
      "chile",
      "denmark",
      "england",
      "france",
      "germany",
      "ghana",
      "greece",
      "honduras",
      "italy",
      "ivory-coast",
      "japan",
      "mexico",
      "netherlands",
      "new-zealand",
      "nigeria",
      "north-korea",
      "paraguay",
      "portugal",
      "serbia",
      "slovakia",
      "slovenia",
      "south-africa",
      "south-korea",
      "spain",
      "switzerland",
      "uruguay",
      "usa"
    ],
    "confederations": {
      "algeria": "CAF",
      "argentina": "CONMEBOL",
      "australia": "AFC",
      "brazil": "CONMEBOL",
      "cameroon": "CAF",
      "chile": "CONMEBOL",
      "denmark": "UEFA",
      "england": "UEFA",
      "france": "UEFA",
      "germany": "UEFA",
      "ghana": "CAF",
      "greece": "UEFA",
      "honduras": "CONCACAF",
      "italy": "UEFA",
      "ivory-coast": "CAF",
      "japan": "AFC",
      "mexico": "CONCACAF",
      "netherlands": "UEFA",
      "new-zealand": "OFC",
      "nigeria": "CAF",
      "north-korea": "AFC",
      "paraguay": "CONMEBOL",
      "portugal": "UEFA",
      "serbia": "UEFA",
      "slovakia": "UEFA",
      "slovenia": "UEFA",
      "south-africa": "CAF",
      "south-korea": "AFC",
      "spain": "UEFA",
      "switzerland": "UEFA",
      "uruguay": "CONMEBOL",
      "usa": "CONCACAF"
    },
    "groups": {
      "A": [
        "south-africa",
        "mexico",
        "uruguay",
        "france"
      ],
      "B": [
        "argentina",
        "nigeria",
        "south-korea",
        "greece"
      ],
      "C": [
        "england",
        "usa",
        "algeria",
        "slovenia"
      ],
      "D": [
        "germany",
        "australia",
        "serbia",
        "ghana"
      ],
      "E": [
        "netherlands",
        "denmark",
        "japan",
        "cameroon"
      ],
      "F": [
        "italy",
        "paraguay",
        "new-zealand",
        "slovakia"
      ],
      "G": [
        "brazil",
        "north-korea",
        "ivory-coast",
        "portugal"
      ],
      "H": [
        "spain",
        "switzerland",
        "honduras",
        "chile"
      ]
    },
    "bracket": {
      "description": "Round of 16: M49 1A-2B, M50 1C-2D, M51 1D-2C, M52 1B-2A, M53 1E-2F, M54 1G-2H, M55 1F-2E, M56 1H-2G; Quarter-finals: M57 W53-W54, M58 W49-W50, M59 W52-W51, M60 W55-W56; Semi-finals: M61 W57-W58, M62 W59-W60; Third-place match: L61-L62; Final: W61-W62.",
      "rounds": [
        "round-of-16",
        "quarter-final",
        "semi-final",
        "third-place",
        "final"
      ]
    },
    "provenance": {
      "sourceName": "OpenFootball World Cup repository (2010--south-africa) + FIFA 2010 page (user-supplied derived CSV)",
      "sourceUrl": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt ; https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt",
      "sourceFile": "wc2010-identity.csv",
      "sha256": "8d3ad67b4036a70d119f6a9ccfc8369bf110bf839f93a7b2ccae9f58e8fe1d83",
      "licence": "OpenFootball CC0-1.0; Fjelstul (richer coverage) CC-BY-SA-4.0; FIFA pages reference-only",
      "retrievedAt": "2026-06-21",
      "notes": "Compact raw identity (1 row; groups as JSON, confederations as colon-style string) normalized to teamIds[]/groups{}/confederations{}. Per-team confederation is the known 2010 FIFA membership; aggregate counts (AFC:4; CAF:6; CONCACAF:3; CONMEBOL:5; UEFA:13; OFC:1) cross-checked by the validator. format text: \"32 teams; 8 groups of 4; top 2 per group advanced to knockout; Round of 16 through Final\"."
    }
  },
  "results": [
    {
      "matchId": "wc2010-01",
      "date": "2010-06-11",
      "stage": "group",
      "group": "A",
      "teamA": "south-africa",
      "teamB": "mexico",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Soccer City",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-02",
      "date": "2010-06-11",
      "stage": "group",
      "group": "A",
      "teamA": "uruguay",
      "teamB": "france",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Cape Town Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-03",
      "date": "2010-06-16",
      "stage": "group",
      "group": "A",
      "teamA": "south-africa",
      "teamB": "uruguay",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Loftus Versfeld Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-04",
      "date": "2010-06-17",
      "stage": "group",
      "group": "A",
      "teamA": "france",
      "teamB": "mexico",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Peter Mokaba Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-05",
      "date": "2010-06-22",
      "stage": "group",
      "group": "A",
      "teamA": "mexico",
      "teamB": "uruguay",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Royal Bafokeng Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-06",
      "date": "2010-06-22",
      "stage": "group",
      "group": "A",
      "teamA": "france",
      "teamB": "south-africa",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Free State Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-07",
      "date": "2010-06-12",
      "stage": "group",
      "group": "B",
      "teamA": "south-korea",
      "teamB": "greece",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Nelson Mandela Bay Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-08",
      "date": "2010-06-12",
      "stage": "group",
      "group": "B",
      "teamA": "argentina",
      "teamB": "nigeria",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Ellis Park Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-09",
      "date": "2010-06-17",
      "stage": "group",
      "group": "B",
      "teamA": "argentina",
      "teamB": "south-korea",
      "goalsA": 4,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Soccer City",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-10",
      "date": "2010-06-17",
      "stage": "group",
      "group": "B",
      "teamA": "greece",
      "teamB": "nigeria",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Free State Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-11",
      "date": "2010-06-22",
      "stage": "group",
      "group": "B",
      "teamA": "nigeria",
      "teamB": "south-korea",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Moses Mabhida Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-12",
      "date": "2010-06-22",
      "stage": "group",
      "group": "B",
      "teamA": "greece",
      "teamB": "argentina",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Peter Mokaba Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-13",
      "date": "2010-06-12",
      "stage": "group",
      "group": "C",
      "teamA": "england",
      "teamB": "usa",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Royal Bafokeng Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-14",
      "date": "2010-06-13",
      "stage": "group",
      "group": "C",
      "teamA": "algeria",
      "teamB": "slovenia",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Peter Mokaba Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-15",
      "date": "2010-06-18",
      "stage": "group",
      "group": "C",
      "teamA": "slovenia",
      "teamB": "usa",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Ellis Park Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-16",
      "date": "2010-06-18",
      "stage": "group",
      "group": "C",
      "teamA": "england",
      "teamB": "algeria",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Cape Town Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-17",
      "date": "2010-06-23",
      "stage": "group",
      "group": "C",
      "teamA": "usa",
      "teamB": "algeria",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Loftus Versfeld Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-18",
      "date": "2010-06-23",
      "stage": "group",
      "group": "C",
      "teamA": "slovenia",
      "teamB": "england",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Nelson Mandela Bay Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-19",
      "date": "2010-06-13",
      "stage": "group",
      "group": "D",
      "teamA": "serbia",
      "teamB": "ghana",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Loftus Versfeld Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-20",
      "date": "2010-06-13",
      "stage": "group",
      "group": "D",
      "teamA": "germany",
      "teamB": "australia",
      "goalsA": 4,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Moses Mabhida Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-21",
      "date": "2010-06-18",
      "stage": "group",
      "group": "D",
      "teamA": "germany",
      "teamB": "serbia",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Nelson Mandela Bay Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-22",
      "date": "2010-06-19",
      "stage": "group",
      "group": "D",
      "teamA": "ghana",
      "teamB": "australia",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Royal Bafokeng Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-23",
      "date": "2010-06-23",
      "stage": "group",
      "group": "D",
      "teamA": "australia",
      "teamB": "serbia",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Mbombela Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-24",
      "date": "2010-06-23",
      "stage": "group",
      "group": "D",
      "teamA": "ghana",
      "teamB": "germany",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Soccer City",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-25",
      "date": "2010-06-14",
      "stage": "group",
      "group": "E",
      "teamA": "netherlands",
      "teamB": "denmark",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Soccer City",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-26",
      "date": "2010-06-14",
      "stage": "group",
      "group": "E",
      "teamA": "japan",
      "teamB": "cameroon",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Free State Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-27",
      "date": "2010-06-19",
      "stage": "group",
      "group": "E",
      "teamA": "netherlands",
      "teamB": "japan",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Moses Mabhida Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-28",
      "date": "2010-06-19",
      "stage": "group",
      "group": "E",
      "teamA": "cameroon",
      "teamB": "denmark",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Loftus Versfeld Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-29",
      "date": "2010-06-24",
      "stage": "group",
      "group": "E",
      "teamA": "denmark",
      "teamB": "japan",
      "goalsA": 1,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Royal Bafokeng Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-30",
      "date": "2010-06-24",
      "stage": "group",
      "group": "E",
      "teamA": "cameroon",
      "teamB": "netherlands",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Cape Town Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-31",
      "date": "2010-06-14",
      "stage": "group",
      "group": "F",
      "teamA": "italy",
      "teamB": "paraguay",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Cape Town Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-32",
      "date": "2010-06-15",
      "stage": "group",
      "group": "F",
      "teamA": "new-zealand",
      "teamB": "slovakia",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Royal Bafokeng Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-33",
      "date": "2010-06-20",
      "stage": "group",
      "group": "F",
      "teamA": "slovakia",
      "teamB": "paraguay",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Free State Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-34",
      "date": "2010-06-20",
      "stage": "group",
      "group": "F",
      "teamA": "italy",
      "teamB": "new-zealand",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Mbombela Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-35",
      "date": "2010-06-24",
      "stage": "group",
      "group": "F",
      "teamA": "slovakia",
      "teamB": "italy",
      "goalsA": 3,
      "goalsB": 2,
      "resultAt90": "A",
      "venue": "Ellis Park Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-36",
      "date": "2010-06-24",
      "stage": "group",
      "group": "F",
      "teamA": "paraguay",
      "teamB": "new-zealand",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Peter Mokaba Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-37",
      "date": "2010-06-15",
      "stage": "group",
      "group": "G",
      "teamA": "ivory-coast",
      "teamB": "portugal",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Nelson Mandela Bay Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-38",
      "date": "2010-06-15",
      "stage": "group",
      "group": "G",
      "teamA": "brazil",
      "teamB": "north-korea",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Ellis Park Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-39",
      "date": "2010-06-20",
      "stage": "group",
      "group": "G",
      "teamA": "brazil",
      "teamB": "ivory-coast",
      "goalsA": 3,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Soccer City",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-40",
      "date": "2010-06-21",
      "stage": "group",
      "group": "G",
      "teamA": "portugal",
      "teamB": "north-korea",
      "goalsA": 7,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Cape Town Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-41",
      "date": "2010-06-25",
      "stage": "group",
      "group": "G",
      "teamA": "portugal",
      "teamB": "brazil",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Moses Mabhida Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-42",
      "date": "2010-06-25",
      "stage": "group",
      "group": "G",
      "teamA": "north-korea",
      "teamB": "ivory-coast",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Mbombela Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-43",
      "date": "2010-06-16",
      "stage": "group",
      "group": "H",
      "teamA": "honduras",
      "teamB": "chile",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Mbombela Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-44",
      "date": "2010-06-16",
      "stage": "group",
      "group": "H",
      "teamA": "spain",
      "teamB": "switzerland",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Moses Mabhida Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-45",
      "date": "2010-06-21",
      "stage": "group",
      "group": "H",
      "teamA": "chile",
      "teamB": "switzerland",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Nelson Mandela Bay Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-46",
      "date": "2010-06-21",
      "stage": "group",
      "group": "H",
      "teamA": "spain",
      "teamB": "honduras",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Ellis Park Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-47",
      "date": "2010-06-25",
      "stage": "group",
      "group": "H",
      "teamA": "chile",
      "teamB": "spain",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Loftus Versfeld Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-48",
      "date": "2010-06-25",
      "stage": "group",
      "group": "H",
      "teamA": "switzerland",
      "teamB": "honduras",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Free State Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup.txt"
    },
    {
      "matchId": "wc2010-49",
      "date": "2010-06-26",
      "stage": "round-of-16",
      "teamA": "uruguay",
      "teamB": "south-korea",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Nelson Mandela Bay Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    },
    {
      "matchId": "wc2010-50",
      "date": "2010-06-26",
      "stage": "round-of-16",
      "teamA": "usa",
      "teamB": "ghana",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "venue": "Royal Bafokeng Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    },
    {
      "matchId": "wc2010-51",
      "date": "2010-06-27",
      "stage": "round-of-16",
      "teamA": "germany",
      "teamB": "england",
      "goalsA": 4,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Free State Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    },
    {
      "matchId": "wc2010-52",
      "date": "2010-06-27",
      "stage": "round-of-16",
      "teamA": "argentina",
      "teamB": "mexico",
      "goalsA": 3,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Soccer City",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    },
    {
      "matchId": "wc2010-53",
      "date": "2010-06-28",
      "stage": "round-of-16",
      "teamA": "netherlands",
      "teamB": "slovakia",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Moses Mabhida Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    },
    {
      "matchId": "wc2010-54",
      "date": "2010-06-28",
      "stage": "round-of-16",
      "teamA": "brazil",
      "teamB": "chile",
      "goalsA": 3,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Ellis Park Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    },
    {
      "matchId": "wc2010-55",
      "date": "2010-06-29",
      "stage": "round-of-16",
      "teamA": "paraguay",
      "teamB": "japan",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 5,
        "b": 3
      },
      "venue": "Loftus Versfeld Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    },
    {
      "matchId": "wc2010-56",
      "date": "2010-06-29",
      "stage": "round-of-16",
      "teamA": "spain",
      "teamB": "portugal",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Cape Town Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    },
    {
      "matchId": "wc2010-57",
      "date": "2010-07-02",
      "stage": "quarter-final",
      "teamA": "netherlands",
      "teamB": "brazil",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Nelson Mandela Bay Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    },
    {
      "matchId": "wc2010-58",
      "date": "2010-07-02",
      "stage": "quarter-final",
      "teamA": "uruguay",
      "teamB": "ghana",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 4,
        "b": 2
      },
      "venue": "Soccer City",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    },
    {
      "matchId": "wc2010-59",
      "date": "2010-07-03",
      "stage": "quarter-final",
      "teamA": "argentina",
      "teamB": "germany",
      "goalsA": 0,
      "goalsB": 4,
      "resultAt90": "B",
      "venue": "Cape Town Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    },
    {
      "matchId": "wc2010-60",
      "date": "2010-07-03",
      "stage": "quarter-final",
      "teamA": "paraguay",
      "teamB": "spain",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Ellis Park Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    },
    {
      "matchId": "wc2010-61",
      "date": "2010-07-06",
      "stage": "semi-final",
      "teamA": "uruguay",
      "teamB": "netherlands",
      "goalsA": 2,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Cape Town Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    },
    {
      "matchId": "wc2010-62",
      "date": "2010-07-07",
      "stage": "semi-final",
      "teamA": "germany",
      "teamB": "spain",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Moses Mabhida Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    },
    {
      "matchId": "wc2010-63",
      "date": "2010-07-10",
      "stage": "third-place",
      "teamA": "uruguay",
      "teamB": "germany",
      "goalsA": 2,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Nelson Mandela Bay Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    },
    {
      "matchId": "wc2010-64",
      "date": "2010-07-11",
      "stage": "final",
      "teamA": "netherlands",
      "teamB": "spain",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "venue": "Soccer City",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2010--south-africa/cup_finals.txt"
    }
  ],
  "elo": [
    {
      "teamId": "algeria",
      "rating": 1669,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "argentina",
      "rating": 1920,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "australia",
      "rating": 1757,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "brazil",
      "rating": 2109,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "cameroon",
      "rating": 1690,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "chile",
      "rating": 1886,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "denmark",
      "rating": 1840,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "england",
      "rating": 2001,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "france",
      "rating": 1857,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "germany",
      "rating": 1958,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "ghana",
      "rating": 1711,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "greece",
      "rating": 1809,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "honduras",
      "rating": 1644,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "italy",
      "rating": 1937,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "ivory-coast",
      "rating": 1763,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "japan",
      "rating": 1692,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "mexico",
      "rating": 1898,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "netherlands",
      "rating": 2044,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "new-zealand",
      "rating": 1501,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "nigeria",
      "rating": 1701,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "north-korea",
      "rating": 1465,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "paraguay",
      "rating": 1836,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "portugal",
      "rating": 1876,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "serbia",
      "rating": 1855,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "slovakia",
      "rating": 1741,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "slovenia",
      "rating": 1708,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "south-africa",
      "rating": 1578,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "south-korea",
      "rating": 1745,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "spain",
      "rating": 2112,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "switzerland",
      "rating": 1786,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "uruguay",
      "rating": 1844,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    },
    {
      "teamId": "usa",
      "rating": 1812,
      "asOfDate": "2010-06-10",
      "sourceRef": "https://www.eloratings.net/2010_World_Cup_start"
    }
  ],
  "fifa": [
    {
      "teamId": "algeria",
      "rank": 30,
      "points": 821,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "argentina",
      "rank": 7,
      "points": 1076,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "australia",
      "rank": 20,
      "points": 886,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "brazil",
      "rank": 1,
      "points": 1611,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "cameroon",
      "rank": 19,
      "points": 887,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "chile",
      "rank": 18,
      "points": 888,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "denmark",
      "rank": 36,
      "points": 767,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "england",
      "rank": 8,
      "points": 1068,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "france",
      "rank": 9,
      "points": 1044,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "germany",
      "rank": 6,
      "points": 1082,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "ghana",
      "rank": 32,
      "points": 800,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "greece",
      "rank": 13,
      "points": 964,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "honduras",
      "rank": 38,
      "points": 734,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "italy",
      "rank": 5,
      "points": 1184,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "ivory-coast",
      "rank": 27,
      "points": 856,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "japan",
      "rank": 45,
      "points": 682,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "mexico",
      "rank": 17,
      "points": 895,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "netherlands",
      "rank": 4,
      "points": 1231,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "new-zealand",
      "rank": 78,
      "points": 410,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "nigeria",
      "rank": 21,
      "points": 883,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "north-korea",
      "rank": 105,
      "points": 285,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "paraguay",
      "rank": 31,
      "points": 820,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "portugal",
      "rank": 3,
      "points": 1249,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "serbia",
      "rank": 15,
      "points": 947,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "slovakia",
      "rank": 34,
      "points": 777,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "slovenia",
      "rank": 25,
      "points": 860,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "south-africa",
      "rank": 83,
      "points": 392,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "south-korea",
      "rank": 47,
      "points": 632,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "spain",
      "rank": 2,
      "points": 1565,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "switzerland",
      "rank": 24,
      "points": 866,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "uruguay",
      "rank": 16,
      "points": 899,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    },
    {
      "teamId": "usa",
      "rank": 14,
      "points": 957,
      "rankingDate": "2010-05-26",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2010-05-26"
    }
  ],
  "macro": [],
  "recentForm": []
};
