/**
 * Phase 1.19C - WC-2002 historical source-pack snapshot (32 teams, 64 matches). STRETCH.
 * GENERATED by scripts/generate-historical-2002.mjs - DO NOT EDIT BY HAND.
 *
 * ISOLATED + UNWIRED: part of the backtesting layer (`data/historical/`,
 * `lib/backtesting/`). NEVER imported by the production 2026 app; nothing is wired
 * into lib/model/*; no probabilities change; no calibration, no tournament replay.
 * Validated by lib/backtesting/validate-historical.ts.
 *
 * STRETCH EVIDENCE ONLY: WC-2002 is an ADDITIVE stretch pack. It does NOT change the
 * primary four-tournament (2010/2014/2018/2022) diagnostic headline, does NOT recompute
 * LOTO, does NOT create stretch consolidation, and does NOT approve calibration
 * (calibration remains NO-GO). Per-tournament diagnostics are NOT pooled with the
 * primary scope.
 *
 * DERIVED-ONLY: raw CSV/MD source files are NOT committed; their SHA-256 anchors live
 * in WC2002_SOURCE.
 *
 * CO-HOSTS: South Korea + Japan (both AFC). hostCountries = ["South Korea","Japan"].
 *
 * LEAKAGE: every Elo asOfDate (2002-05-30) and FIFA rankingDate (2002-05-15) is
 * strictly before the opening kickoff (2002-05-31T20:30:00+09:00 = 2002-05-31T11:30:00Z).
 * Match results are OUTCOMES ONLY and must never feed a pre-tournament feature.
 *
 * SCORE CONVENTION (mirrors 2022/2018/2014/2010/2006): snapshot goalsA/goalsB store the
 * 90-MINUTE score; resultAt90 is derived from the 90' score; extra time
 * (afterExtraTime) and penalties (penalties MADE, not attempts) are recorded separately.
 * GOLDEN GOAL (2002 knockouts): stored as a 90' draw + afterExtraTime:true, no penalties
 * (the golden goal is an ET goal, never in 90' goalsA/goalsB). The evaluator targets only
 * 90-minute W/D/L. Final: Germany 0-2 Brazil (no ET, no penalties; resultAt90 "B").
 *
 * SLUGS: "Republic of Ireland" -> republic-of-ireland (HISTORICAL-ONLY, distinct from
 * Northern Ireland); "China PR"/"China" -> china (new clean slug); "Turkey" -> turkiye
 * (REUSE canonical slug); "South Korea" -> south-korea; "United States" -> usa.
 */
import type { HistoricalSourcePack, BacktestProvenance } from "@/lib/backtesting/types";

/** Per-file source provenance + SHA-256 anchors (raw files NOT committed). */
export const WC2002_SOURCE: {
  label: string;
  openingKickoff: string;
  retrievedAt: string;
  files: Record<string, BacktestProvenance>;
  notes: string;
} = {
  label: "FIFA World Cup 2002 (South Korea / Japan) historical source pack - backtesting (STRETCH)",
  openingKickoff: "2002-05-31T20:30:00+09:00",
  retrievedAt: "2026-06-22",
  files: {
    identity: {
      sourceName: "OpenFootball World Cup repository (2002--south-korea-n-japan) + FIFA 2002 page",
      sourceUrl: "https://github.com/openfootball/worldcup",
      sourceFile: "wc2002-identity.csv",
      sha256: "ffbee796765f082af7551833ab5b95f5c4f7b6dafb13acab7ec7586f340aca7c",
      licence: "OpenFootball CC0-1.0; FIFA page reference-only",
      retrievedAt: "2026-06-22",
      notes: "Compact 1-row identity (JSON groups, colon-style confederations) normalized; raw not committed. Co-hosts South Korea + Japan (both AFC).",
    },
    results: {
      sourceName: "OpenFootball World Cup repository (2002--south-korea-n-japan)",
      sourceUrl: "https://github.com/openfootball/worldcup",
      sourceFile: "wc2002-results.csv",
      sha256: "40105e2a8ee5a4cf9b46087848117f519da76d8a091fcc566ce9d6c83bc9318a",
      licence: "OpenFootball CC0-1.0",
      retrievedAt: "2026-06-22",
      notes:
        "64 matches; stage/outcome labels normalized to contract enums; outcomes only. Snapshot " +
        "goalsA/goalsB = 90-minute score (raw goalsA/goalsB are after-ET; golden-goal era). Final: Germany 0-2 Brazil.",
    },
    elo: {
      sourceName: "World Football Elo Ratings 2002 World Cup start (eloratings.net)",
      sourceUrl: "https://www.eloratings.net/2002_World_Cup_start",
      sourceFile: "wc2002-elo.csv",
      sha256: "b9531fb353c7673231ad43aa768369c4396f1d593c8647a2b5d033f219ca70e0",
      licence: "eloratings/international-football.net reference; small derived values only",
      retrievedAt: "2026-06-22",
      asOfDate: "2002-05-30",
      notes: "Pre-tournament Elo as-of 2002-05-30, strictly before the opening kickoff. No host adjustment.",
    },
    fifa: {
      sourceName: "FIFA men's ranking 2002-05-15 (en.fifaranking.net mirror)",
      sourceUrl: "https://en.fifaranking.net/ranking/?d=2002-05-15",
      sourceFile: "wc2002-fifa.csv",
      sha256: "235cc03f4a5e1246e90933e87d461ab9a5267bb41ee5fca57d43bb5eb1f8a4e0",
      licence: "Public ranking mirror licensing unclear / reference-grade; official values conceptually",
      retrievedAt: "2026-06-22",
      asOfDate: "2002-05-15",
      notes:
        "Last pre-tournament FIFA release (exact date 2002-05-15); no post-tournament ranking used. Ranks may " +
        "contain ties (uniqueness not asserted). Raw mirror not committed - SHA-256 is the anchor.",
    },
    readme: {
      sourceName: "User-supplied source notes (README_SOURCE_NOTES.md)",
      sourceFile: "README_SOURCE_NOTES.md",
      sha256: "3f94d053fae18eefbcc8eeb239b7d228b8ae074c483186a753a010e718b4d878",
      licence: "n/a (documentation of source strategy + licence notes)",
      retrievedAt: "2026-06-22",
      notes: "Records source strategy, leakage rules, golden-goal/ET/penalty cases, and licence notes for the pack.",
    },
  },
  notes:
    "STRETCH backtesting pack (2002). Optional packs (macro, recent form, squads, managers, " +
    "venues/tournamentContext) are intentionally deferred. Sources: OpenFootball (CC0) is the " +
    "permissive fixtures/results route; FIFA ranking values are official conceptually but supplied via a " +
    "public mirror (treat licensing cautiously); eloratings is a small derived Elo reference, not a raw " +
    "dump. Raw source files are NOT committed; checksums are the reproducibility anchor. Stretch-only: this " +
    "does not change the primary four-tournament diagnostics, does not recompute LOTO, does not create " +
    "stretch consolidation, and does not approve calibration (calibration remains NO-GO).",
};

/** Declared per-confederation entrant counts (from the compact identity row). */
export const WC2002_CONFEDERATION_COUNTS: Record<string, number> = {
  "AFC": 4,
  "CAF": 5,
  "CONCACAF": 3,
  "CONMEBOL": 5,
  "UEFA": 15
};

/** Source team display name -> historical team id (historical id space). */
export const WC2002_NAME_TO_ID: Record<string, string> = {
  "France": "france",
  "Senegal": "senegal",
  "Uruguay": "uruguay",
  "Denmark": "denmark",
  "Spain": "spain",
  "Slovenia": "slovenia",
  "Paraguay": "paraguay",
  "South Africa": "south-africa",
  "Brazil": "brazil",
  "Turkey": "turkiye",
  "China PR": "china",
  "Costa Rica": "costa-rica",
  "South Korea": "south-korea",
  "Poland": "poland",
  "United States": "usa",
  "Portugal": "portugal",
  "Germany": "germany",
  "Saudi Arabia": "saudi-arabia",
  "Republic of Ireland": "republic-of-ireland",
  "Cameroon": "cameroon",
  "Argentina": "argentina",
  "Nigeria": "nigeria",
  "England": "england",
  "Sweden": "sweden",
  "Italy": "italy",
  "Ecuador": "ecuador",
  "Croatia": "croatia",
  "Mexico": "mexico",
  "Japan": "japan",
  "Belgium": "belgium",
  "Russia": "russia",
  "Tunisia": "tunisia",
  "China": "china",
  "Korea Republic": "south-korea",
  "USA": "usa",
  "Türkiye": "turkiye",
  "Ireland": "republic-of-ireland"
};

export const WC2002_PACK: HistoricalSourcePack = {
  "identity": {
    "tournamentYear": 2002,
    "hostCountries": [
      "South Korea",
      "Japan"
    ],
    "openingKickoff": "2002-05-31T20:30:00+09:00",
    "format": "32-team-8-groups",
    "teamIds": [
      "argentina",
      "belgium",
      "brazil",
      "cameroon",
      "china",
      "costa-rica",
      "croatia",
      "denmark",
      "ecuador",
      "england",
      "france",
      "germany",
      "italy",
      "japan",
      "mexico",
      "nigeria",
      "paraguay",
      "poland",
      "portugal",
      "republic-of-ireland",
      "russia",
      "saudi-arabia",
      "senegal",
      "slovenia",
      "south-africa",
      "south-korea",
      "spain",
      "sweden",
      "tunisia",
      "turkiye",
      "uruguay",
      "usa"
    ],
    "confederations": {
      "argentina": "CONMEBOL",
      "belgium": "UEFA",
      "brazil": "CONMEBOL",
      "cameroon": "CAF",
      "china": "AFC",
      "costa-rica": "CONCACAF",
      "croatia": "UEFA",
      "denmark": "UEFA",
      "ecuador": "CONMEBOL",
      "england": "UEFA",
      "france": "UEFA",
      "germany": "UEFA",
      "italy": "UEFA",
      "japan": "AFC",
      "mexico": "CONCACAF",
      "nigeria": "CAF",
      "paraguay": "CONMEBOL",
      "poland": "UEFA",
      "portugal": "UEFA",
      "republic-of-ireland": "UEFA",
      "russia": "UEFA",
      "saudi-arabia": "AFC",
      "senegal": "CAF",
      "slovenia": "UEFA",
      "south-africa": "CAF",
      "south-korea": "AFC",
      "spain": "UEFA",
      "sweden": "UEFA",
      "tunisia": "CAF",
      "turkiye": "UEFA",
      "uruguay": "CONMEBOL",
      "usa": "CONCACAF"
    },
    "groups": {
      "A": [
        "france",
        "senegal",
        "uruguay",
        "denmark"
      ],
      "B": [
        "spain",
        "slovenia",
        "paraguay",
        "south-africa"
      ],
      "C": [
        "brazil",
        "turkiye",
        "china",
        "costa-rica"
      ],
      "D": [
        "south-korea",
        "poland",
        "usa",
        "portugal"
      ],
      "E": [
        "germany",
        "saudi-arabia",
        "republic-of-ireland",
        "cameroon"
      ],
      "F": [
        "argentina",
        "nigeria",
        "england",
        "sweden"
      ],
      "G": [
        "italy",
        "ecuador",
        "croatia",
        "mexico"
      ],
      "H": [
        "japan",
        "belgium",
        "russia",
        "tunisia"
      ]
    },
    "bracket": {
      "description": "Round of 16: Germany-Paraguay, Denmark-England, Sweden-Senegal, Spain-Republic of Ireland, Mexico-United States, Brazil-Belgium, Japan-Turkey, South Korea-Italy; Quarter-finals: Germany-United States, England-Brazil, Spain-South Korea, Senegal-Turkey; Semi-finals: Germany-South Korea, Brazil-Turkey; Third-place match: South Korea-Turkey; Final: Germany-Brazil",
      "rounds": [
        "round-of-16",
        "quarter-final",
        "semi-final",
        "third-place",
        "final"
      ]
    },
    "provenance": {
      "sourceName": "OpenFootball World Cup repository (2002--south-korea-n-japan) + FIFA 2002 page (user-supplied derived CSV)",
      "sourceUrl": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt; https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt; https://en.wikipedia.org/wiki/2002_FIFA_World_Cup",
      "sourceFile": "wc2002-identity.csv",
      "sha256": "ffbee796765f082af7551833ab5b95f5c4f7b6dafb13acab7ec7586f340aca7c",
      "licence": "OpenFootball CC0-1.0; FIFA pages reference-only; eloratings derived reference",
      "retrievedAt": "2026-06-22",
      "notes": "Compact raw identity (1 row; groups as JSON, confederations as colon-style string) normalized to teamIds[]/groups{}/confederations{}. CO-HOSTS South Korea + Japan (both AFC) parsed from the delimited hostCountries column; aggregate counts (AFC:4; CAF:5; CONCACAF:3; CONMEBOL:5; UEFA:15) cross-checked by the validator. format text: \"32 teams; 8 groups of 4; top 2 per group advanced to knockout; Round of 16 through Final; golden-goal extra time in knockout rounds where applicable\"."
    }
  },
  "results": [
    {
      "matchId": "wc2002-01",
      "date": "2002-05-31",
      "stage": "group",
      "group": "A",
      "teamA": "france",
      "teamB": "senegal",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Seoul World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-02",
      "date": "2002-06-01",
      "stage": "group",
      "group": "A",
      "teamA": "uruguay",
      "teamB": "denmark",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Ulsan Munsu Football Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-03",
      "date": "2002-06-06",
      "stage": "group",
      "group": "A",
      "teamA": "denmark",
      "teamB": "senegal",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Daegu World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-04",
      "date": "2002-06-06",
      "stage": "group",
      "group": "A",
      "teamA": "france",
      "teamB": "uruguay",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Busan Asiad Main Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-05",
      "date": "2002-06-11",
      "stage": "group",
      "group": "A",
      "teamA": "denmark",
      "teamB": "france",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Incheon Munhak Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-06",
      "date": "2002-06-11",
      "stage": "group",
      "group": "A",
      "teamA": "senegal",
      "teamB": "uruguay",
      "goalsA": 3,
      "goalsB": 3,
      "resultAt90": "D",
      "venue": "Suwon World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-07",
      "date": "2002-06-02",
      "stage": "group",
      "group": "B",
      "teamA": "paraguay",
      "teamB": "south-africa",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Busan Asiad Main Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-08",
      "date": "2002-06-02",
      "stage": "group",
      "group": "B",
      "teamA": "spain",
      "teamB": "slovenia",
      "goalsA": 3,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Gwangju World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-09",
      "date": "2002-06-07",
      "stage": "group",
      "group": "B",
      "teamA": "spain",
      "teamB": "paraguay",
      "goalsA": 3,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Jeonju World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-10",
      "date": "2002-06-08",
      "stage": "group",
      "group": "B",
      "teamA": "south-africa",
      "teamB": "slovenia",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Daegu World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-11",
      "date": "2002-06-12",
      "stage": "group",
      "group": "B",
      "teamA": "south-africa",
      "teamB": "spain",
      "goalsA": 2,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Daejeon World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-12",
      "date": "2002-06-12",
      "stage": "group",
      "group": "B",
      "teamA": "slovenia",
      "teamB": "paraguay",
      "goalsA": 1,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Jeju World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-13",
      "date": "2002-06-03",
      "stage": "group",
      "group": "C",
      "teamA": "brazil",
      "teamB": "turkiye",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Ulsan Munsu Football Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-14",
      "date": "2002-06-04",
      "stage": "group",
      "group": "C",
      "teamA": "china",
      "teamB": "costa-rica",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Gwangju World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-15",
      "date": "2002-06-08",
      "stage": "group",
      "group": "C",
      "teamA": "brazil",
      "teamB": "china",
      "goalsA": 4,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Jeju World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-16",
      "date": "2002-06-09",
      "stage": "group",
      "group": "C",
      "teamA": "costa-rica",
      "teamB": "turkiye",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Incheon Munhak Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-17",
      "date": "2002-06-13",
      "stage": "group",
      "group": "C",
      "teamA": "costa-rica",
      "teamB": "brazil",
      "goalsA": 2,
      "goalsB": 5,
      "resultAt90": "B",
      "venue": "Suwon World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-18",
      "date": "2002-06-13",
      "stage": "group",
      "group": "C",
      "teamA": "turkiye",
      "teamB": "china",
      "goalsA": 3,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Seoul World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-19",
      "date": "2002-06-04",
      "stage": "group",
      "group": "D",
      "teamA": "south-korea",
      "teamB": "poland",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Busan Asiad Main Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-20",
      "date": "2002-06-05",
      "stage": "group",
      "group": "D",
      "teamA": "usa",
      "teamB": "portugal",
      "goalsA": 3,
      "goalsB": 2,
      "resultAt90": "A",
      "venue": "Suwon World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-21",
      "date": "2002-06-10",
      "stage": "group",
      "group": "D",
      "teamA": "south-korea",
      "teamB": "usa",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Daegu World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-22",
      "date": "2002-06-10",
      "stage": "group",
      "group": "D",
      "teamA": "portugal",
      "teamB": "poland",
      "goalsA": 4,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Jeonju World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-23",
      "date": "2002-06-14",
      "stage": "group",
      "group": "D",
      "teamA": "portugal",
      "teamB": "south-korea",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Incheon Munhak Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-24",
      "date": "2002-06-14",
      "stage": "group",
      "group": "D",
      "teamA": "poland",
      "teamB": "usa",
      "goalsA": 3,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Daejeon World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-25",
      "date": "2002-06-01",
      "stage": "group",
      "group": "E",
      "teamA": "republic-of-ireland",
      "teamB": "cameroon",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Niigata Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-26",
      "date": "2002-06-01",
      "stage": "group",
      "group": "E",
      "teamA": "germany",
      "teamB": "saudi-arabia",
      "goalsA": 8,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Sapporo Dome",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-27",
      "date": "2002-06-05",
      "stage": "group",
      "group": "E",
      "teamA": "germany",
      "teamB": "republic-of-ireland",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Kashima Soccer Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-28",
      "date": "2002-06-06",
      "stage": "group",
      "group": "E",
      "teamA": "cameroon",
      "teamB": "saudi-arabia",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Saitama Stadium 2002",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-29",
      "date": "2002-06-11",
      "stage": "group",
      "group": "E",
      "teamA": "cameroon",
      "teamB": "germany",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Shizuoka Stadium Ecopa",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-30",
      "date": "2002-06-11",
      "stage": "group",
      "group": "E",
      "teamA": "saudi-arabia",
      "teamB": "republic-of-ireland",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "International Stadium Yokohama",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-31",
      "date": "2002-06-02",
      "stage": "group",
      "group": "F",
      "teamA": "argentina",
      "teamB": "nigeria",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Kashima Soccer Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-32",
      "date": "2002-06-02",
      "stage": "group",
      "group": "F",
      "teamA": "england",
      "teamB": "sweden",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Saitama Stadium 2002",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-33",
      "date": "2002-06-07",
      "stage": "group",
      "group": "F",
      "teamA": "sweden",
      "teamB": "nigeria",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Kobe Wing Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-34",
      "date": "2002-06-07",
      "stage": "group",
      "group": "F",
      "teamA": "argentina",
      "teamB": "england",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Sapporo Dome",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-35",
      "date": "2002-06-12",
      "stage": "group",
      "group": "F",
      "teamA": "sweden",
      "teamB": "argentina",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Miyagi Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-36",
      "date": "2002-06-12",
      "stage": "group",
      "group": "F",
      "teamA": "nigeria",
      "teamB": "england",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Nagai Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-37",
      "date": "2002-06-03",
      "stage": "group",
      "group": "G",
      "teamA": "croatia",
      "teamB": "mexico",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Niigata Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-38",
      "date": "2002-06-03",
      "stage": "group",
      "group": "G",
      "teamA": "italy",
      "teamB": "ecuador",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Sapporo Dome",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-39",
      "date": "2002-06-08",
      "stage": "group",
      "group": "G",
      "teamA": "italy",
      "teamB": "croatia",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Kashima Soccer Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-40",
      "date": "2002-06-09",
      "stage": "group",
      "group": "G",
      "teamA": "mexico",
      "teamB": "ecuador",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Miyagi Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-41",
      "date": "2002-06-13",
      "stage": "group",
      "group": "G",
      "teamA": "mexico",
      "teamB": "italy",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Oita Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-42",
      "date": "2002-06-13",
      "stage": "group",
      "group": "G",
      "teamA": "ecuador",
      "teamB": "croatia",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "International Stadium Yokohama",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-43",
      "date": "2002-06-04",
      "stage": "group",
      "group": "H",
      "teamA": "japan",
      "teamB": "belgium",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Saitama Stadium 2002",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-44",
      "date": "2002-06-05",
      "stage": "group",
      "group": "H",
      "teamA": "russia",
      "teamB": "tunisia",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Kobe Wing Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-45",
      "date": "2002-06-09",
      "stage": "group",
      "group": "H",
      "teamA": "japan",
      "teamB": "russia",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "International Stadium Yokohama",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-46",
      "date": "2002-06-10",
      "stage": "group",
      "group": "H",
      "teamA": "tunisia",
      "teamB": "belgium",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Oita Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-47",
      "date": "2002-06-14",
      "stage": "group",
      "group": "H",
      "teamA": "tunisia",
      "teamB": "japan",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Nagai Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-48",
      "date": "2002-06-14",
      "stage": "group",
      "group": "H",
      "teamA": "belgium",
      "teamB": "russia",
      "goalsA": 3,
      "goalsB": 2,
      "resultAt90": "A",
      "venue": "Shizuoka Stadium Ecopa",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup.txt"
    },
    {
      "matchId": "wc2002-49",
      "date": "2002-06-15",
      "stage": "round-of-16",
      "teamA": "germany",
      "teamB": "paraguay",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "germany",
      "venue": "Jeju World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    },
    {
      "matchId": "wc2002-50",
      "date": "2002-06-15",
      "stage": "round-of-16",
      "teamA": "denmark",
      "teamB": "england",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "winner": "england",
      "venue": "Niigata Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    },
    {
      "matchId": "wc2002-51",
      "date": "2002-06-16",
      "stage": "round-of-16",
      "teamA": "sweden",
      "teamB": "senegal",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "winner": "senegal",
      "venue": "Oita Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    },
    {
      "matchId": "wc2002-52",
      "date": "2002-06-16",
      "stage": "round-of-16",
      "teamA": "spain",
      "teamB": "republic-of-ireland",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 3,
        "b": 2
      },
      "winner": "spain",
      "venue": "Suwon World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    },
    {
      "matchId": "wc2002-53",
      "date": "2002-06-17",
      "stage": "round-of-16",
      "teamA": "mexico",
      "teamB": "usa",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "winner": "usa",
      "venue": "Jeonju World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    },
    {
      "matchId": "wc2002-54",
      "date": "2002-06-17",
      "stage": "round-of-16",
      "teamA": "brazil",
      "teamB": "belgium",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "brazil",
      "venue": "Kobe Wing Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    },
    {
      "matchId": "wc2002-55",
      "date": "2002-06-18",
      "stage": "round-of-16",
      "teamA": "japan",
      "teamB": "turkiye",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "winner": "turkiye",
      "venue": "Miyagi Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    },
    {
      "matchId": "wc2002-56",
      "date": "2002-06-18",
      "stage": "round-of-16",
      "teamA": "south-korea",
      "teamB": "italy",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "winner": "south-korea",
      "venue": "Daejeon World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    },
    {
      "matchId": "wc2002-57",
      "date": "2002-06-21",
      "stage": "quarter-final",
      "teamA": "england",
      "teamB": "brazil",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "winner": "brazil",
      "venue": "Shizuoka Stadium Ecopa",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    },
    {
      "matchId": "wc2002-58",
      "date": "2002-06-21",
      "stage": "quarter-final",
      "teamA": "germany",
      "teamB": "usa",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "germany",
      "venue": "Ulsan Munsu Football Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    },
    {
      "matchId": "wc2002-59",
      "date": "2002-06-22",
      "stage": "quarter-final",
      "teamA": "spain",
      "teamB": "south-korea",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 3,
        "b": 5
      },
      "winner": "south-korea",
      "venue": "Gwangju World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    },
    {
      "matchId": "wc2002-60",
      "date": "2002-06-22",
      "stage": "quarter-final",
      "teamA": "senegal",
      "teamB": "turkiye",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "winner": "turkiye",
      "venue": "Nagai Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    },
    {
      "matchId": "wc2002-61",
      "date": "2002-06-25",
      "stage": "semi-final",
      "teamA": "germany",
      "teamB": "south-korea",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "germany",
      "venue": "Seoul World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    },
    {
      "matchId": "wc2002-62",
      "date": "2002-06-26",
      "stage": "semi-final",
      "teamA": "brazil",
      "teamB": "turkiye",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "brazil",
      "venue": "Saitama Stadium 2002",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    },
    {
      "matchId": "wc2002-63",
      "date": "2002-06-29",
      "stage": "third-place",
      "teamA": "south-korea",
      "teamB": "turkiye",
      "goalsA": 2,
      "goalsB": 3,
      "resultAt90": "B",
      "winner": "turkiye",
      "venue": "Daegu World Cup Stadium",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    },
    {
      "matchId": "wc2002-64",
      "date": "2002-06-30",
      "stage": "final",
      "teamA": "germany",
      "teamB": "brazil",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "winner": "brazil",
      "venue": "International Stadium Yokohama",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2002--south-korea-n-japan/cup_finals.txt"
    }
  ],
  "elo": [
    {
      "teamId": "argentina",
      "rating": 2026,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "belgium",
      "rating": 1837,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "brazil",
      "rating": 1867,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "cameroon",
      "rating": 1787,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "china",
      "rating": 1531,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "costa-rica",
      "rating": 1755,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "croatia",
      "rating": 1815,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "denmark",
      "rating": 1854,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "ecuador",
      "rating": 1741,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "england",
      "rating": 1914,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "france",
      "rating": 2130,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "germany",
      "rating": 1869,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "italy",
      "rating": 2008,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "japan",
      "rating": 1848,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "mexico",
      "rating": 1832,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "nigeria",
      "rating": 1754,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "paraguay",
      "rating": 1731,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "poland",
      "rating": 1719,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "portugal",
      "rating": 1978,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "republic-of-ireland",
      "rating": 1873,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "russia",
      "rating": 1797,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "saudi-arabia",
      "rating": 1697,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "senegal",
      "rating": 1622,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "slovenia",
      "rating": 1745,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "south-africa",
      "rating": 1640,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "south-korea",
      "rating": 1734,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "spain",
      "rating": 1963,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "sweden",
      "rating": 1866,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "tunisia",
      "rating": 1708,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "turkiye",
      "rating": 1757,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "uruguay",
      "rating": 1811,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    },
    {
      "teamId": "usa",
      "rating": 1802,
      "asOfDate": "2002-05-30",
      "sourceRef": "https://www.eloratings.net/2002_World_Cup_start"
    }
  ],
  "fifa": [
    {
      "teamId": "argentina",
      "rank": 3,
      "points": 784,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "belgium",
      "rank": 23,
      "points": 653,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "brazil",
      "rank": 2,
      "points": 784,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "cameroon",
      "rank": 17,
      "points": 672,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "china",
      "rank": 50,
      "points": 566,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "costa-rica",
      "rank": 29,
      "points": 643,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "croatia",
      "rank": 21,
      "points": 655,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "denmark",
      "rank": 20,
      "points": 657,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "ecuador",
      "rank": 36,
      "points": 624,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "england",
      "rank": 12,
      "points": 694,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "france",
      "rank": 1,
      "points": 802,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "germany",
      "rank": 11,
      "points": 695,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "italy",
      "rank": 6,
      "points": 717,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "japan",
      "rank": 32,
      "points": 634,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "mexico",
      "rank": 7,
      "points": 716,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "nigeria",
      "rank": 27,
      "points": 644,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "paraguay",
      "rank": 18,
      "points": 671,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "poland",
      "rank": 38,
      "points": 615,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "portugal",
      "rank": 5,
      "points": 726,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "republic-of-ireland",
      "rank": 15,
      "points": 674,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "russia",
      "rank": 28,
      "points": 644,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "saudi-arabia",
      "rank": 34,
      "points": 627,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "senegal",
      "rank": 42,
      "points": 599,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "slovenia",
      "rank": 25,
      "points": 649,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "south-africa",
      "rank": 37,
      "points": 623,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "south-korea",
      "rank": 40,
      "points": 603,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "spain",
      "rank": 8,
      "points": 713,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "sweden",
      "rank": 19,
      "points": 665,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "tunisia",
      "rank": 31,
      "points": 635,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "turkiye",
      "rank": 22,
      "points": 654,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "uruguay",
      "rank": 24,
      "points": 652,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    },
    {
      "teamId": "usa",
      "rank": 13,
      "points": 690,
      "rankingDate": "2002-05-15",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2002-05-15"
    }
  ],
  "macro": [],
  "recentForm": []
};
