/**
 * Phase 1.18B-6 - WC-2014 historical source-pack snapshot (32 teams, 64 matches).
 * GENERATED by scripts/generate-historical-2014.mjs - DO NOT EDIT BY HAND.
 *
 * ISOLATED + UNWIRED: part of the backtesting layer (`data/historical/`,
 * `lib/backtesting/`). NEVER imported by the production 2026 app; nothing is wired
 * into lib/model/*; no probabilities change; no calibration, no tournament replay.
 * Validated by lib/backtesting/validate-historical.ts.
 *
 * DERIVED-ONLY: raw CSV/MD source files are NOT committed; their SHA-256 anchors live
 * in WC2014_SOURCE. Third historical pack (after WC-2022, WC-2018) for the bench.
 *
 * LEAKAGE: every Elo asOfDate (2014-06-11) and FIFA rankingDate (2014-06-05) is
 * strictly before the opening kickoff (2014-06-12T17:00:00-03:00 = 2014-06-12T20:00:00Z).
 * Match results are OUTCOMES ONLY and must never feed a pre-tournament feature.
 *
 * SCORE CONVENTION (mirrors 2022/2018): snapshot goalsA/goalsB store the 90-MINUTE
 * score; resultAt90 is derived from the 90' score; extra time (afterExtraTime) and
 * penalties (penalties MADE, not attempts) are recorded separately. The match
 * evaluator targets only 90-minute W/D/L. Final: Germany 1-0 Argentina after extra
 * time (0-0 at 90, so goalsA=0/goalsB=0, resultAt90 "D", afterExtraTime true).
 */
import type { HistoricalSourcePack, BacktestProvenance } from "@/lib/backtesting/types";

/** Per-file source provenance + SHA-256 anchors (raw files NOT committed). */
export const WC2014_SOURCE: {
  label: string;
  openingKickoff: string;
  retrievedAt: string;
  files: Record<string, BacktestProvenance>;
  notes: string;
} = {
  label: "FIFA World Cup 2014 (Brazil) historical source pack - backtesting",
  openingKickoff: "2014-06-12T17:00:00-03:00",
  retrievedAt: "2026-06-21",
  files: {
    identity: {
      sourceName: "OpenFootball World Cup repository (2014--brazil) + FIFA 2014 page",
      sourceUrl: "https://github.com/openfootball/worldcup",
      sourceFile: "wc2014-identity.csv",
      sha256: "c49a6116449ac9ffdbf187bd03bf69decb590e0d7d4a8327518bac64a8fea934",
      licence: "OpenFootball CC0-1.0 (Fjelstul alt. CC-BY-SA-4.0); FIFA page reference-only",
      retrievedAt: "2026-06-21",
      notes: "Compact 1-row identity (JSON groups, colon-style confederations) normalized; raw not committed.",
    },
    results: {
      sourceName: "OpenFootball World Cup repository (2014--brazil)",
      sourceUrl: "https://github.com/openfootball/worldcup",
      sourceFile: "wc2014-results.csv",
      sha256: "1d92cddda92ed6b0d9be06a4c72e3f54630760f152a19a438724780a5946f411",
      licence: "OpenFootball CC0-1.0 (Fjelstul alt. CC-BY-SA-4.0)",
      retrievedAt: "2026-06-21",
      notes:
        "64 matches; stage/outcome labels normalized to contract enums; outcomes only. Snapshot " +
        "goalsA/goalsB = 90-minute score (raw goalsA/goalsB are after-ET). Final: Germany 1-0 Argentina AET.",
    },
    elo: {
      sourceName: "World Football Elo Ratings 2014 World Cup start (eloratings.net)",
      sourceUrl: "https://www.eloratings.net/2014_World_Cup_start",
      sourceFile: "wc2014-elo.csv",
      sha256: "c6111018d1b1094b9003947af8ac83407acb96096fa84c8e8897340a41f209cc",
      licence: "eloratings/international-football.net reference; small derived values only",
      retrievedAt: "2026-06-21",
      asOfDate: "2014-06-11",
      notes: "Pre-tournament Elo as-of 2014-06-11, strictly before the opening kickoff. No host adjustment.",
    },
    fifa: {
      sourceName: "FIFA men's ranking 2014-06-05 (en.fifaranking.net mirror)",
      sourceUrl: "https://en.fifaranking.net/ranking/?d=2014-06-05",
      sourceFile: "wc2014-fifa.csv",
      sha256: "b542eadedb1fd7ee82935e61d3d73db5d53913318ff90ac88bff6122051b5e44",
      licence: "Public ranking mirror licensing unclear / reference-grade; official values conceptually",
      retrievedAt: "2026-06-21",
      asOfDate: "2014-06-05",
      notes:
        "Last pre-tournament FIFA release (2014-06-05); no post-tournament ranking used. Raw mirror not " +
        "committed - SHA-256 is the anchor.",
    },
    readme: {
      sourceName: "User-supplied source notes (README_SOURCE_NOTES.md)",
      sourceFile: "README_SOURCE_NOTES.md",
      sha256: "70b7a7ada2021f75df5756d44f569af6055d03bec5f437c8b9b1afac56d8be87",
      licence: "n/a (documentation of source strategy + licence notes)",
      retrievedAt: "2026-06-21",
      notes: "Records source strategy, leakage rules, and licence notes for the pack.",
    },
  },
  notes:
    "Backtesting pack (2014). Optional packs (macro, recent form, squads, managers, " +
    "venues/tournamentContext) are intentionally deferred. Sources: OpenFootball (CC0) is the " +
    "permissive fixtures/results route; Fjelstul is the richer backbone but carries CC-BY-SA " +
    "obligations; FIFA ranking values are official conceptually but supplied via a public mirror " +
    "(treat licensing cautiously); eloratings is a small derived Elo reference, not a raw dump. " +
    "Raw source files are NOT committed; checksums are the reproducibility anchor.",
};

/** Declared per-confederation entrant counts (from the compact identity row). */
export const WC2014_CONFEDERATION_COUNTS: Record<string, number> = {
  "AFC": 4,
  "CAF": 5,
  "CONCACAF": 4,
  "CONMEBOL": 6,
  "UEFA": 13
};

/** Source team display name -> historical team id (historical id space). */
export const WC2014_NAME_TO_ID: Record<string, string> = {
  "Brazil": "brazil",
  "Croatia": "croatia",
  "Mexico": "mexico",
  "Cameroon": "cameroon",
  "Spain": "spain",
  "Netherlands": "netherlands",
  "Chile": "chile",
  "Australia": "australia",
  "Colombia": "colombia",
  "Greece": "greece",
  "Côte d'Ivoire": "ivory-coast",
  "Japan": "japan",
  "Uruguay": "uruguay",
  "Costa Rica": "costa-rica",
  "England": "england",
  "Italy": "italy",
  "Switzerland": "switzerland",
  "Ecuador": "ecuador",
  "France": "france",
  "Honduras": "honduras",
  "Argentina": "argentina",
  "Bosnia-Herzegovina": "bosnia-herzegovina",
  "Iran": "iran",
  "Nigeria": "nigeria",
  "Germany": "germany",
  "Portugal": "portugal",
  "Ghana": "ghana",
  "USA": "usa",
  "Belgium": "belgium",
  "Algeria": "algeria",
  "Russia": "russia",
  "South Korea": "south-korea",
  "Ivory Coast": "ivory-coast",
  "Bosnia and Herzegovina": "bosnia-herzegovina",
  "IR Iran": "iran",
  "Korea Republic": "south-korea",
  "United States": "usa",
  "Holland": "netherlands"
};

export const WC2014_PACK: HistoricalSourcePack = {
  "identity": {
    "tournamentYear": 2014,
    "hostCountries": [
      "Brazil"
    ],
    "openingKickoff": "2014-06-12T17:00:00-03:00",
    "format": "32-team-8-groups",
    "teamIds": [
      "algeria",
      "argentina",
      "australia",
      "belgium",
      "bosnia-herzegovina",
      "brazil",
      "cameroon",
      "chile",
      "colombia",
      "costa-rica",
      "croatia",
      "ecuador",
      "england",
      "france",
      "germany",
      "ghana",
      "greece",
      "honduras",
      "iran",
      "italy",
      "ivory-coast",
      "japan",
      "mexico",
      "netherlands",
      "nigeria",
      "portugal",
      "russia",
      "south-korea",
      "spain",
      "switzerland",
      "uruguay",
      "usa"
    ],
    "confederations": {
      "algeria": "CAF",
      "argentina": "CONMEBOL",
      "australia": "AFC",
      "belgium": "UEFA",
      "bosnia-herzegovina": "UEFA",
      "brazil": "CONMEBOL",
      "cameroon": "CAF",
      "chile": "CONMEBOL",
      "colombia": "CONMEBOL",
      "costa-rica": "CONCACAF",
      "croatia": "UEFA",
      "ecuador": "CONMEBOL",
      "england": "UEFA",
      "france": "UEFA",
      "germany": "UEFA",
      "ghana": "CAF",
      "greece": "UEFA",
      "honduras": "CONCACAF",
      "iran": "AFC",
      "italy": "UEFA",
      "ivory-coast": "CAF",
      "japan": "AFC",
      "mexico": "CONCACAF",
      "netherlands": "UEFA",
      "nigeria": "CAF",
      "portugal": "UEFA",
      "russia": "UEFA",
      "south-korea": "AFC",
      "spain": "UEFA",
      "switzerland": "UEFA",
      "uruguay": "CONMEBOL",
      "usa": "CONCACAF"
    },
    "groups": {
      "A": [
        "brazil",
        "croatia",
        "mexico",
        "cameroon"
      ],
      "B": [
        "spain",
        "netherlands",
        "chile",
        "australia"
      ],
      "C": [
        "colombia",
        "greece",
        "ivory-coast",
        "japan"
      ],
      "D": [
        "uruguay",
        "costa-rica",
        "england",
        "italy"
      ],
      "E": [
        "switzerland",
        "ecuador",
        "france",
        "honduras"
      ],
      "F": [
        "argentina",
        "bosnia-herzegovina",
        "iran",
        "nigeria"
      ],
      "G": [
        "germany",
        "portugal",
        "ghana",
        "usa"
      ],
      "H": [
        "belgium",
        "algeria",
        "russia",
        "south-korea"
      ]
    },
    "bracket": {
      "description": "Round of 16: M49 1A-2B, M50 1C-2D, M51 1B-2A, M52 1D-2C, M53 1E-2F, M54 1G-2H, M55 1F-2E, M56 1H-2G; Quarter-finals: M57 W53-W54, M58 W49-W50, M59 W55-W56, M60 W51-W52; Semi-finals: M61 W57-W58, M62 W59-W60; Third-place match: L61-L62; Final: W61-W62.",
      "rounds": [
        "round-of-16",
        "quarter-final",
        "semi-final",
        "third-place",
        "final"
      ]
    },
    "provenance": {
      "sourceName": "OpenFootball World Cup repository (2014--brazil) + FIFA 2014 page (user-supplied derived CSV)",
      "sourceUrl": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt ; https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt",
      "sourceFile": "wc2014-identity.csv",
      "sha256": "c49a6116449ac9ffdbf187bd03bf69decb590e0d7d4a8327518bac64a8fea934",
      "licence": "OpenFootball CC0-1.0; Fjelstul (richer coverage) CC-BY-SA-4.0; FIFA pages reference-only",
      "retrievedAt": "2026-06-21",
      "notes": "Compact raw identity (1 row; groups as JSON, confederations as colon-style string) normalized to teamIds[]/groups{}/confederations{}. Per-team confederation is the known 2014 FIFA membership; aggregate counts (AFC:4; CAF:5; CONCACAF:4; CONMEBOL:6; UEFA:13) cross-checked by the validator. format text: \"32 teams; 8 groups of 4; top 2 per group advanced to knockout; Round of 16 through Final\"."
    }
  },
  "results": [
    {
      "matchId": "wc2014-01",
      "date": "2014-06-12",
      "stage": "group",
      "group": "A",
      "teamA": "brazil",
      "teamB": "croatia",
      "goalsA": 3,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Arena de São Paulo",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-02",
      "date": "2014-06-13",
      "stage": "group",
      "group": "A",
      "teamA": "mexico",
      "teamB": "cameroon",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Estádio das Dunas",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-03",
      "date": "2014-06-13",
      "stage": "group",
      "group": "B",
      "teamA": "spain",
      "teamB": "netherlands",
      "goalsA": 1,
      "goalsB": 5,
      "resultAt90": "B",
      "venue": "Arena Fonte Nova",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-04",
      "date": "2014-06-13",
      "stage": "group",
      "group": "B",
      "teamA": "chile",
      "teamB": "australia",
      "goalsA": 3,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Arena Pantanal",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-05",
      "date": "2014-06-14",
      "stage": "group",
      "group": "C",
      "teamA": "colombia",
      "teamB": "greece",
      "goalsA": 3,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Estádio Mineirão",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-06",
      "date": "2014-06-14",
      "stage": "group",
      "group": "C",
      "teamA": "ivory-coast",
      "teamB": "japan",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Arena Pernambuco",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-07",
      "date": "2014-06-14",
      "stage": "group",
      "group": "D",
      "teamA": "uruguay",
      "teamB": "costa-rica",
      "goalsA": 1,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Estádio Castelão",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-08",
      "date": "2014-06-14",
      "stage": "group",
      "group": "D",
      "teamA": "england",
      "teamB": "italy",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Arena Amazônia",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-09",
      "date": "2014-06-15",
      "stage": "group",
      "group": "E",
      "teamA": "switzerland",
      "teamB": "ecuador",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Estádio Nacional Mané Garrincha",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-10",
      "date": "2014-06-15",
      "stage": "group",
      "group": "E",
      "teamA": "france",
      "teamB": "honduras",
      "goalsA": 3,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Estádio Beira-Rio",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-11",
      "date": "2014-06-15",
      "stage": "group",
      "group": "F",
      "teamA": "argentina",
      "teamB": "bosnia-herzegovina",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Estádio do Maracanã",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-12",
      "date": "2014-06-16",
      "stage": "group",
      "group": "F",
      "teamA": "iran",
      "teamB": "nigeria",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Arena da Baixada",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-13",
      "date": "2014-06-16",
      "stage": "group",
      "group": "G",
      "teamA": "germany",
      "teamB": "portugal",
      "goalsA": 4,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Arena Fonte Nova",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-14",
      "date": "2014-06-16",
      "stage": "group",
      "group": "G",
      "teamA": "ghana",
      "teamB": "usa",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Estádio das Dunas",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-15",
      "date": "2014-06-17",
      "stage": "group",
      "group": "H",
      "teamA": "belgium",
      "teamB": "algeria",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Estádio Mineirão",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-16",
      "date": "2014-06-17",
      "stage": "group",
      "group": "H",
      "teamA": "russia",
      "teamB": "south-korea",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Arena Pantanal",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-17",
      "date": "2014-06-17",
      "stage": "group",
      "group": "A",
      "teamA": "brazil",
      "teamB": "mexico",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Estádio Castelão",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-18",
      "date": "2014-06-18",
      "stage": "group",
      "group": "A",
      "teamA": "cameroon",
      "teamB": "croatia",
      "goalsA": 0,
      "goalsB": 4,
      "resultAt90": "B",
      "venue": "Arena Amazônia",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-19",
      "date": "2014-06-18",
      "stage": "group",
      "group": "B",
      "teamA": "australia",
      "teamB": "netherlands",
      "goalsA": 2,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Estádio Beira-Rio",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-20",
      "date": "2014-06-18",
      "stage": "group",
      "group": "B",
      "teamA": "spain",
      "teamB": "chile",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Estádio do Maracanã",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-21",
      "date": "2014-06-19",
      "stage": "group",
      "group": "C",
      "teamA": "colombia",
      "teamB": "ivory-coast",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Estádio Nacional Mané Garrincha",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-22",
      "date": "2014-06-19",
      "stage": "group",
      "group": "C",
      "teamA": "japan",
      "teamB": "greece",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Estádio das Dunas",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-23",
      "date": "2014-06-19",
      "stage": "group",
      "group": "D",
      "teamA": "uruguay",
      "teamB": "england",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Arena de São Paulo",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-24",
      "date": "2014-06-20",
      "stage": "group",
      "group": "D",
      "teamA": "italy",
      "teamB": "costa-rica",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Arena Pernambuco",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-25",
      "date": "2014-06-20",
      "stage": "group",
      "group": "E",
      "teamA": "switzerland",
      "teamB": "france",
      "goalsA": 2,
      "goalsB": 5,
      "resultAt90": "B",
      "venue": "Arena Fonte Nova",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-26",
      "date": "2014-06-20",
      "stage": "group",
      "group": "E",
      "teamA": "honduras",
      "teamB": "ecuador",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Arena da Baixada",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-27",
      "date": "2014-06-21",
      "stage": "group",
      "group": "F",
      "teamA": "argentina",
      "teamB": "iran",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Estádio Mineirão",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-28",
      "date": "2014-06-21",
      "stage": "group",
      "group": "F",
      "teamA": "nigeria",
      "teamB": "bosnia-herzegovina",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Arena Pantanal",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-29",
      "date": "2014-06-21",
      "stage": "group",
      "group": "G",
      "teamA": "germany",
      "teamB": "ghana",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Estádio Castelão",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-30",
      "date": "2014-06-22",
      "stage": "group",
      "group": "G",
      "teamA": "usa",
      "teamB": "portugal",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Arena Amazônia",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-31",
      "date": "2014-06-22",
      "stage": "group",
      "group": "H",
      "teamA": "belgium",
      "teamB": "russia",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Estádio do Maracanã",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-32",
      "date": "2014-06-22",
      "stage": "group",
      "group": "H",
      "teamA": "south-korea",
      "teamB": "algeria",
      "goalsA": 2,
      "goalsB": 4,
      "resultAt90": "B",
      "venue": "Estádio Beira-Rio",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-33",
      "date": "2014-06-23",
      "stage": "group",
      "group": "A",
      "teamA": "cameroon",
      "teamB": "brazil",
      "goalsA": 1,
      "goalsB": 4,
      "resultAt90": "B",
      "venue": "Estádio Nacional Mané Garrincha",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-34",
      "date": "2014-06-23",
      "stage": "group",
      "group": "A",
      "teamA": "croatia",
      "teamB": "mexico",
      "goalsA": 1,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Arena Pernambuco",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-35",
      "date": "2014-06-23",
      "stage": "group",
      "group": "B",
      "teamA": "australia",
      "teamB": "spain",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Arena da Baixada",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-36",
      "date": "2014-06-23",
      "stage": "group",
      "group": "B",
      "teamA": "netherlands",
      "teamB": "chile",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Arena de São Paulo",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-37",
      "date": "2014-06-24",
      "stage": "group",
      "group": "C",
      "teamA": "japan",
      "teamB": "colombia",
      "goalsA": 1,
      "goalsB": 4,
      "resultAt90": "B",
      "venue": "Arena Pantanal",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-38",
      "date": "2014-06-24",
      "stage": "group",
      "group": "C",
      "teamA": "greece",
      "teamB": "ivory-coast",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Estádio Castelão",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-39",
      "date": "2014-06-24",
      "stage": "group",
      "group": "D",
      "teamA": "italy",
      "teamB": "uruguay",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Estádio das Dunas",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-40",
      "date": "2014-06-24",
      "stage": "group",
      "group": "D",
      "teamA": "costa-rica",
      "teamB": "england",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Estádio Mineirão",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-41",
      "date": "2014-06-25",
      "stage": "group",
      "group": "E",
      "teamA": "honduras",
      "teamB": "switzerland",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Arena Amazônia",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-42",
      "date": "2014-06-25",
      "stage": "group",
      "group": "E",
      "teamA": "ecuador",
      "teamB": "france",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Estádio do Maracanã",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-43",
      "date": "2014-06-25",
      "stage": "group",
      "group": "F",
      "teamA": "nigeria",
      "teamB": "argentina",
      "goalsA": 2,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Estádio Beira-Rio",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-44",
      "date": "2014-06-25",
      "stage": "group",
      "group": "F",
      "teamA": "bosnia-herzegovina",
      "teamB": "iran",
      "goalsA": 3,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Arena Fonte Nova",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-45",
      "date": "2014-06-26",
      "stage": "group",
      "group": "G",
      "teamA": "usa",
      "teamB": "germany",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Arena Pernambuco",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-46",
      "date": "2014-06-26",
      "stage": "group",
      "group": "G",
      "teamA": "portugal",
      "teamB": "ghana",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Estádio Nacional Mané Garrincha",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-47",
      "date": "2014-06-26",
      "stage": "group",
      "group": "H",
      "teamA": "south-korea",
      "teamB": "belgium",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Arena de São Paulo",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-48",
      "date": "2014-06-26",
      "stage": "group",
      "group": "H",
      "teamA": "algeria",
      "teamB": "russia",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Arena da Baixada",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup.txt"
    },
    {
      "matchId": "wc2014-49",
      "date": "2014-06-28",
      "stage": "round-of-16",
      "teamA": "brazil",
      "teamB": "chile",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 3,
        "b": 2
      },
      "winner": "brazil",
      "venue": "Estádio Mineirão",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    },
    {
      "matchId": "wc2014-50",
      "date": "2014-06-28",
      "stage": "round-of-16",
      "teamA": "colombia",
      "teamB": "uruguay",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "colombia",
      "venue": "Estádio do Maracanã",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    },
    {
      "matchId": "wc2014-51",
      "date": "2014-06-29",
      "stage": "round-of-16",
      "teamA": "netherlands",
      "teamB": "mexico",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "winner": "netherlands",
      "venue": "Estádio Castelão",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    },
    {
      "matchId": "wc2014-52",
      "date": "2014-06-29",
      "stage": "round-of-16",
      "teamA": "costa-rica",
      "teamB": "greece",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 5,
        "b": 3
      },
      "winner": "costa-rica",
      "venue": "Arena Pernambuco",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    },
    {
      "matchId": "wc2014-53",
      "date": "2014-06-30",
      "stage": "round-of-16",
      "teamA": "france",
      "teamB": "nigeria",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "france",
      "venue": "Estádio Nacional Mané Garrincha",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    },
    {
      "matchId": "wc2014-54",
      "date": "2014-06-30",
      "stage": "round-of-16",
      "teamA": "germany",
      "teamB": "algeria",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "winner": "germany",
      "venue": "Estádio Beira-Rio",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    },
    {
      "matchId": "wc2014-55",
      "date": "2014-07-01",
      "stage": "round-of-16",
      "teamA": "argentina",
      "teamB": "switzerland",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "winner": "argentina",
      "venue": "Arena de São Paulo",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    },
    {
      "matchId": "wc2014-56",
      "date": "2014-07-01",
      "stage": "round-of-16",
      "teamA": "belgium",
      "teamB": "usa",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "winner": "belgium",
      "venue": "Arena Fonte Nova",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    },
    {
      "matchId": "wc2014-57",
      "date": "2014-07-04",
      "stage": "quarter-final",
      "teamA": "france",
      "teamB": "germany",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "winner": "germany",
      "venue": "Estádio do Maracanã",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    },
    {
      "matchId": "wc2014-58",
      "date": "2014-07-04",
      "stage": "quarter-final",
      "teamA": "brazil",
      "teamB": "colombia",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "winner": "brazil",
      "venue": "Estádio Castelão",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    },
    {
      "matchId": "wc2014-59",
      "date": "2014-07-05",
      "stage": "quarter-final",
      "teamA": "argentina",
      "teamB": "belgium",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "argentina",
      "venue": "Estádio Nacional Mané Garrincha",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    },
    {
      "matchId": "wc2014-60",
      "date": "2014-07-05",
      "stage": "quarter-final",
      "teamA": "netherlands",
      "teamB": "costa-rica",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 4,
        "b": 3
      },
      "winner": "netherlands",
      "venue": "Arena Fonte Nova",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    },
    {
      "matchId": "wc2014-61",
      "date": "2014-07-08",
      "stage": "semi-final",
      "teamA": "brazil",
      "teamB": "germany",
      "goalsA": 1,
      "goalsB": 7,
      "resultAt90": "B",
      "winner": "germany",
      "venue": "Estádio Mineirão",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    },
    {
      "matchId": "wc2014-62",
      "date": "2014-07-09",
      "stage": "semi-final",
      "teamA": "netherlands",
      "teamB": "argentina",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 2,
        "b": 4
      },
      "winner": "argentina",
      "venue": "Arena de São Paulo",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    },
    {
      "matchId": "wc2014-63",
      "date": "2014-07-12",
      "stage": "third-place",
      "teamA": "brazil",
      "teamB": "netherlands",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "winner": "netherlands",
      "venue": "Estádio Nacional Mané Garrincha",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    },
    {
      "matchId": "wc2014-64",
      "date": "2014-07-13",
      "stage": "final",
      "teamA": "germany",
      "teamB": "argentina",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "winner": "germany",
      "venue": "Estádio do Maracanã",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2014--brazil/cup_finals.txt"
    }
  ],
  "elo": [
    {
      "teamId": "algeria",
      "rating": 1625,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "argentina",
      "rating": 2019,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "australia",
      "rating": 1708,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "belgium",
      "rating": 1852,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "bosnia-herzegovina",
      "rating": 1785,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "brazil",
      "rating": 2138,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "cameroon",
      "rating": 1606,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "chile",
      "rating": 1920,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "colombia",
      "rating": 1922,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "costa-rica",
      "rating": 1711,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "croatia",
      "rating": 1819,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "ecuador",
      "rating": 1837,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "england",
      "rating": 1931,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "france",
      "rating": 1897,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "germany",
      "rating": 2073,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "ghana",
      "rating": 1704,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "greece",
      "rating": 1823,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "honduras",
      "rating": 1669,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "iran",
      "rating": 1715,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "italy",
      "rating": 1888,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "ivory-coast",
      "rating": 1772,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "japan",
      "rating": 1785,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "mexico",
      "rating": 1814,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "netherlands",
      "rating": 1985,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "nigeria",
      "rating": 1727,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "portugal",
      "rating": 1942,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "russia",
      "rating": 1848,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "south-korea",
      "rating": 1667,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "spain",
      "rating": 2107,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "switzerland",
      "rating": 1854,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "uruguay",
      "rating": 1918,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    },
    {
      "teamId": "usa",
      "rating": 1857,
      "asOfDate": "2014-06-11",
      "sourceRef": "https://www.eloratings.net/2014_World_Cup_start"
    }
  ],
  "fifa": [
    {
      "teamId": "algeria",
      "rank": 22,
      "points": 858,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "argentina",
      "rank": 5,
      "points": 1175,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "australia",
      "rank": 62,
      "points": 526,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "belgium",
      "rank": 11,
      "points": 1074,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "bosnia-herzegovina",
      "rank": 21,
      "points": 873,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "brazil",
      "rank": 3,
      "points": 1242,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "cameroon",
      "rank": 56,
      "points": 558,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "chile",
      "rank": 14,
      "points": 1026,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "colombia",
      "rank": 8,
      "points": 1137,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "costa-rica",
      "rank": 28,
      "points": 762,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "croatia",
      "rank": 18,
      "points": 903,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "ecuador",
      "rank": 26,
      "points": 791,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "england",
      "rank": 10,
      "points": 1090,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "france",
      "rank": 17,
      "points": 913,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "germany",
      "rank": 2,
      "points": 1300,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "ghana",
      "rank": 37,
      "points": 704,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "greece",
      "rank": 12,
      "points": 1064,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "honduras",
      "rank": 33,
      "points": 731,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "iran",
      "rank": 43,
      "points": 641,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "italy",
      "rank": 9,
      "points": 1104,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "ivory-coast",
      "rank": 23,
      "points": 809,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "japan",
      "rank": 46,
      "points": 626,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "mexico",
      "rank": 20,
      "points": 882,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "netherlands",
      "rank": 15,
      "points": 981,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "nigeria",
      "rank": 44,
      "points": 640,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "portugal",
      "rank": 4,
      "points": 1189,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "russia",
      "rank": 19,
      "points": 893,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "south-korea",
      "rank": 57,
      "points": 547,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "spain",
      "rank": 1,
      "points": 1485,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "switzerland",
      "rank": 6,
      "points": 1149,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "uruguay",
      "rank": 7,
      "points": 1147,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    },
    {
      "teamId": "usa",
      "rank": 13,
      "points": 1035,
      "rankingDate": "2014-06-05",
      "sourceRef": "https://en.fifaranking.net/ranking/?d=2014-06-05"
    }
  ],
  "macro": [],
  "recentForm": []
};
