/**
 * Phase 1.18B-4 - WC-2018 historical source-pack snapshot (32 teams, 64 matches).
 * GENERATED by scripts/generate-historical-2018.mjs - DO NOT EDIT BY HAND.
 *
 * ISOLATED + UNWIRED: part of the backtesting layer (`data/historical/`,
 * `lib/backtesting/`). NEVER imported by the production 2026 app; nothing is wired
 * into lib/model/*; no probabilities change; no calibration, no tournament replay.
 * Validated by lib/backtesting/validate-historical.ts.
 *
 * DERIVED-ONLY: raw CSV/MD source files are NOT committed; their SHA-256 anchors live
 * in WC2018_SOURCE. Second historical pack (after WC-2022) for the match-level bench.
 *
 * LEAKAGE: every Elo asOfDate (2018-06-13) and FIFA rankingDate (2018-06-07) is
 * strictly before the opening kickoff (2018-06-14T18:00:00+03:00 = 2018-06-14T15:00:00Z).
 * FIFA uses the last pre-tournament release (2018-06-07), NOT the post-tournament
 * July 2018 ranking. Match results are OUTCOMES ONLY and must never feed a
 * pre-tournament feature; goalsA/goalsB are the 90-minute goals (ET/penalties, which
 * store penalties MADE not attempts, recorded separately). Final: France 4-2 Croatia.
 */
import type { HistoricalSourcePack, BacktestProvenance } from "@/lib/backtesting/types";

/** Per-file source provenance + SHA-256 anchors (raw files NOT committed). */
export const WC2018_SOURCE: {
  label: string;
  openingKickoff: string;
  retrievedAt: string;
  files: Record<string, BacktestProvenance>;
  notes: string;
} = {
  label: "FIFA World Cup 2018 (Russia) historical source pack - backtesting",
  openingKickoff: "2018-06-14T18:00:00+03:00",
  retrievedAt: "2026-06-21",
  files: {
    identity: {
      sourceName: "OpenFootball World Cup repository + FIFA 2018 page (Fjelstul backbone)",
      sourceUrl: "https://github.com/openfootball/worldcup",
      sourceFile: "wc2018-identity.csv",
      sha256: "0fcbe98d61db3621832308b38c62fa8f120ddcdac799569633c532830015b21d",
      licence: "OpenFootball CC0-1.0 (Fjelstul alt. CC-BY-SA-4.0); FIFA page reference-only",
      retrievedAt: "2026-06-21",
      notes: "Compact 1-row identity normalized into the snapshot; raw not committed.",
    },
    results: {
      sourceName: "OpenFootball World Cup repository + FIFA 2018 page",
      sourceUrl: "https://github.com/openfootball/worldcup",
      sourceFile: "wc2018-results.csv",
      sha256: "d906b886bae109f125dc550325f86d79565046360382b442a60bddde11b35ef7",
      licence: "OpenFootball CC0-1.0 (Fjelstul alt. CC-BY-SA-4.0)",
      retrievedAt: "2026-06-21",
      notes:
        "64 matches; stage/outcome labels normalized to contract enums; outcomes only. " +
        "Final correctly stored France 4-2 Croatia; penalty fields store penalties made.",
    },
    elo: {
      sourceName: "International-football.net Elo table as on 2018-06-13 (calculated on eloratings.net)",
      sourceUrl: "https://www.eloratings.net/",
      sourceFile: "wc2018-elo.csv",
      sha256: "29f72ab76178be1091a66e15c187d41e6cb198cc013b8bd644fcc0e63a7a3f63",
      licence: "eloratings/international-football.net reference; small derived values only",
      retrievedAt: "2026-06-21",
      asOfDate: "2018-06-13",
      notes: "Pre-tournament Elo as-of 2018-06-13, strictly before the opening kickoff.",
    },
    fifa: {
      sourceName: "FIFA men's ranking 2018-06-07 (Dato-Futbol historical CSV + kjytay cross-check)",
      sourceUrl: "https://inside.fifa.com/fifa-world-ranking/men",
      sourceFile: "wc2018-fifa.csv",
      sha256: "2ad328f42832b9c6ed0b2e54f72067f2fc4032a5b2dea2f70f4c06fe1866fc6b",
      licence: "Public CSV mirror licensing unclear / reference-grade; official values conceptually",
      retrievedAt: "2026-06-21",
      asOfDate: "2018-06-07",
      notes:
        "Last pre-tournament FIFA release (2018-06-07); the post-tournament July 2018 ranking is " +
        "deliberately NOT used. Raw mirror not committed - SHA-256 is the anchor.",
    },
    readme: {
      sourceName: "User-supplied source notes (README_SOURCE_NOTES.md)",
      sourceFile: "README_SOURCE_NOTES.md",
      sha256: "490dab599b81e837ea240902a13084b90a54e69d56c33c60abee8ebba37e0b1e",
      licence: "n/a (documentation of source strategy + licence notes)",
      retrievedAt: "2026-06-21",
      notes: "Records source strategy, leakage rules, and licence notes for the pack.",
    },
  },
  notes:
    "Backtesting pack (2018). Optional packs (macro, recent form, squads, managers, " +
    "venues/tournamentContext) are intentionally deferred. Sources: OpenFootball (CC0) is the " +
    "permissive fixtures/results route; Fjelstul is the richer backbone but carries CC-BY-SA " +
    "obligations; FIFA ranking values are official conceptually but supplied via public mirrors " +
    "(treat licensing cautiously); eloratings/international-football.net are small derived Elo " +
    "references, not raw dumps. Raw source files are NOT committed; checksums are the anchor.",
};

/** Declared per-confederation entrant counts (from the compact identity row). */
export const WC2018_CONFEDERATION_COUNTS: Record<string, number> = {
  "AFC": 5,
  "CAF": 5,
  "CONCACAF": 3,
  "CONMEBOL": 5,
  "UEFA": 14,
  "OFC": 0
};

/** Source team display name -> historical team id (historical id space). */
export const WC2018_NAME_TO_ID: Record<string, string> = {
  "Russia": "russia",
  "Saudi Arabia": "saudi-arabia",
  "Egypt": "egypt",
  "Uruguay": "uruguay",
  "Portugal": "portugal",
  "Spain": "spain",
  "Morocco": "morocco",
  "Iran": "iran",
  "France": "france",
  "Australia": "australia",
  "Peru": "peru",
  "Denmark": "denmark",
  "Argentina": "argentina",
  "Iceland": "iceland",
  "Croatia": "croatia",
  "Nigeria": "nigeria",
  "Brazil": "brazil",
  "Switzerland": "switzerland",
  "Costa Rica": "costa-rica",
  "Serbia": "serbia",
  "Germany": "germany",
  "Mexico": "mexico",
  "Sweden": "sweden",
  "South Korea": "south-korea",
  "Belgium": "belgium",
  "Panama": "panama",
  "Tunisia": "tunisia",
  "England": "england",
  "Poland": "poland",
  "Senegal": "senegal",
  "Colombia": "colombia",
  "Japan": "japan"
};

export const WC2018_PACK: HistoricalSourcePack = {
  "identity": {
    "tournamentYear": 2018,
    "hostCountries": [
      "Russia"
    ],
    "openingKickoff": "2018-06-14T18:00:00+03:00",
    "format": "32-team-8-groups",
    "teamIds": [
      "argentina",
      "australia",
      "belgium",
      "brazil",
      "colombia",
      "costa-rica",
      "croatia",
      "denmark",
      "egypt",
      "england",
      "france",
      "germany",
      "iceland",
      "iran",
      "japan",
      "mexico",
      "morocco",
      "nigeria",
      "panama",
      "peru",
      "poland",
      "portugal",
      "russia",
      "saudi-arabia",
      "senegal",
      "serbia",
      "south-korea",
      "spain",
      "sweden",
      "switzerland",
      "tunisia",
      "uruguay"
    ],
    "confederations": {
      "argentina": "CONMEBOL",
      "australia": "AFC",
      "belgium": "UEFA",
      "brazil": "CONMEBOL",
      "colombia": "CONMEBOL",
      "costa-rica": "CONCACAF",
      "croatia": "UEFA",
      "denmark": "UEFA",
      "egypt": "CAF",
      "england": "UEFA",
      "france": "UEFA",
      "germany": "UEFA",
      "iceland": "UEFA",
      "iran": "AFC",
      "japan": "AFC",
      "mexico": "CONCACAF",
      "morocco": "CAF",
      "nigeria": "CAF",
      "panama": "CONCACAF",
      "peru": "CONMEBOL",
      "poland": "UEFA",
      "portugal": "UEFA",
      "russia": "UEFA",
      "saudi-arabia": "AFC",
      "senegal": "CAF",
      "serbia": "UEFA",
      "south-korea": "AFC",
      "spain": "UEFA",
      "sweden": "UEFA",
      "switzerland": "UEFA",
      "tunisia": "CAF",
      "uruguay": "CONMEBOL"
    },
    "groups": {
      "A": [
        "russia",
        "saudi-arabia",
        "egypt",
        "uruguay"
      ],
      "B": [
        "portugal",
        "spain",
        "morocco",
        "iran"
      ],
      "C": [
        "france",
        "australia",
        "peru",
        "denmark"
      ],
      "D": [
        "argentina",
        "iceland",
        "croatia",
        "nigeria"
      ],
      "E": [
        "brazil",
        "switzerland",
        "costa-rica",
        "serbia"
      ],
      "F": [
        "germany",
        "mexico",
        "sweden",
        "south-korea"
      ],
      "G": [
        "belgium",
        "panama",
        "tunisia",
        "england"
      ],
      "H": [
        "poland",
        "senegal",
        "colombia",
        "japan"
      ]
    },
    "bracket": {
      "description": "R16: A1-B2, C1-D2, E1-F2, G1-H2, B1-A2, D1-C2, F1-E2, H1-G2; QF; SF; third-place; final",
      "roundOf16": [
        {
          "home": "A1",
          "away": "B2"
        },
        {
          "home": "C1",
          "away": "D2"
        },
        {
          "home": "E1",
          "away": "F2"
        },
        {
          "home": "G1",
          "away": "H2"
        },
        {
          "home": "B1",
          "away": "A2"
        },
        {
          "home": "D1",
          "away": "C2"
        },
        {
          "home": "F1",
          "away": "E2"
        },
        {
          "home": "H1",
          "away": "G2"
        }
      ],
      "rounds": [
        "round-of-16",
        "quarter-final",
        "semi-final",
        "third-place",
        "final"
      ]
    },
    "provenance": {
      "sourceName": "OpenFootball World Cup repository + FIFA 2018 tournament page (user-supplied derived CSV)",
      "sourceUrl": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup",
      "sourceFile": "wc2018-identity.csv",
      "sha256": "0fcbe98d61db3621832308b38c62fa8f120ddcdac799569633c532830015b21d",
      "licence": "OpenFootball CC0-1.0; Fjelstul (richer coverage) CC-BY-SA-4.0; FIFA pages reference-only",
      "retrievedAt": "2026-06-21",
      "notes": "Compact raw identity (1 row, groups/confederations as strings) normalized to teamIds[]/groups{}/confederations{}. Per-team confederation is the known 2018 FIFA membership; aggregate counts (AFC=5; CAF=5; CONCACAF=3; CONMEBOL=5; UEFA=14; OFC=0) cross-checked by the validator. format text: \"32 teams; eight groups of four; top two from each group advance to Round of 16; then quarter-finals, semi-finals, third-place match and final\"."
    }
  },
  "results": [
    {
      "matchId": "WC2018-001",
      "date": "2018-06-14",
      "stage": "group",
      "group": "A",
      "teamA": "russia",
      "teamB": "saudi-arabia",
      "goalsA": 5,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Luzhniki Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-002",
      "date": "2018-06-15",
      "stage": "group",
      "group": "A",
      "teamA": "egypt",
      "teamB": "uruguay",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Ekaterinburg Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-003",
      "date": "2018-06-15",
      "stage": "group",
      "group": "B",
      "teamA": "morocco",
      "teamB": "iran",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Saint Petersburg Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-004",
      "date": "2018-06-15",
      "stage": "group",
      "group": "B",
      "teamA": "portugal",
      "teamB": "spain",
      "goalsA": 3,
      "goalsB": 3,
      "resultAt90": "D",
      "venue": "Fisht Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-005",
      "date": "2018-06-16",
      "stage": "group",
      "group": "C",
      "teamA": "france",
      "teamB": "australia",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Kazan Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-006",
      "date": "2018-06-16",
      "stage": "group",
      "group": "D",
      "teamA": "argentina",
      "teamB": "iceland",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Spartak Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-007",
      "date": "2018-06-16",
      "stage": "group",
      "group": "C",
      "teamA": "peru",
      "teamB": "denmark",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Mordovia Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-008",
      "date": "2018-06-16",
      "stage": "group",
      "group": "D",
      "teamA": "croatia",
      "teamB": "nigeria",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Kaliningrad Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-009",
      "date": "2018-06-17",
      "stage": "group",
      "group": "E",
      "teamA": "costa-rica",
      "teamB": "serbia",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Samara Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-010",
      "date": "2018-06-17",
      "stage": "group",
      "group": "F",
      "teamA": "germany",
      "teamB": "mexico",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Luzhniki Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-011",
      "date": "2018-06-17",
      "stage": "group",
      "group": "E",
      "teamA": "brazil",
      "teamB": "switzerland",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Rostov Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-012",
      "date": "2018-06-18",
      "stage": "group",
      "group": "F",
      "teamA": "sweden",
      "teamB": "south-korea",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Nizhny Novgorod Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-013",
      "date": "2018-06-18",
      "stage": "group",
      "group": "G",
      "teamA": "belgium",
      "teamB": "panama",
      "goalsA": 3,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Fisht Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-014",
      "date": "2018-06-18",
      "stage": "group",
      "group": "G",
      "teamA": "tunisia",
      "teamB": "england",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Volgograd Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-015",
      "date": "2018-06-19",
      "stage": "group",
      "group": "H",
      "teamA": "colombia",
      "teamB": "japan",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Mordovia Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-016",
      "date": "2018-06-19",
      "stage": "group",
      "group": "H",
      "teamA": "poland",
      "teamB": "senegal",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Spartak Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-017",
      "date": "2018-06-19",
      "stage": "group",
      "group": "A",
      "teamA": "russia",
      "teamB": "egypt",
      "goalsA": 3,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Saint Petersburg Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-018",
      "date": "2018-06-20",
      "stage": "group",
      "group": "B",
      "teamA": "portugal",
      "teamB": "morocco",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Luzhniki Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-019",
      "date": "2018-06-20",
      "stage": "group",
      "group": "A",
      "teamA": "uruguay",
      "teamB": "saudi-arabia",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Rostov Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-020",
      "date": "2018-06-20",
      "stage": "group",
      "group": "B",
      "teamA": "iran",
      "teamB": "spain",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Kazan Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-021",
      "date": "2018-06-21",
      "stage": "group",
      "group": "C",
      "teamA": "denmark",
      "teamB": "australia",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Samara Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-022",
      "date": "2018-06-21",
      "stage": "group",
      "group": "C",
      "teamA": "france",
      "teamB": "peru",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Ekaterinburg Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-023",
      "date": "2018-06-21",
      "stage": "group",
      "group": "D",
      "teamA": "argentina",
      "teamB": "croatia",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Nizhny Novgorod Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-024",
      "date": "2018-06-22",
      "stage": "group",
      "group": "E",
      "teamA": "brazil",
      "teamB": "costa-rica",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Saint Petersburg Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-025",
      "date": "2018-06-22",
      "stage": "group",
      "group": "D",
      "teamA": "nigeria",
      "teamB": "iceland",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Volgograd Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-026",
      "date": "2018-06-22",
      "stage": "group",
      "group": "E",
      "teamA": "serbia",
      "teamB": "switzerland",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Kaliningrad Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-027",
      "date": "2018-06-23",
      "stage": "group",
      "group": "G",
      "teamA": "belgium",
      "teamB": "tunisia",
      "goalsA": 5,
      "goalsB": 2,
      "resultAt90": "A",
      "venue": "Spartak Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-028",
      "date": "2018-06-23",
      "stage": "group",
      "group": "F",
      "teamA": "south-korea",
      "teamB": "mexico",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Rostov Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-029",
      "date": "2018-06-23",
      "stage": "group",
      "group": "F",
      "teamA": "germany",
      "teamB": "sweden",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Fisht Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-030",
      "date": "2018-06-24",
      "stage": "group",
      "group": "G",
      "teamA": "england",
      "teamB": "panama",
      "goalsA": 6,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Nizhny Novgorod Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-031",
      "date": "2018-06-24",
      "stage": "group",
      "group": "H",
      "teamA": "japan",
      "teamB": "senegal",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Ekaterinburg Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-032",
      "date": "2018-06-24",
      "stage": "group",
      "group": "H",
      "teamA": "poland",
      "teamB": "colombia",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Kazan Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-033",
      "date": "2018-06-25",
      "stage": "group",
      "group": "A",
      "teamA": "saudi-arabia",
      "teamB": "egypt",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Volgograd Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-034",
      "date": "2018-06-25",
      "stage": "group",
      "group": "A",
      "teamA": "uruguay",
      "teamB": "russia",
      "goalsA": 3,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Samara Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-035",
      "date": "2018-06-25",
      "stage": "group",
      "group": "B",
      "teamA": "iran",
      "teamB": "portugal",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Mordovia Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-036",
      "date": "2018-06-25",
      "stage": "group",
      "group": "B",
      "teamA": "spain",
      "teamB": "morocco",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Kaliningrad Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-037",
      "date": "2018-06-26",
      "stage": "group",
      "group": "C",
      "teamA": "australia",
      "teamB": "peru",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Fisht Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-038",
      "date": "2018-06-26",
      "stage": "group",
      "group": "C",
      "teamA": "denmark",
      "teamB": "france",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Luzhniki Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-039",
      "date": "2018-06-26",
      "stage": "group",
      "group": "D",
      "teamA": "nigeria",
      "teamB": "argentina",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Saint Petersburg Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-040",
      "date": "2018-06-26",
      "stage": "group",
      "group": "D",
      "teamA": "iceland",
      "teamB": "croatia",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Rostov Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-041",
      "date": "2018-06-27",
      "stage": "group",
      "group": "F",
      "teamA": "mexico",
      "teamB": "sweden",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Ekaterinburg Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-042",
      "date": "2018-06-27",
      "stage": "group",
      "group": "F",
      "teamA": "south-korea",
      "teamB": "germany",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Kazan Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-043",
      "date": "2018-06-27",
      "stage": "group",
      "group": "E",
      "teamA": "switzerland",
      "teamB": "costa-rica",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Nizhny Novgorod Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-044",
      "date": "2018-06-27",
      "stage": "group",
      "group": "E",
      "teamA": "serbia",
      "teamB": "brazil",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Spartak Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-045",
      "date": "2018-06-28",
      "stage": "group",
      "group": "H",
      "teamA": "senegal",
      "teamB": "colombia",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Samara Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-046",
      "date": "2018-06-28",
      "stage": "group",
      "group": "H",
      "teamA": "japan",
      "teamB": "poland",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Volgograd Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-047",
      "date": "2018-06-28",
      "stage": "group",
      "group": "G",
      "teamA": "england",
      "teamB": "belgium",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Kaliningrad Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-048",
      "date": "2018-06-28",
      "stage": "group",
      "group": "G",
      "teamA": "panama",
      "teamB": "tunisia",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Mordovia Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-049",
      "date": "2018-06-30",
      "stage": "round-of-16",
      "teamA": "france",
      "teamB": "argentina",
      "goalsA": 4,
      "goalsB": 3,
      "resultAt90": "A",
      "winner": "france",
      "venue": "Kazan Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-050",
      "date": "2018-06-30",
      "stage": "round-of-16",
      "teamA": "uruguay",
      "teamB": "portugal",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "winner": "uruguay",
      "venue": "Fisht Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-051",
      "date": "2018-07-01",
      "stage": "round-of-16",
      "teamA": "spain",
      "teamB": "russia",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 3,
        "b": 4
      },
      "winner": "russia",
      "venue": "Luzhniki Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-052",
      "date": "2018-07-01",
      "stage": "round-of-16",
      "teamA": "croatia",
      "teamB": "denmark",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 3,
        "b": 2
      },
      "winner": "croatia",
      "venue": "Nizhny Novgorod Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-053",
      "date": "2018-07-02",
      "stage": "round-of-16",
      "teamA": "brazil",
      "teamB": "mexico",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "brazil",
      "venue": "Samara Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-054",
      "date": "2018-07-02",
      "stage": "round-of-16",
      "teamA": "belgium",
      "teamB": "japan",
      "goalsA": 3,
      "goalsB": 2,
      "resultAt90": "A",
      "winner": "belgium",
      "venue": "Rostov Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-055",
      "date": "2018-07-03",
      "stage": "round-of-16",
      "teamA": "sweden",
      "teamB": "switzerland",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "sweden",
      "venue": "Saint Petersburg Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-056",
      "date": "2018-07-03",
      "stage": "round-of-16",
      "teamA": "colombia",
      "teamB": "england",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 3,
        "b": 4
      },
      "winner": "england",
      "venue": "Spartak Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-057",
      "date": "2018-07-06",
      "stage": "quarter-final",
      "teamA": "uruguay",
      "teamB": "france",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "winner": "france",
      "venue": "Nizhny Novgorod Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-058",
      "date": "2018-07-06",
      "stage": "quarter-final",
      "teamA": "brazil",
      "teamB": "belgium",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "winner": "belgium",
      "venue": "Kazan Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-059",
      "date": "2018-07-07",
      "stage": "quarter-final",
      "teamA": "sweden",
      "teamB": "england",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "winner": "england",
      "venue": "Samara Arena",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-060",
      "date": "2018-07-07",
      "stage": "quarter-final",
      "teamA": "russia",
      "teamB": "croatia",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 3,
        "b": 4
      },
      "winner": "croatia",
      "venue": "Fisht Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-061",
      "date": "2018-07-10",
      "stage": "semi-final",
      "teamA": "france",
      "teamB": "belgium",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "france",
      "venue": "Saint Petersburg Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-062",
      "date": "2018-07-11",
      "stage": "semi-final",
      "teamA": "croatia",
      "teamB": "england",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "winner": "croatia",
      "venue": "Luzhniki Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-063",
      "date": "2018-07-14",
      "stage": "third-place",
      "teamA": "belgium",
      "teamB": "england",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "belgium",
      "venue": "Saint Petersburg Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    },
    {
      "matchId": "WC2018-064",
      "date": "2018-07-15",
      "stage": "final",
      "teamA": "france",
      "teamB": "croatia",
      "goalsA": 4,
      "goalsB": 2,
      "resultAt90": "A",
      "winner": "france",
      "venue": "Luzhniki Stadium",
      "sourceRef": "https://github.com/openfootball/worldcup; https://github.com/openfootball/worldcup.json; https://www.fifa.com/tournaments/mens/worldcup/2018russia; https://github.com/jfjelstul/worldcup"
    }
  ],
  "elo": [
    {
      "teamId": "argentina",
      "rating": 1985,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "australia",
      "rating": 1741,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "belgium",
      "rating": 1937,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "brazil",
      "rating": 2142,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "colombia",
      "rating": 1928,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "costa-rica",
      "rating": 1743,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "croatia",
      "rating": 1853,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "denmark",
      "rating": 1855,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "egypt",
      "rating": 1643,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "england",
      "rating": 1948,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "france",
      "rating": 1987,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "germany",
      "rating": 2077,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "iceland",
      "rating": 1764,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "iran",
      "rating": 1790,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "japan",
      "rating": 1684,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "mexico",
      "rating": 1850,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "morocco",
      "rating": 1733,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "nigeria",
      "rating": 1684,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "panama",
      "rating": 1657,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "peru",
      "rating": 1916,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "poland",
      "rating": 1831,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "portugal",
      "rating": 1969,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "russia",
      "rating": 1678,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "saudi-arabia",
      "rating": 1586,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "senegal",
      "rating": 1749,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "serbia",
      "rating": 1778,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "south-korea",
      "rating": 1713,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "spain",
      "rating": 2044,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "sweden",
      "rating": 1795,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "switzerland",
      "rating": 1889,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "tunisia",
      "rating": 1656,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    },
    {
      "teamId": "uruguay",
      "rating": 1893,
      "asOfDate": "2018-06-13",
      "sourceRef": "https://www.international-football.net/elo-ratings-table?confed=&day=13&month=06&year=2018; https://www.eloratings.net/"
    }
  ],
  "fifa": [
    {
      "teamId": "argentina",
      "rank": 5,
      "points": 1241,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "australia",
      "rank": 36,
      "points": 718,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "belgium",
      "rank": 3,
      "points": 1298,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "brazil",
      "rank": 2,
      "points": 1431,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "colombia",
      "rank": 16,
      "points": 986,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "costa-rica",
      "rank": 23,
      "points": 884,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "croatia",
      "rank": 20,
      "points": 945,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "denmark",
      "rank": 12,
      "points": 1051,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "egypt",
      "rank": 45,
      "points": 649,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "england",
      "rank": 12,
      "points": 1051,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "france",
      "rank": 7,
      "points": 1198,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "germany",
      "rank": 1,
      "points": 1558,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "iceland",
      "rank": 22,
      "points": 908,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "iran",
      "rank": 37,
      "points": 708,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "japan",
      "rank": 61,
      "points": 521,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "mexico",
      "rank": 15,
      "points": 989,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "morocco",
      "rank": 41,
      "points": 686,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "nigeria",
      "rank": 48,
      "points": 618,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "panama",
      "rank": 55,
      "points": 571,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "peru",
      "rank": 11,
      "points": 1125,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "poland",
      "rank": 8,
      "points": 1183,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "portugal",
      "rank": 4,
      "points": 1274,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "russia",
      "rank": 70,
      "points": 457,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "saudi-arabia",
      "rank": 67,
      "points": 465,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "senegal",
      "rank": 27,
      "points": 838,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "serbia",
      "rank": 34,
      "points": 751,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "south-korea",
      "rank": 57,
      "points": 544,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "spain",
      "rank": 10,
      "points": 1126,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "sweden",
      "rank": 24,
      "points": 880,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "switzerland",
      "rank": 6,
      "points": 1199,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "tunisia",
      "rank": 21,
      "points": 910,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    },
    {
      "teamId": "uruguay",
      "rank": 14,
      "points": 1018,
      "rankingDate": "2018-06-07",
      "sourceRef": "https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv; https://inside.fifa.com/fifa-world-ranking/men; https://github.com/kjytay/FIFA-world-cup-2018"
    }
  ],
  "macro": [],
  "recentForm": []
};
