/**
 * Phase 1.19B - WC-2006 historical source-pack snapshot (32 teams, 64 matches). STRETCH.
 * GENERATED by scripts/generate-historical-2006.mjs - DO NOT EDIT BY HAND.
 *
 * ISOLATED + UNWIRED: part of the backtesting layer (`data/historical/`,
 * `lib/backtesting/`). NEVER imported by the production 2026 app; nothing is wired
 * into lib/model/*; no probabilities change; no calibration, no tournament replay.
 * Validated by lib/backtesting/validate-historical.ts.
 *
 * STRETCH EVIDENCE ONLY: WC-2006 is an ADDITIVE stretch pack. It does NOT change the
 * primary four-tournament (2010/2014/2018/2022) diagnostic headline, does NOT recompute
 * LOTO, and does NOT approve calibration (calibration remains NO-GO). Per-tournament
 * diagnostics are NOT pooled with the primary scope.
 *
 * DERIVED-ONLY: raw CSV/MD source files are NOT committed; their SHA-256 anchors live
 * in WC2006_SOURCE.
 *
 * LEAKAGE: every Elo asOfDate (2006-06-08) and FIFA rankingDate (2006-05-17) is
 * strictly before the opening kickoff (2006-06-09T18:00:00+02:00 = 2006-06-09T16:00:00Z).
 * Match results are OUTCOMES ONLY and must never feed a pre-tournament feature.
 *
 * SCORE CONVENTION (mirrors 2022/2018/2014/2010): snapshot goalsA/goalsB store the
 * 90-MINUTE score; resultAt90 is derived from the 90' score; extra time
 * (afterExtraTime) and penalties (penalties MADE, not attempts) are recorded
 * separately. The evaluator targets only 90-minute W/D/L. Final: Italy 1-1 France
 * after extra time (1-1 at 90, so goalsA=1/goalsB=1, resultAt90 "D", afterExtraTime
 * true, penalties Italy 5-3).
 *
 * SLUGS: "Serbia and Montenegro" -> serbia-and-montenegro (HISTORICAL-ONLY, distinct
 * from modern `serbia`); "Czech Republic" -> czechia (REUSE canonical slug);
 * Australia -> OFC (source-pack qualification/allocation convention, sole OFC entrant).
 */
import type { HistoricalSourcePack, BacktestProvenance } from "@/lib/backtesting/types";

/** Per-file source provenance + SHA-256 anchors (raw files NOT committed). */
export const WC2006_SOURCE: {
  label: string;
  openingKickoff: string;
  retrievedAt: string;
  files: Record<string, BacktestProvenance>;
  notes: string;
} = {
  label: "FIFA World Cup 2006 (Germany) historical source pack - backtesting (STRETCH)",
  openingKickoff: "2006-06-09T18:00:00+02:00",
  retrievedAt: "2026-06-21",
  files: {
    identity: {
      sourceName: "OpenFootball World Cup repository (2006--germany) + FIFA 2006 page",
      sourceUrl: "https://github.com/openfootball/worldcup",
      sourceFile: "wc2006-identity.csv",
      sha256: "dd39530f719a2ed856916c5a8d263be0af037824acf775f8cb6bfe6f60ff36c1",
      licence: "OpenFootball CC0-1.0; FIFA page reference-only",
      retrievedAt: "2026-06-21",
      notes: "Compact 1-row identity (JSON groups, colon-style confederations) normalized; raw not committed. Australia=OFC (source allocation).",
    },
    results: {
      sourceName: "OpenFootball World Cup repository (2006--germany)",
      sourceUrl: "https://github.com/openfootball/worldcup",
      sourceFile: "wc2006-results.csv",
      sha256: "e3cec3f67e67b931acbdb847869bd8bfec52820010feb458244c3eceb9036b86",
      licence: "OpenFootball CC0-1.0",
      retrievedAt: "2026-06-21",
      notes:
        "64 matches; stage/outcome labels normalized to contract enums; outcomes only. Snapshot " +
        "goalsA/goalsB = 90-minute score (raw goalsA/goalsB are after-ET). Final: Italy 1-1 France AET, pens 5-3.",
    },
    elo: {
      sourceName: "World Football Elo Ratings 2006 World Cup start (eloratings.net)",
      sourceUrl: "https://www.eloratings.net/2006_World_Cup_start",
      sourceFile: "wc2006-elo.csv",
      sha256: "d1a66fd72f7f0ec4e7856ae32985fe4904b5ebfc01962842faae750e97f33223",
      licence: "eloratings/international-football.net reference; small derived values only",
      retrievedAt: "2026-06-21",
      asOfDate: "2006-06-08",
      notes: "Pre-tournament Elo as-of 2006-06-08, strictly before the opening kickoff. No host adjustment.",
    },
    fifa: {
      sourceName: "FIFA men's ranking 2006-05-17 (en.fifaranking.net mirror)",
      sourceUrl: "https://en.fifaranking.net/ranking/index.php?d=2006-05-17",
      sourceFile: "wc2006-fifa.csv",
      sha256: "3f55adc620056e0c8240e6b7ad8544ce3c89ceca5ecc65db1f3c02c72e6a46f4",
      licence: "Public ranking mirror licensing unclear / reference-grade; official values conceptually",
      retrievedAt: "2026-06-21",
      asOfDate: "2006-05-17",
      notes:
        "Last pre-tournament FIFA release (exact date 2006-05-17); no post-tournament ranking used. Ranks may " +
        "contain ties (uniqueness not asserted). Raw mirror not committed - SHA-256 is the anchor.",
    },
    readme: {
      sourceName: "User-supplied source notes (README_SOURCE_NOTES.md)",
      sourceFile: "README_SOURCE_NOTES.md",
      sha256: "832713b561b57dba32e28992a6a2d019045b6b0d47e8610f5e188a715121e549",
      licence: "n/a (documentation of source strategy + licence notes)",
      retrievedAt: "2026-06-21",
      notes: "Records source strategy, leakage rules, ET/penalty cases, and licence notes for the pack.",
    },
  },
  notes:
    "STRETCH backtesting pack (2006). Optional packs (macro, recent form, squads, managers, " +
    "venues/tournamentContext) are intentionally deferred. Sources: OpenFootball (CC0) is the " +
    "permissive fixtures/results route; FIFA ranking values are official conceptually but supplied via a " +
    "public mirror (treat licensing cautiously); eloratings is a small derived Elo reference, not a raw " +
    "dump. Raw source files are NOT committed; checksums are the reproducibility anchor. Stretch-only: this " +
    "does not change the primary four-tournament diagnostics, does not recompute LOTO, and does not approve " +
    "calibration (calibration remains NO-GO).",
};

/** Declared per-confederation entrant counts (from the compact identity row). */
export const WC2006_CONFEDERATION_COUNTS: Record<string, number> = {
  "AFC": 4,
  "CAF": 5,
  "CONCACAF": 4,
  "CONMEBOL": 4,
  "OFC": 1,
  "UEFA": 14
};

/** Source team display name -> historical team id (historical id space). */
export const WC2006_NAME_TO_ID: Record<string, string> = {
  "Germany": "germany",
  "Ecuador": "ecuador",
  "Poland": "poland",
  "Costa Rica": "costa-rica",
  "England": "england",
  "Sweden": "sweden",
  "Paraguay": "paraguay",
  "Trinidad and Tobago": "trinidad-and-tobago",
  "Argentina": "argentina",
  "Netherlands": "netherlands",
  "Côte d'Ivoire": "ivory-coast",
  "Serbia and Montenegro": "serbia-and-montenegro",
  "Portugal": "portugal",
  "Mexico": "mexico",
  "Angola": "angola",
  "Iran": "iran",
  "Italy": "italy",
  "Ghana": "ghana",
  "Czech Republic": "czechia",
  "USA": "usa",
  "Brazil": "brazil",
  "Australia": "australia",
  "Croatia": "croatia",
  "Japan": "japan",
  "Switzerland": "switzerland",
  "France": "france",
  "South Korea": "south-korea",
  "Togo": "togo",
  "Spain": "spain",
  "Ukraine": "ukraine",
  "Tunisia": "tunisia",
  "Saudi Arabia": "saudi-arabia",
  "Ivory Coast": "ivory-coast",
  "United States": "usa",
  "Korea Republic": "south-korea",
  "Czechia": "czechia",
  "Czech Rep.": "czechia",
  "IR Iran": "iran"
};

export const WC2006_PACK: HistoricalSourcePack = {
  "identity": {
    "tournamentYear": 2006,
    "hostCountries": [
      "Germany"
    ],
    "openingKickoff": "2006-06-09T18:00:00+02:00",
    "format": "32-team-8-groups",
    "teamIds": [
      "angola",
      "argentina",
      "australia",
      "brazil",
      "costa-rica",
      "croatia",
      "czechia",
      "ecuador",
      "england",
      "france",
      "germany",
      "ghana",
      "iran",
      "italy",
      "ivory-coast",
      "japan",
      "mexico",
      "netherlands",
      "paraguay",
      "poland",
      "portugal",
      "saudi-arabia",
      "serbia-and-montenegro",
      "south-korea",
      "spain",
      "sweden",
      "switzerland",
      "togo",
      "trinidad-and-tobago",
      "tunisia",
      "ukraine",
      "usa"
    ],
    "confederations": {
      "angola": "CAF",
      "argentina": "CONMEBOL",
      "australia": "OFC",
      "brazil": "CONMEBOL",
      "costa-rica": "CONCACAF",
      "croatia": "UEFA",
      "czechia": "UEFA",
      "ecuador": "CONMEBOL",
      "england": "UEFA",
      "france": "UEFA",
      "germany": "UEFA",
      "ghana": "CAF",
      "iran": "AFC",
      "italy": "UEFA",
      "ivory-coast": "CAF",
      "japan": "AFC",
      "mexico": "CONCACAF",
      "netherlands": "UEFA",
      "paraguay": "CONMEBOL",
      "poland": "UEFA",
      "portugal": "UEFA",
      "saudi-arabia": "AFC",
      "serbia-and-montenegro": "UEFA",
      "south-korea": "AFC",
      "spain": "UEFA",
      "sweden": "UEFA",
      "switzerland": "UEFA",
      "togo": "CAF",
      "trinidad-and-tobago": "CONCACAF",
      "tunisia": "CAF",
      "ukraine": "UEFA",
      "usa": "CONCACAF"
    },
    "groups": {
      "A": [
        "germany",
        "ecuador",
        "poland",
        "costa-rica"
      ],
      "B": [
        "england",
        "sweden",
        "paraguay",
        "trinidad-and-tobago"
      ],
      "C": [
        "argentina",
        "netherlands",
        "ivory-coast",
        "serbia-and-montenegro"
      ],
      "D": [
        "portugal",
        "mexico",
        "angola",
        "iran"
      ],
      "E": [
        "italy",
        "ghana",
        "czechia",
        "usa"
      ],
      "F": [
        "brazil",
        "australia",
        "croatia",
        "japan"
      ],
      "G": [
        "switzerland",
        "france",
        "south-korea",
        "togo"
      ],
      "H": [
        "spain",
        "ukraine",
        "tunisia",
        "saudi-arabia"
      ]
    },
    "bracket": {
      "description": "Round of 16: M49 1A-2B, M50 1C-2D, M51 1B-2A, M52 1D-2C, M53 1E-2F, M54 1G-2H, M55 1F-2E, M56 1H-2G; Quarter-finals: M57 W49-W50, M58 W53-W54, M59 W51-W52, M60 W55-W56; Semi-finals: M61 W57-W58, M62 W59-W60; Third-place match: L61-L62; Final: W61-W62.",
      "rounds": [
        "round-of-16",
        "quarter-final",
        "semi-final",
        "third-place",
        "final"
      ]
    },
    "provenance": {
      "sourceName": "OpenFootball World Cup repository (2006--germany) + FIFA 2006 page (user-supplied derived CSV)",
      "sourceUrl": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt ; https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt",
      "sourceFile": "wc2006-identity.csv",
      "sha256": "dd39530f719a2ed856916c5a8d263be0af037824acf775f8cb6bfe6f60ff36c1",
      "licence": "OpenFootball CC0-1.0; FIFA pages reference-only; eloratings derived reference",
      "retrievedAt": "2026-06-21",
      "notes": "Compact raw identity (1 row; groups as JSON, confederations as colon-style string) normalized to teamIds[]/groups{}/confederations{}. Per-team confederation follows the source-pack 2006 allocation (Australia OFC); aggregate counts (AFC:4; CAF:5; CONCACAF:4; CONMEBOL:4; OFC:1; UEFA:14) cross-checked by the validator. format text: \"32 teams; 8 groups of 4; top 2 per group advanced to knockout; Round of 16 through Final\"."
    }
  },
  "results": [
    {
      "matchId": "wc2006-01",
      "date": "2006-06-09",
      "stage": "group",
      "group": "A",
      "teamA": "germany",
      "teamB": "costa-rica",
      "goalsA": 4,
      "goalsB": 2,
      "resultAt90": "A",
      "venue": "Allianz Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-02",
      "date": "2006-06-09",
      "stage": "group",
      "group": "A",
      "teamA": "poland",
      "teamB": "ecuador",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Veltins-Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-03",
      "date": "2006-06-14",
      "stage": "group",
      "group": "A",
      "teamA": "germany",
      "teamB": "poland",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Signal Iduna Park",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-04",
      "date": "2006-06-15",
      "stage": "group",
      "group": "A",
      "teamA": "ecuador",
      "teamB": "costa-rica",
      "goalsA": 3,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "AOL Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-05",
      "date": "2006-06-20",
      "stage": "group",
      "group": "A",
      "teamA": "ecuador",
      "teamB": "germany",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Olympiastadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-06",
      "date": "2006-06-20",
      "stage": "group",
      "group": "A",
      "teamA": "costa-rica",
      "teamB": "poland",
      "goalsA": 1,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "AWD-Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-07",
      "date": "2006-06-10",
      "stage": "group",
      "group": "B",
      "teamA": "england",
      "teamB": "paraguay",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Commerzbank-Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-08",
      "date": "2006-06-10",
      "stage": "group",
      "group": "B",
      "teamA": "trinidad-and-tobago",
      "teamB": "sweden",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Signal Iduna Park",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-09",
      "date": "2006-06-15",
      "stage": "group",
      "group": "B",
      "teamA": "england",
      "teamB": "trinidad-and-tobago",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Frankenstadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-10",
      "date": "2006-06-15",
      "stage": "group",
      "group": "B",
      "teamA": "sweden",
      "teamB": "paraguay",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Olympiastadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-11",
      "date": "2006-06-20",
      "stage": "group",
      "group": "B",
      "teamA": "sweden",
      "teamB": "england",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "RheinEnergieStadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-12",
      "date": "2006-06-20",
      "stage": "group",
      "group": "B",
      "teamA": "paraguay",
      "teamB": "trinidad-and-tobago",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Fritz-Walter-Stadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-13",
      "date": "2006-06-10",
      "stage": "group",
      "group": "C",
      "teamA": "argentina",
      "teamB": "ivory-coast",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "AOL Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-14",
      "date": "2006-06-11",
      "stage": "group",
      "group": "C",
      "teamA": "serbia-and-montenegro",
      "teamB": "netherlands",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Zentralstadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-15",
      "date": "2006-06-16",
      "stage": "group",
      "group": "C",
      "teamA": "argentina",
      "teamB": "serbia-and-montenegro",
      "goalsA": 6,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Veltins-Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-16",
      "date": "2006-06-16",
      "stage": "group",
      "group": "C",
      "teamA": "netherlands",
      "teamB": "ivory-coast",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Gottlieb-Daimler-Stadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-17",
      "date": "2006-06-21",
      "stage": "group",
      "group": "C",
      "teamA": "netherlands",
      "teamB": "argentina",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Commerzbank-Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-18",
      "date": "2006-06-21",
      "stage": "group",
      "group": "C",
      "teamA": "ivory-coast",
      "teamB": "serbia-and-montenegro",
      "goalsA": 3,
      "goalsB": 2,
      "resultAt90": "A",
      "venue": "Allianz Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-19",
      "date": "2006-06-11",
      "stage": "group",
      "group": "D",
      "teamA": "mexico",
      "teamB": "iran",
      "goalsA": 3,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Frankenstadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-20",
      "date": "2006-06-11",
      "stage": "group",
      "group": "D",
      "teamA": "angola",
      "teamB": "portugal",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "RheinEnergieStadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-21",
      "date": "2006-06-16",
      "stage": "group",
      "group": "D",
      "teamA": "mexico",
      "teamB": "angola",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "AWD-Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-22",
      "date": "2006-06-17",
      "stage": "group",
      "group": "D",
      "teamA": "portugal",
      "teamB": "iran",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Commerzbank-Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-23",
      "date": "2006-06-21",
      "stage": "group",
      "group": "D",
      "teamA": "portugal",
      "teamB": "mexico",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Veltins-Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-24",
      "date": "2006-06-21",
      "stage": "group",
      "group": "D",
      "teamA": "iran",
      "teamB": "angola",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Zentralstadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-25",
      "date": "2006-06-12",
      "stage": "group",
      "group": "E",
      "teamA": "italy",
      "teamB": "ghana",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "AWD-Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-26",
      "date": "2006-06-12",
      "stage": "group",
      "group": "E",
      "teamA": "usa",
      "teamB": "czechia",
      "goalsA": 0,
      "goalsB": 3,
      "resultAt90": "B",
      "venue": "Veltins-Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-27",
      "date": "2006-06-17",
      "stage": "group",
      "group": "E",
      "teamA": "italy",
      "teamB": "usa",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Fritz-Walter-Stadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-28",
      "date": "2006-06-17",
      "stage": "group",
      "group": "E",
      "teamA": "czechia",
      "teamB": "ghana",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "RheinEnergieStadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-29",
      "date": "2006-06-22",
      "stage": "group",
      "group": "E",
      "teamA": "czechia",
      "teamB": "italy",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "AOL Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-30",
      "date": "2006-06-22",
      "stage": "group",
      "group": "E",
      "teamA": "ghana",
      "teamB": "usa",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Frankenstadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-31",
      "date": "2006-06-13",
      "stage": "group",
      "group": "F",
      "teamA": "brazil",
      "teamB": "croatia",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Olympiastadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-32",
      "date": "2006-06-12",
      "stage": "group",
      "group": "F",
      "teamA": "australia",
      "teamB": "japan",
      "goalsA": 3,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Fritz-Walter-Stadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-33",
      "date": "2006-06-18",
      "stage": "group",
      "group": "F",
      "teamA": "brazil",
      "teamB": "australia",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Allianz Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-34",
      "date": "2006-06-18",
      "stage": "group",
      "group": "F",
      "teamA": "japan",
      "teamB": "croatia",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Frankenstadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-35",
      "date": "2006-06-22",
      "stage": "group",
      "group": "F",
      "teamA": "japan",
      "teamB": "brazil",
      "goalsA": 1,
      "goalsB": 4,
      "resultAt90": "B",
      "venue": "Signal Iduna Park",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-36",
      "date": "2006-06-22",
      "stage": "group",
      "group": "F",
      "teamA": "croatia",
      "teamB": "australia",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Gottlieb-Daimler-Stadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-37",
      "date": "2006-06-13",
      "stage": "group",
      "group": "G",
      "teamA": "france",
      "teamB": "switzerland",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "venue": "Gottlieb-Daimler-Stadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-38",
      "date": "2006-06-13",
      "stage": "group",
      "group": "G",
      "teamA": "south-korea",
      "teamB": "togo",
      "goalsA": 2,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Commerzbank-Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-39",
      "date": "2006-06-18",
      "stage": "group",
      "group": "G",
      "teamA": "france",
      "teamB": "south-korea",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "venue": "Zentralstadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-40",
      "date": "2006-06-19",
      "stage": "group",
      "group": "G",
      "teamA": "togo",
      "teamB": "switzerland",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "Signal Iduna Park",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-41",
      "date": "2006-06-23",
      "stage": "group",
      "group": "G",
      "teamA": "togo",
      "teamB": "france",
      "goalsA": 0,
      "goalsB": 2,
      "resultAt90": "B",
      "venue": "RheinEnergieStadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-42",
      "date": "2006-06-23",
      "stage": "group",
      "group": "G",
      "teamA": "switzerland",
      "teamB": "south-korea",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "AWD-Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-43",
      "date": "2006-06-14",
      "stage": "group",
      "group": "H",
      "teamA": "spain",
      "teamB": "ukraine",
      "goalsA": 4,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Zentralstadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-44",
      "date": "2006-06-14",
      "stage": "group",
      "group": "H",
      "teamA": "tunisia",
      "teamB": "saudi-arabia",
      "goalsA": 2,
      "goalsB": 2,
      "resultAt90": "D",
      "venue": "Allianz Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-45",
      "date": "2006-06-19",
      "stage": "group",
      "group": "H",
      "teamA": "spain",
      "teamB": "tunisia",
      "goalsA": 3,
      "goalsB": 1,
      "resultAt90": "A",
      "venue": "Gottlieb-Daimler-Stadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-46",
      "date": "2006-06-19",
      "stage": "group",
      "group": "H",
      "teamA": "saudi-arabia",
      "teamB": "ukraine",
      "goalsA": 0,
      "goalsB": 4,
      "resultAt90": "B",
      "venue": "AOL Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-47",
      "date": "2006-06-23",
      "stage": "group",
      "group": "H",
      "teamA": "saudi-arabia",
      "teamB": "spain",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "venue": "Fritz-Walter-Stadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-48",
      "date": "2006-06-23",
      "stage": "group",
      "group": "H",
      "teamA": "ukraine",
      "teamB": "tunisia",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "venue": "Olympiastadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup.txt"
    },
    {
      "matchId": "wc2006-49",
      "date": "2006-06-24",
      "stage": "round-of-16",
      "teamA": "germany",
      "teamB": "sweden",
      "goalsA": 2,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "germany",
      "venue": "Allianz Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    },
    {
      "matchId": "wc2006-50",
      "date": "2006-06-24",
      "stage": "round-of-16",
      "teamA": "argentina",
      "teamB": "mexico",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "winner": "argentina",
      "venue": "Zentralstadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    },
    {
      "matchId": "wc2006-51",
      "date": "2006-06-25",
      "stage": "round-of-16",
      "teamA": "england",
      "teamB": "ecuador",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "england",
      "venue": "Gottlieb-Daimler-Stadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    },
    {
      "matchId": "wc2006-52",
      "date": "2006-06-25",
      "stage": "round-of-16",
      "teamA": "portugal",
      "teamB": "netherlands",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "portugal",
      "venue": "Frankenstadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    },
    {
      "matchId": "wc2006-53",
      "date": "2006-06-26",
      "stage": "round-of-16",
      "teamA": "italy",
      "teamB": "australia",
      "goalsA": 1,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "italy",
      "venue": "Fritz-Walter-Stadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    },
    {
      "matchId": "wc2006-54",
      "date": "2006-06-26",
      "stage": "round-of-16",
      "teamA": "switzerland",
      "teamB": "ukraine",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 0,
        "b": 3
      },
      "winner": "ukraine",
      "venue": "RheinEnergieStadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    },
    {
      "matchId": "wc2006-55",
      "date": "2006-06-27",
      "stage": "round-of-16",
      "teamA": "brazil",
      "teamB": "ghana",
      "goalsA": 3,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "brazil",
      "venue": "Signal Iduna Park",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    },
    {
      "matchId": "wc2006-56",
      "date": "2006-06-27",
      "stage": "round-of-16",
      "teamA": "spain",
      "teamB": "france",
      "goalsA": 1,
      "goalsB": 3,
      "resultAt90": "B",
      "winner": "france",
      "venue": "AWD-Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    },
    {
      "matchId": "wc2006-57",
      "date": "2006-06-30",
      "stage": "quarter-final",
      "teamA": "germany",
      "teamB": "argentina",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 4,
        "b": 2
      },
      "winner": "germany",
      "venue": "Olympiastadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    },
    {
      "matchId": "wc2006-58",
      "date": "2006-06-30",
      "stage": "quarter-final",
      "teamA": "italy",
      "teamB": "ukraine",
      "goalsA": 3,
      "goalsB": 0,
      "resultAt90": "A",
      "winner": "italy",
      "venue": "AOL Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    },
    {
      "matchId": "wc2006-59",
      "date": "2006-07-01",
      "stage": "quarter-final",
      "teamA": "england",
      "teamB": "portugal",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 1,
        "b": 3
      },
      "winner": "portugal",
      "venue": "Veltins-Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    },
    {
      "matchId": "wc2006-60",
      "date": "2006-07-01",
      "stage": "quarter-final",
      "teamA": "brazil",
      "teamB": "france",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "winner": "france",
      "venue": "Commerzbank-Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    },
    {
      "matchId": "wc2006-61",
      "date": "2006-07-04",
      "stage": "semi-final",
      "teamA": "germany",
      "teamB": "italy",
      "goalsA": 0,
      "goalsB": 0,
      "resultAt90": "D",
      "afterExtraTime": true,
      "winner": "italy",
      "venue": "Signal Iduna Park",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    },
    {
      "matchId": "wc2006-62",
      "date": "2006-07-05",
      "stage": "semi-final",
      "teamA": "portugal",
      "teamB": "france",
      "goalsA": 0,
      "goalsB": 1,
      "resultAt90": "B",
      "winner": "france",
      "venue": "Allianz Arena",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    },
    {
      "matchId": "wc2006-63",
      "date": "2006-07-08",
      "stage": "third-place",
      "teamA": "germany",
      "teamB": "portugal",
      "goalsA": 3,
      "goalsB": 1,
      "resultAt90": "A",
      "winner": "germany",
      "venue": "Gottlieb-Daimler-Stadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    },
    {
      "matchId": "wc2006-64",
      "date": "2006-07-09",
      "stage": "final",
      "teamA": "italy",
      "teamB": "france",
      "goalsA": 1,
      "goalsB": 1,
      "resultAt90": "D",
      "afterExtraTime": true,
      "penalties": {
        "a": 5,
        "b": 3
      },
      "winner": "italy",
      "venue": "Olympiastadion",
      "sourceRef": "https://raw.githubusercontent.com/openfootball/worldcup/master/2006--germany/cup_finals.txt"
    }
  ],
  "elo": [
    {
      "teamId": "angola",
      "rating": 1573,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "argentina",
      "rating": 1923,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "australia",
      "rating": 1798,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "brazil",
      "rating": 2034,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "costa-rica",
      "rating": 1722,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "croatia",
      "rating": 1838,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "czechia",
      "rating": 1830,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "ecuador",
      "rating": 1752,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "england",
      "rating": 1966,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "france",
      "rating": 1971,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "germany",
      "rating": 1898,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "ghana",
      "rating": 1616,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "iran",
      "rating": 1766,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "italy",
      "rating": 1944,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "ivory-coast",
      "rating": 1660,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "japan",
      "rating": 1789,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "mexico",
      "rating": 1903,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "netherlands",
      "rating": 1994,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "paraguay",
      "rating": 1776,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "poland",
      "rating": 1742,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "portugal",
      "rating": 1916,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "saudi-arabia",
      "rating": 1654,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "serbia-and-montenegro",
      "rating": 1770,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "south-korea",
      "rating": 1719,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "spain",
      "rating": 1901,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "sweden",
      "rating": 1859,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "switzerland",
      "rating": 1799,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "togo",
      "rating": 1592,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "trinidad-and-tobago",
      "rating": 1567,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "tunisia",
      "rating": 1703,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "ukraine",
      "rating": 1790,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    },
    {
      "teamId": "usa",
      "rating": 1852,
      "asOfDate": "2006-06-08",
      "sourceRef": "https://www.eloratings.net/2006_World_Cup_start"
    }
  ],
  "fifa": [
    {
      "teamId": "angola",
      "rank": 57,
      "points": 581,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "argentina",
      "rank": 9,
      "points": 746,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "australia",
      "rank": 42,
      "points": 612,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "brazil",
      "rank": 1,
      "points": 827,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "costa-rica",
      "rank": 26,
      "points": 683,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "croatia",
      "rank": 23,
      "points": 686,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "czechia",
      "rank": 2,
      "points": 772,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "ecuador",
      "rank": 39,
      "points": 631,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "england",
      "rank": 10,
      "points": 741,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "france",
      "rank": 8,
      "points": 749,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "germany",
      "rank": 19,
      "points": 696,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "ghana",
      "rank": 48,
      "points": 600,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "iran",
      "rank": 23,
      "points": 686,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "italy",
      "rank": 13,
      "points": 728,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "ivory-coast",
      "rank": 32,
      "points": 669,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "japan",
      "rank": 18,
      "points": 705,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "mexico",
      "rank": 4,
      "points": 758,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "netherlands",
      "rank": 3,
      "points": 768,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "paraguay",
      "rank": 33,
      "points": 653,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "poland",
      "rank": 29,
      "points": 677,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "portugal",
      "rank": 7,
      "points": 750,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "saudi-arabia",
      "rank": 34,
      "points": 651,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "serbia-and-montenegro",
      "rank": 44,
      "points": 610,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "south-korea",
      "rank": 29,
      "points": 677,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "spain",
      "rank": 5,
      "points": 756,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "sweden",
      "rank": 16,
      "points": 709,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "switzerland",
      "rank": 35,
      "points": 648,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "togo",
      "rank": 61,
      "points": 569,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "trinidad-and-tobago",
      "rank": 47,
      "points": 604,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "tunisia",
      "rank": 21,
      "points": 693,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "ukraine",
      "rank": 45,
      "points": 609,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    },
    {
      "teamId": "usa",
      "rank": 5,
      "points": 756,
      "rankingDate": "2006-05-17",
      "sourceRef": "https://en.fifaranking.net/ranking/index.php?d=2006-05-17"
    }
  ],
  "macro": [],
  "recentForm": []
};
